### ISSUE TITLE
All Mined Gems Turning to Rubies

### ISSUE THREAD

**Issue by cattrfly** [SilentChaos512/SilentGems#10]
I've never used GitHub before, so apologies if I'm reporting this incorrectly. Had a weird glitch start last night where any gems I mined turned into rubies if I looked at them while they were bouncing on the ground before I picked them up, or if they subsequently ended up on the ground, as happened when I broke a chest. The only way they didn't change was if they went into my inventory without me viewing them while they were bobbing around on the ground, so if I stood right next to the block while mining it, or if I quickly looked away after mining the block and then picked up the gems by backing or sidling into them. I could move them between inventories safely, as long as they didn't end up on the ground.

I'd just updated several mods in my game, but I think the most plausibly relevant changes that occurred before the "rubinization" began may have been my using "Finder Compass" and "Auto Ore Dictionary Converter" for the first time in my 1.8.9 instance (both are officially listed as compatible only up to 1.8.8, but I'd been told they should work with 1.8.9, which they seemed to do, as far as I could tell) - if I recall correctly, I did mine some gems before using them and the gems behaved normally. I realize that this means that the error may be somewhere in one of those mods, but since the only obvious effect I saw was to the items from SilentGems I thought I should report the problem to you first.

I'm playing MC 1.8.9, with Forge 1.8.9-11.15.1.1727, using MultiMC 5 - Version 0.4.7, Java 8 Update 71, on a MacbookPro running OSX 10.10.5 (Yosemite). Please let me know what MC logs or any other info you may need if you think this is something that bears investigation on your end.

**Comment by SilentChaos512** [comment]
Sorry for the trouble, and thank you for posting such detailed information! I think I know what the problem is and how to fix it. I should be able to take care of it sometime tomorrow. No need for logs, I think it's just me doing something silly with the ore dictionary a long time ago, before I knew any better...
