### ISSUE TITLE
[Request] Baubles Support

### ISSUE THREAD

**Issue by scottosx** [SilentChaos512/SilentGems#100]
It would be nice to have Baubles pendants for Chaos orbs and rings, belts or charms for Chaos gems. Here is the API: https://github.com/Azanor/Baubles

The jewelry aspect of the mod is kind of missing at this point.

It may help your mod to get much more exposure because many packs include Botania which installs Baubles by default. Thaumcraft is due to be updated anytime as well.

**Comment by SilentChaos512** [comment]
Baubles support is something I would like to do. I've also had a suggestion for making the Return Home Charm a bauble as well.

And thanks for taking the time to respond on #73!

**Comment by scottosx** [comment]
It seems like a natural fit. A good Bauble implementation of SG Chaos gems would exceed any current offering being customizable in color and buffs.

**Comment by SilentChaos512** [comment]
Still needs some work/testing, most likely. This required a lot more code than I thought, so I may not backport to 1.10.2.

**Comment by scottosx** [comment]
It may be easier to maintain backports if you implement CompatLayer https://github.com/McJty/compatlayer/wiki
