### ISSUE TITLE
[1.11.2] Client crash when adding enchantment token

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/SilentGems#102]
Description: When attempting to add a protection enchantment token to my boots, I receive this [client crash](https://gist.github.com/dirtyfargo/e1c75f4aa77fc8ea25556f0fbe98ab94) as soon as I place them both beside each other in any crafting grid. I haven't tested with other tokens/tools yet.
MC Version: 1.11.2
Version: 1.11-2.2.5-103
Silentlib: 1.11-1.1.3-28
Forge Version: 13.20.0.2214

**Comment by SilentChaos512** [comment]
Looks like Mojang changed the visibility on that method for reasons I can't even imagine. I'll look for a workaround.
