### ISSUE TITLE
JEI - SG Tools display You Broke It

### ISSUE THREAD

**Issue by scottosx** [SilentChaos512/SilentGems#104]
Whenever I hover over some Silent Gems tools and press R to show the recipe the icon of the tool goes white with a red 'x' over it and the tool tip says 'You broke it'?

The screenshot is from the flint pickaxe.

![image](https://cloud.githubusercontent.com/assets/5866215/22151683/c0496a8a-dee4-11e6-9298-c29822d99d08.png)

**Comment by SilentChaos512** [comment]
What version of Gems, JEI, and Forge?

**Comment by scottosx** [comment]
MC 1.10.2
Forge 12.18.2.2202
SG 1.10.2-2.2.5-103
Silent Lib 1.10.2-23
JEI 1.10.2-3.14.2_401

**Comment by SilentChaos512** [comment]
Doesn't happen for me. I know that what you are seeing is caused by tools losing their NBT, but I have no idea _how_ that's happening.

**Comment by scottosx** [comment]
Maybe related mods are causing it? I have Tinker's, Silent Gems: Extra Parts, and Gemulation (plus a bunch of other mods)
