### ISSUE TITLE
enchanting-related crash

### ISSUE THREAD

**Issue by Tyfyter** [SilentChaos512/SilentGems#105]
when I try to add a second enchantment on a bow it crashes Minecraft, I can put the crash log here if you need it, but I don't have access to my github account on my computer right now

**Comment by SilentChaos512** [comment]
Always link crash reports. I have no way of knowing what happened (or what version since you didn't list it) without the crash report.

**Comment by Katallask** [comment]
Silent, 
It's reproducible by taking a multi-supercharged-gem pickaxe and putting fortune on it then trying to add unbreaking with a enchantment token.. I was able to repro it several times consecutively.. here's the crash report too.. looks like the method that's dying is a null pointer ref on (what looks to me like ) a bool method.    

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/22/17 7:44 PM
Description: Updating screen events

java.lang.NullPointerException:
 Updating screen events
	at net.silentchaos512.gems.item.ItemEnchantmentToken.canApplyEnchantsTogether(ItemEnchantmentToken.java:194)
	at net.silentchaos512.gems.item.ItemEnchantmentToken.applyTokenToTool(ItemEnchantmentToken.java:228)
	at net.silentchaos512.gems.recipe.RecipeApplyEnchantmentToken.func_77572_b(RecipeApplyEnchantmentToken.java:44)
	at net.silentchaos512.lib.recipe.RecipeBase.func_77569_a(RecipeBase.java:23)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1244)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:52)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:92)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:189)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:581)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:552)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.silentchaos512.gems.item.ItemEnchantmentToken.canApplyEnchantsTogether(ItemEnchantmentToken.java:194)
	at net.silentchaos512.gems.item.ItemEnchantmentToken.applyTokenToTool(ItemEnchantmentToken.java:228)
	at net.silentchaos512.gems.recipe.RecipeApplyEnchantmentToken.func_77572_b(RecipeApplyEnchantmentToken.java:44)
	at net.silentchaos512.lib.recipe.RecipeBase.func_77569_a(RecipeBase.java:23)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1244)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:52)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:92)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:189)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:581)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:552)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Katallask'/218, l='MpServer', x=-151.67, y=66.00, z=58.99]]
	Chunk stats: MultiplayerChunkCache: 2401, 2401
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (168,64,256), Chunk: (at 8,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 807333 game time, 1000174 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntitySpider['Spider'/7174, l='MpServer', x=-178.69, y=66.00, z=-7.44], EntityCreeper['Creeper'/7187, l='MpServer', x=-103.50, y=63.00, z=20.50], EntityZombie['Zombie'/7194, l='MpServer', x=-132.50, y=19.00, z=121.50], EntityBat['Bat'/6433, l='MpServer', x=-126.54, y=23.10, z=-17.41], EntityCreeper['Creeper'/8482, l='MpServer', x=-153.50, y=65.00, z=8.50], EntitySkeleton['Skeleton'/8489, l='MpServer', x=-209.50, y=72.00, z=29.50], EntityZombie['Zombie'/8500, l='MpServer', x=-134.97, y=64.00, z=89.76], EntityZombie['Zombie'/7994, l='MpServer', x=-169.50, y=64.00, z=6.50], EntityCreeper['Creeper'/7995, l='MpServer', x=-92.50, y=48.00, z=-4.50], EntityBat['Bat'/7740, l='MpServer', x=-89.35, y=33.17, z=-2.15], EntityCreeper['Creeper'/8508, l='MpServer', x=-197.53, y=65.00, z=99.26], EntityCreeper['Creeper'/8515, l='MpServer', x=-130.50, y=21.00, z=-16.50], EntityPig['Pig'/584, l='MpServer', x=-127.37, y=65.00, z=138.78], EntitySpider['Spider'/6222, l='MpServer', x=-126.95, y=65.00, z=136.96], EntitySheep['Sheep'/848, l='MpServer', x=-214.73, y=65.00, z=-16.45], EntityBat['Bat'/7512, l='MpServer', x=-98.61, y=37.19, z=14.20], EntityBat['Bat'/7516, l='MpServer', x=-221.25, y=50.09, z=105.55], EntityCow['Cow'/606, l='MpServer', x=-83.16, y=67.00, z=60.50], EntityPig['Pig'/607, l='MpServer', x=-123.46, y=61.00, z=85.74], EntityWolf['Wolf'/608, l='MpServer', x=-115.44, y=51.00, z=95.49], EntityCreeper['Creeper'/5994, l='MpServer', x=-185.17, y=71.00, z=68.49], EntityBat['Bat'/8554, l='MpServer', x=-184.67, y=15.00, z=117.77], EntityWolf['Wolf'/619, l='MpServer', x=-142.70, y=61.36, z=118.60], EntitySkeleton['Skeleton'/6252, l='MpServer', x=-184.57, y=72.00, z=58.11], EntityPig['Pig'/623, l='MpServer', x=-149.59, y=63.00, z=133.24], EntityPig['Pig'/624, l='MpServer', x=-149.47, y=63.00, z=136.79], EntitySkeleton['Skeleton'/7542, l='MpServer', x=-166.27, y=28.00, z=115.46], EntitySkeleton['Skeleton'/7543, l='MpServer', x=-163.50, y=32.00, z=108.50], EntitySkeleton['Skeleton'/7548, l='MpServer', x=-76.50, y=67.00, z=137.50], EntityZombie['Zombie'/7556, l='MpServer', x=-118.50, y=66.00, z=138.50], EntityZombie['Zombie'/6537, l='MpServer', x=-182.22, y=64.00, z=136.59], EntitySkeleton['Skeleton'/6538, l='MpServer', x=-183.23, y=64.00, z=137.46], EntityBat['Bat'/8337, l='MpServer', x=-82.58, y=38.05, z=50.58], EntityBat['Bat'/7829, l='MpServer', x=-114.68, y=19.56, z=-8.20], EntityCow['Cow'/664, l='MpServer', x=-160.43, y=65.00, z=53.81], EntityCow['Cow'/665, l='MpServer', x=-162.93, y=65.00, z=55.05], EntitySheep['Sheep'/666, l='MpServer', x=-162.95, y=65.00, z=57.07], EntityCow['Cow'/667, l='MpServer', x=-163.67, y=65.00, z=54.02], EntitySheep['Sheep'/668, l='MpServer', x=-162.89, y=65.00, z=58.34], EntitySheep['Sheep'/669, l='MpServer', x=-163.93, y=65.00, z=58.16], EntitySheep['Sheep'/670, l='MpServer', x=-163.93, y=65.00, z=57.07], EntitySheep['Sheep'/671, l='MpServer', x=-163.93, y=65.00, z=60.92], EntityCow['Cow'/672, l='MpServer', x=-163.93, y=65.00, z=55.92], EntityCow['Cow'/673, l='MpServer', x=-163.93, y=65.00, z=53.07], EntitySkeleton['Skeleton'/8353, l='MpServer', x=-194.74, y=15.00, z=87.47], EntityPig['Pig'/674, l='MpServer', x=-160.08, y=65.00, z=48.07], EntitySpider['Spider'/7586, l='MpServer', x=-192.01, y=66.00, z=-5.00], EntitySkeleton['Skeleton'/8354, l='MpServer', x=-202.50, y=13.00, z=89.50], EntityPig['Pig'/675, l='MpServer', x=-160.69, y=65.00, z=51.48], EntityPig['Pig'/676, l='MpServer', x=-163.49, y=65.00, z=51.32], EntitySkeleton['Skeleton'/8356, l='MpServer', x=-198.50, y=13.00, z=88.50], EntityCow['Cow'/677, l='MpServer', x=-161.58, y=65.00, z=53.57], EntitySheep['Sheep'/678, l='MpServer', x=-161.84, y=65.00, z=57.80], EntitySkeleton['Skeleton'/6822, l='MpServer', x=-145.74, y=64.00, z=42.50], EntityPig['Pig'/679, l='MpServer', x=-160.39, y=65.00, z=49.62], EntityEnderman['Enderman'/8362, l='MpServer', x=-203.50, y=18.00, z=128.50], EntitySpider['Spider'/6576, l='MpServer', x=-77.50, y=63.00, z=43.50], EntityBat['Bat'/8115, l='MpServer', x=-123.50, y=19.12, z=-17.60], EntityBat['Bat'/8116, l='MpServer', x=-128.20, y=22.87, z=-16.90], EntitySkeleton['Skeleton'/7094, l='MpServer', x=-76.34, y=64.00, z=123.79], EntitySkeleton['Skeleton'/7095, l='MpServer', x=-81.37, y=64.00, z=114.72], EntitySheep['Sheep'/698, l='MpServer', x=-214.73, y=80.00, z=128.51], EntitySkeleton['Skeleton'/7101, l='MpServer', x=-164.29, y=64.00, z=22.49], EntitySkeleton['Skeleton'/7357, l='MpServer', x=-173.10, y=63.00, z=133.57], EntitySkeleton['Skeleton'/7102, l='MpServer', x=-155.47, y=66.00, z=20.73], EntityBat['Bat'/8383, l='MpServer', x=-216.71, y=46.39, z=119.75], EntityZombie['Zombie'/7363, l='MpServer', x=-87.50, y=46.00, z=-9.50], EntityEnderman['Enderman'/6340, l='MpServer', x=-159.50, y=63.00, z=99.50], EntitySheep['Sheep'/709, l='MpServer', x=-142.68, y=64.00, z=-14.24], EntityZombie['Zombie'/7625, l='MpServer', x=-119.50, y=44.00, z=36.50], EntityZombie['Zombie'/7375, l='MpServer', x=-181.50, y=55.00, z=130.50], EntitySkeleton['Skeleton'/8400, l='MpServer', x=-218.50, y=66.00, z=-5.50], EntityDonkey['Donkey'/722, l='MpServer', x=-194.99, y=67.00, z=71.14], EntitySkeleton['Skeleton'/8403, l='MpServer', x=-219.50, y=66.00, z=-9.50], EntityCreeper['Creeper'/8404, l='MpServer', x=-219.50, y=66.00, z=-6.50], EntityWolf['Wolf'/219, l='MpServer', x=-148.12, y=66.88, z=56.10], EntityWolf['Wolf'/220, l='MpServer', x=-147.30, y=66.00, z=59.76], EntityCreeper['Creeper'/8414, l='MpServer', x=-112.50, y=67.00, z=78.50], EntityCreeper['Creeper'/8415, l='MpServer', x=-111.50, y=67.00, z=82.50], EntityDonkey['Donkey'/736, l='MpServer', x=-200.75, y=67.00, z=92.12], EntitySkeleton['Skeleton'/8418, l='MpServer', x=-135.50, y=64.00, z=3.50], EntityPlayerSP['Katallask'/218, l='MpServer', x=-151.67, y=66.00, z=58.99], EntityCreeper['Creeper'/6890, l='MpServer', x=-138.50, y=64.00, z=-0.50], EntityWitch['Witch'/7660, l='MpServer', x=-181.50, y=19.00, z=107.50], EntityZombie['Zombie'/7408, l='MpServer', x=-77.50, y=68.00, z=18.50], EntityCreeper['Creeper'/7153, l='MpServer', x=-159.50, y=65.00, z=22.50], EntityZombie['Zombie'/8184, l='MpServer', x=-151.50, y=32.00, z=113.50], EntityZombie['Zombie'/7419, l='MpServer', x=-183.49, y=71.00, z=57.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2046354576 bytes (1951 MB) / 3758620672 bytes (3584 MB) up to 3758620672 bytes (3584 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xmn4G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2223 Optifine OptiFine_1.11.2_HD_U_B6 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2223.jar) 
	UCHIJAAAA	forge{13.20.0.2223} [Minecraft Forge] (forge-1.11.2-13.20.0.2223.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	silentlib{1.2.0} [Silent Lib] (SilentLib-1.11-1.2.0-30.jar) 
	UCHIJAAAA	silentgems{2.2.6} [Silent's Gems] (SilentsGems-1.11-2.2.6-106.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.1' Renderer: 'Radeon (TM) RX 480 Graphics'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2223
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.5.14008 Compatibility Profile Context 21.19.137.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-3800 APU with Radeon(tm) HD Graphics

**Comment by Katallask** [comment]
The first time I did it was with a book enchantment then added a token, so I tried the second time with just tokens for both enchants, and it died on that too.. It crashes as soon as you put the tool and the ench token onto the crafting table when it tries to render the target item.

**Comment by SilentChaos512** [comment]
So this is kind of related to #102. Just a matter of tracking down what is null.
