### ISSUE TITLE
Burner Chaos Generator won't work and only destroys items.

### ISSUE THREAD

**Issue by BreakTheWind** [SilentChaos512/SilentGems#106]
Putting an item in the Burner does nothing. I've tried putting any item, it's always the same. If I don't close the Burner window and try to retrieve my item, as soon as I click on it it disappears. If I close the window and then open the Burner again, the item is also gone.

Here's whats interesting tho:
When I open the Burner and put a single item from a stack in the slot, drop the rest of the stack in my inventory and close the burner, the stack I dropped in my inventory drops on the floor. Like when you put items in the crafting table and walk away from it.

I have 15 mods, some of which are OptiFine, Inventory Tweaks, Furniture mod.

Also, is there a way to increase the player's chaos energy? I want to use tools special ability without having to go to base to recharge so often (or bring the crystal with me).

P.S. 
{
This is one of the most awesome mods out there. What it's missing is a guide for the complex mechanisms. I understand you recommend an addon for that, but I tried many versions of that addon and all of them crashed at start or wouldn't work with my version.

For example: It took me LOADS of time to figure out that Supercharged item's abilities require Chaos Energy. There should be a notification for this. I read many of your guides, and watched many of your videos, after maybe 3 hours of searching I managed to figure out it needs chaos energy by reading some vague line in one of your overviews.
}

**Comment by SilentChaos512** [comment]
Also need to know the version of the mod and the Minecraft version, please.

**Comment by BreakTheWind** [comment]
Release 1.11.2 -forge 1.11.2-13.20.0.2224
"SilentsGems-1.11-2.2.4-101"

**Comment by BreakTheWind** [comment]
Update: It turns out the first Coal I put inside the Burner instantly disappears.
The second one I put inside stays there until I try to interact with it or exit the burner.

**Comment by SilentChaos512** [comment]
Fixed for next version (2.2.7). Will probably be released tomorrow.
