### ISSUE TITLE
Guide-API causing Ticking Memory Connection error when loading world

### ISSUE THREAD

**Issue by Moonalesca** [SilentChaos512/SilentGems#107]
Had this issue after installing the Guide-API. Removed it and the error disappeared. Here's my crash log for your reference. **http://pastebin.com/GC1RADQP**

**Comment by SilentChaos512** [comment]
Update Guide-API to 2.1.0-49 and try with Gems 2.2.9 when it's released. Those versions don't crash together. Sorry I couldn't figure out this one.
