### ISSUE TITLE
[request] Right click to harvest fully grown fluffy puff

### ISSUE THREAD

**Issue by MiagoMeowsome** [SilentChaos512/SilentGems#11]
Everything is in the title ! :D 
It would be a lot easier to harvest them without having to break the plant every time.

Ps : I don't know if it's the right place for me to ask request and if it's not I'm sorry ^^"

**Comment by SilentChaos512** [comment]
Sounds good, also gives me another idea to try...

And yes, this is the right place for feature suggestions! I accept them from anywhere, but GitHub is a nice place to keep everything organized.
