### ISSUE TITLE
1.11.2 Console error- NoSuchMethodError: net.minecraft.item.ItemBlock.func_

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#110]
https://gist.github.com/ProsperCraft/ee1367987ac3a0bc22fd445eefae6dff

Logs are attached.
[Errorreport.zip](https://github.com/SilentChaos512/SilentGems/files/730237/Errorreport.zip)

Modpack- One Elf Squared version 3.7.0

**Comment by SilentChaos512** [comment]
Is this crashing or just displaying error messages?

**Comment by ProsperCraft** [comment]
Only errors in console.
