### ISSUE TITLE
The Shift+C toggle special goes back to default

### ISSUE THREAD

**Issue by BreakTheWind** [SilentChaos512/SilentGems#111]
If I change the Shift+C hotkey to only C for item's special ability toggle, and I restart minecraft, it always gets reverted back to Shift+C.

**Comment by SilentChaos512** [comment]
What Forge version?

**Comment by BreakTheWind** [comment]
13.20.0.2224

**Comment by SilentChaos512** [comment]
Can't reproduce this, it always saves correctly for me. I'm guessing some other mod is doing this. If you give me a list of the mods you are using, I might be able to figure something out.

**Comment by BreakTheWind** [comment]
Better Sprinting
Inventory Tweaks
Just Enough Items
Journey Map

**Comment by thephoenixlodge** [comment]
It's not specifically that it goes back to default, but rather that it's insisting on having Lshift as part of it. Lewdicolo was encountering it continually changing to Shift-NUM5 when he had it set to NUM5
