### ISSUE TITLE
[1.11.x] Chaos Flower Pot does not save properly

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#114]
World reload causes the glow rose in the pot to vanish. Interestingly, the phantom lights do not disappear, but the flower pot's light level is changed correctly.

(correction) Seems to be client-server desync. The new glow rose I "placed" in the pot just reappeared in my inventory.

**Comment by ProsperCraft** [comment]
We have observed the same issue on our server, where the flower in the pot dissapears but light and the pot remains.
