### ISSUE TITLE
Silent's Gems crashes at startup

### ISSUE THREAD

**Issue by Tanden22** [SilentChaos512/SilentGems#117]
Hi,
I am getting a crash at startup, and i believe Silent's Gems is causing it.
Can you look into it?

Thanks.
[crash-2017-02-02_10.11.29-client.txt](https://github.com/SilentChaos512/SilentGems/files/748097/crash-2017-02-02_10.11.29-client.txt)

**Comment by SilentChaos512** [comment]
Any mods you added recently? This crash is caused by an enchantment from another mod, but I have no idea which one.

**Comment by Tanden22** [comment]
the only things i can think of that would add enchantments are Quark and possibly Roots

**Comment by SilentChaos512** [comment]
Seems to be the "Good ol' PvP" mod. It might be overwriting vanilla enchantments, which has caused enchantment token crashes in the past. I'll see if there's anything I can do about it.

**Comment by Tanden22** [comment]
ah. thanks!

**Comment by Tanden22** [comment]
it seems to be working without the Good Ol' PvP mod. Thanks for the help!
