### ISSUE TITLE
Vanilla sticks not craftable

### ISSUE THREAD

**Issue by DingoX3** [SilentChaos512/SilentGems#118]
All sticks have a tool tip showing its a tool rod.  
![2017-02-05_03 05 22](https://cloud.githubusercontent.com/assets/16032841/22624662/92904a96-eb50-11e6-8c03-37b8d657ca00.png)
![2017-02-05_03 05 18](https://cloud.githubusercontent.com/assets/16032841/22624664/98f10240-eb50-11e6-82ff-ecfbd93e6678.png)

Minecraft Version 1.11,2
Forge Version 13.20.0.2226
Silent Gems Version 1.11-2.2.28-112
Silent Gems Extra Parts Version 1.11-1.2.4-12
Silent Lib 1.11-1.2.0-30
Mod-Pack--> [One Elf Squared](https://mods.curse.com/modpacks/minecraft/256325-one-elf-squared)

**Comment by SilentChaos512** [comment]
Those sticks are exactly what they appear to be. I'm just adding information to the tooltip.

**Comment by DingoX3** [comment]
Ok thanks for they reply. I thought it might be adding other data to them. Im using a mod called vanilla magic and it requires you to rename a stick to "Stick Wand" in an anvil and im having an issue getting it to work so i thought it was the tool rod tool tip not allowing it to register properly.
