### ISSUE TITLE
Chaos nodes once moved caused major server lag

### ISSUE THREAD

**Issue by thejims** [SilentChaos512/SilentGems#119]
TPS reported about 24% of total TPS was around a chunk that had a handful of moved chaos nodes.  Upon TPing over to investigate client and server locked up pretty hard, see TPS reported below.  Area had ~6 chaos nodes and a dozen passive nodes.

[20:08:48] [TickProfiler/INFO] [TickProfiler/]:
TPS: 0.03333222
                     Single Entity | Time/Tick |     %
EntityPacketChaos -5189,69,-2969:0 |    43.439 | 0.146
EntityPacketChaos -5188,70,-2970:0 |    28.710 | 0.096
EntityPacketChaos -5188,70,-2969:0 |     3.861 | 0.013
EntityPacketChaos -5188,69,-2969:0 |     3.817 | 0.013
EntityPacketChaos -5187,69,-2970:0 |     3.675 | 0.012
         Chunk | Time/Tick |      %
 0: -325, -186 | 29780.418 | 99.953
 0: -324, -186 |     3.100 |  0.010
0: -312, -1003 |     1.975 |  0.007
  0: -118, 148 |     1.419 |  0.005
  0: -117, 148 |     1.262 |  0.004
All Entities of Type | Time/Tick |      %
   EntityPacketChaos | 29785.492 | 99.970
 passive.EntitySheep |     2.211 |  0.007
entity.EntityCitizen |     1.245 |  0.004
    EntityAntiPlayer |     1.025 |  0.003
 EntityAbyssalZombie |     0.847 |  0.003
Average Entity of Type | Time/tick | Calls
     EntityPacketChaos |     1.012 | 29440
      TileEntityHopper |     0.192 |     1
   passive.EntitySheep |     0.054 |    41
  entity.EntityDweller |     0.049 |     2
passive.EntityVillager |     0.045 |     7

**Comment by SilentChaos512** [comment]
I'll see if I can find anything. I've had reports like this in the past, but never had any luck figuring out the problem. Try enabling the "Direct Transfer" option under the "chaos" category. You may have to wait for existing problem packets to despawn, or find a way to kill them (I'm not an expert on server commands here).

**Comment by SilentChaos512** [comment]
Any news on this one?

**Comment by thejims** [comment]
No issues to report since toggling that option in configs
