### ISSUE TITLE
Strange client-side crash when crafting an item from another mod, but the crash only mentions this mod

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#12]
https://paste.ee/p/ynOYz

I really don't understand it. All I'm trying to do is craft the Holy Hand Grenades from [this fork of Reliquary](https://github.com/P3pp3rF1y/Reliquary) that's updated for 1.8.9, and trying to take the result out of the crafting grid causes this crash. I figured I'd post it to this mod instead of that one because the crash report clearly points to this one...

**Comment by SilentChaos512** [comment]
Very odd, but I should be able to fix it.

**Comment by Febilian** [comment]
For the sake of clarification, the recipe is shapeless and uses TNT, a gold nugget, and two items specifically from Reliquary. It's really weird that this mod is having issues with that.

**Comment by SilentChaos512** [comment]
I've done everything I can do, but still crashing. I created a new issue on the Reliquary repository. https://github.com/P3pp3rF1y/Reliquary/issues/44
