### ISSUE TITLE
crash on startup with latest version of Guide API

### ISSUE THREAD

**Issue by Hellcommander** [SilentChaos512/SilentGems#120]
minecraft crashes on loading on using the newest Guide-API-1.11-2.1.0-49.jar when silentgems is installed
removing silentgems allows it to continue
[crash-2017-02-17_20.40.19-client.txt](https://github.com/SilentChaos512/SilentGems/files/784685/crash-2017-02-17_20.40.19-client.txt)

**Comment by SilentChaos512** [comment]
Nice to hear there's a Guide-API update. I could never figure out the crash with the previous version (issue #107). At least this one looks like something fixable.
