### ISSUE TITLE
Dupe Glitch with gems

### ISSUE THREAD

**Issue by Puzzledlight** [SilentChaos512/SilentGems#121]
Got a dupe glitch between Actually Additions and Shinies Bag. Posted on his github, he told me to contact you. He suggested a fix, but I know nothing of code, so here's the link to that post. 
Adore your mod, btw.
 https://github.com/Ellpeck/ActuallyAdditions/issues/647#event-967584962

**Comment by SilentChaos512** [comment]
I don't make Gemulation, but I'll pass along the information.

**Comment by Puzzledlight** [comment]
My mistake! I assumed that Gemulation/Gems were by the same person! Thanks for the quick response.
