### ISSUE TITLE
broken pipe error w/ Quantus modpack

### ISSUE THREAD

**Issue by FenixFyreX** [SilentChaos512/SilentGems#122]
Hello, I've been attempting to install SilentLib/Gems into the 1.10.2 [Quantus Modpack](https://minecraft.curseforge.com/projects/quantus) but I've been having troubles getting them to play nice. To reproduce, simply install this modpack via a curse client, add SilentGems v1.10.2-2.2.5-103 and SilentLib v1.10.2-1.1.0-23, and try and connect to a server (you'll need two computers).

The game starts up perfectly, and I can generate / play a single player world. Conversely, I can host a server just fine. However when the client attempts to connect to the server, the client gets timed out with a "write(...) pipe error" and the server reports that the client's `caughtException()` handler caught a `ReadTimeoutException`. That is all the logs have to offer...it's quite cryptic.

I've noted that this only occurs if there are MineTweaker scripts to be sent to the client. If there are no files to 'sync', then the client connects, but even just one script will cause the error to occur. Interestingly, the error does not occur if JUST SilentLib/Gems, CraftTweaker, and script(s) are used.

The error also does not occur if SilentLib/Gems are not present. I am currently adding each mod one by one to see who / what the culprit is, or if it's simply too large a load (which should not be the case, modpacks with 3-4 times the load have worked fine in the past).

Any idea why this is happening?
Edit: It should be noted all this is happening on a local LAN setup. All ethernet coords have been checked, router is working just fine, etc.

**Server Specs:**
- ArchLinux 64bit
- Java 1.8.0_121 64bit
- Forge-1.10.2-12.18.3.2221

**Client Specs:**
- ArchLinux 64bit
- Java 1.8.0_121 64bit
- Forge-1.10.2-12.18.3.2221

**Comment by FenixFyreX** [comment]
I've tested every mod by itself and it seems not one single mod is causing this error (except for SilentLib/Gems)...it really seems that there is just too much to send between server/client, but that shouldn't be the case at all. I've caught a new error though (similar to the original):
`Internal Exception: java.io.IOException: Error while (read...): Connection reset by peer`. The server still says the same exact thing as before, and the logs give no hint about why this is happening.

**Comment by SilentChaos512** [comment]
I'll look into this as soon as I get the chance. Hopefully I will be off work on Friday...

**Comment by SilentChaos512** [comment]
Sorry I haven't had any time for this. Have you tried with recent versions? They run the latest 1.11 mod code on 1.10.2, so it might have fixed whatever obscure bug is causing this problem.

**Comment by FenixFyreX** [comment]
Will try when I have the time, and will report back with any logs / good or bad news. I had no idea the 1.11 version(s) would run on 1.10.2, so this very well could be a thing. Thanks :)
