### ISSUE TITLE
Chaos Gem NullPointerException Crash

### ISSUE THREAD

**Issue by scottosx** [SilentChaos512/SilentGems#124]
After creating an Onyx Chaos Gem I get this crash repeatedly causing world corruption and needing to restore from backup.

[crash-2017-02-28_22.11.30-client.txt](https://github.com/SilentChaos512/SilentGems/files/809673/crash-2017-02-28_22.11.30-client.txt)

**Comment by SilentChaos512** [comment]
Seems to be caused by a Chaos Rune that is somehow missing its NBT. The Chaos Gem isn't the issue. Should be easy to fix. I'll be sure to fix the 1.10.2 version as well, since that's what you're using.

I wonder if this has the same cause as #104? Something is wiping NBT from item stacks, presumably the ones being displayed in JEI. I see CodeChickenLib and Bookshelf in the crash report here, so it might be one of those.

**Comment by scottosx** [comment]
Could be. Bookshelf was not in the other mod pack but CodeChickenLib was. It is basically in all of my mod packs for ChickenChunks and Ender Storage at the least.

One thing that did happen prior to this crash was that I crafted a Flying Rune and as a test saved it to ProjectE. It stripped the NBT data out though and it was no longer the flying rune. I didn't pull it back out or try to install it, simply used the GUI 'forget' command. This should have only affected its record of the rune, I think.

There is some weirdness with ProjectE and runes as they all have the same EMC value of 6787 although different crafting materials. I don't yet know why.

ProjectE was not in the other pack though.

**Comment by scottosx** [comment]
Another weird thing though prior to the crash was that I have a full Refined Chaos Orb in my inventory. When I put in the Gem it started filling it. I didn't let it finish as I wanted to keep that Chaos so I put the Gem in an Altar. However it immediately filled to 2,000,000. 
That didn't make much sense but I was happy it did until the crash. I actually think that is the cause. Something with the Chaos buffer.

**Comment by SilentChaos512** [comment]
Not sure about the instant Chaos fill. I'll keep an eye out for it, but I believe I've got this crash fixed. It'll be in the next build, which is cross compatible between 1.10.2 and 1.11.x.
