### ISSUE TITLE
[2.3.0] crashes dedicated server Forge 1.11.2 build 2253

### ISSUE THREAD

**Issue by kreezxil** [SilentChaos512/SilentGems#127]
Notes:
     on startup, reported this too guide-api as well, this appears to effect extra parts as well so you can copy there too if you want

crash report:
https://gist.github.com/0f0e04ac4331b9969446f901a0a6e705

fml server latest:
https://gist.github.com/d1e1a4319ea2fb650fa93423e81cf7f4

this has also been reported to the guide-api guys @ https://github.com/TeamAmeriFrance/Guide-API/issues/62

**Comment by SilentChaos512** [comment]
Uploading new builds of Silent Lib (2.0.0-37) that fix the issue. Strange that it points to Guide-API in the crash report, but the log points to the real issue.
