### ISSUE TITLE
[1.10.2] Silent's Gems is missing mods with latest 1.10.2 silent lib

### ISSUE THREAD

**Issue by b0bst3r** [SilentChaos512/SilentGems#128]
SilentsGems-1.10.2-2.2.5-103
SilentLib-1.10.2-2.0.2-42

http://i.imgur.com/T7fXPPb.png

**Comment by SilentChaos512** [comment]
Either update Gems or downgrade Lib, those two versions are not compatible.

**Comment by b0bst3r** [comment]
The 1.11.x ones work on 1.10.2?

I picked the latest 1.10.2 one from curse - http://imgur.com/aJxDDAQ
And the latest 1.10.2 SilentLib from curse - http://i.imgur.com/RbQhy2H.png

Those 2 aren't compatible, so I use SilentsGems-1.10.2-2.2.5-103 with SilentLib-1.10.2-1.1.0-23 

Curse is very misleading

**Comment by SilentChaos512** [comment]
Silent Lib 2 allows properly designed mods for 1.11 and 1.11.2 to run on 1.10.2.  It's basically CompatLayer, but with some minor differences. All cross compat builds (Lib, Gems, and all) are currently marked as alphas.

The cross compat thing has been more of a mess than I thought it would be, but hopefully it will be sorted out soon. There are still some bugs, especially in Gems (missing textures and tools not displaying in JEI being 2 I'm aware of). But it means 1.10.2 users will be getting updates again.

**Comment by b0bst3r** [comment]
So what yer saying is use SilentLib2 for 1.10.2 and Silent's Gems 1.11.2 on 1.10.2?

**Comment by SilentChaos512** [comment]
Right.
