### ISSUE TITLE
[1.10.2] Loader Exception crash on game start

### ISSUE THREAD

**Issue by cattrfly** [SilentChaos512/SilentGems#129]
[crash-2017-03-13_01.27.22-client.txt](https://github.com/SilentChaos512/SilentGems/files/837353/crash-2017-03-13_01.27.22-client.txt)
Latest versions of Silent Gems & Silent Lib, Forge 2252, using Curse launcher.

**Comment by SilentChaos512** [comment]
I didn't think about Guide-API... That mod changes a lot version-to-version, so no surprise to me it's crashing when running on a different Minecraft version. I would suggest removing Guide-API for now if you don't need it and I'll start looking for a fix tomorrow.

**Comment by HDShatter** [comment]
Any updates on fixing the incompatibility? A lot of mods require guide api in 1.10.2 so updating atm is a no go.

**Comment by SilentChaos512** [comment]
The next version will avoid registering the guide book in 1.10.2 to prevent the crash until I can find a solution (or a less headache-inducing replacement for Guide-API). The band-aid fix will be out tomorrow evening, probably.

**Comment by SilentChaos512** [comment]
A new guide book system is being added to Silent Lib. The existing Guide-API book will be removed and Gems will create a Silent Lib guide book starting in version 2.3.7.
