### ISSUE TITLE
Flight Rune disappears when crafted with a Chaos Gem without adding its effect to the gem

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#13]
For the record, I've gotten a chaos gem with regeneration II on it already, so I assumed that the process of creating a flight one would be the same. As soon as I crafted the rune with a new and different chaos gem, though, it consumed the rune without doing anything visible. The gem does not say "Flight" anywhere on it and activating it does not drain charge - because it has no effects on it at all.

Am I missing something, or is that not intended?

**Comment by Febilian** [comment]
Okay, so I grabbed another rune from creative and crafted it with my new chaos gem when it had some charge in it, and it applied as normal. Maybe it only affects uncharged gems in the way I had a problem with?

**Comment by SilentChaos512** [comment]
It does seem like applying runes to an empty chaos gem does not work, I'll take a look at it.
