### ISSUE TITLE
[1.10.2] Crashing when using dual wield.

### ISSUE THREAD

**Issue by ItsTequila** [SilentChaos512/SilentGems#130]
The game crashes when you got an SilentGems tool in your right hand and places any kind of block with the left hand(dual-wield).
http://pastebin.com/SRWcEewf

Latest versions of Silent Gems & Silent Lib, Forge 2252.

You also crash when using a hoe and right click on any block.
http://pastebin.com/jdas0ptX

**Comment by SilentChaos512** [comment]
Probably a cross compat bug. I'll take a look at it.
