### ISSUE TITLE
[1.10.2] Crashes With Armor in Inventory 

### ISSUE THREAD

**Issue by HDShatter** [SilentChaos512/SilentGems#131]
Crash log:
http://pastebin.com/HSyBBM8K

Using latest versions of everything.

Happens always with iolite armor, it only crashes the client not the server and everytime you login it crashes immediately.

**Comment by SilentChaos512** [comment]
Looks like a cross compat bug, should be easy to fix.

**Comment by HDShatter** [comment]
Alright, if anyone has issues with it till a fix is out just delete the item with a NBT Editor and the crashes will stop.
