### ISSUE TITLE
[1.10.2] Planting Fluffy Puff Seeds Crash

### ISSUE THREAD

**Issue by hextrace** [SilentChaos512/SilentGems#132]
**Crashlog:** https://paste.ee/p/sYbvf

**Minecraft:** 1.10.2
**Forge:**  12.18.3.2254
**Mod Versions:**
- Silent Lib 2.0.5
- Silent's Gems 2.3.3
- Silent's Gems: Extra Parts 1.2.5

**Problem:** As the title suggests, when ever I attempt to plant the fluffy puff seeds the client completely crashes out. I planted other mod seeds to rule out the potential of a mod conflict and the crash log is essentially an enigma.

**Comment by SilentChaos512** [comment]
Ah, I should have thought of that. Fluffy puffs caused problems going to 1.11, so the 1.11 code fails on 1.10.2. Strange that it's a null pointer exception, but I should be able to get this figured out by tomorrow afternoon, at the latest.
