### ISSUE TITLE
[1.10.2] Right-click crash with shovels

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#133]
Like the title says, the game crashes when sneaking + right clicking on a Minecraft Wooden Door using the Sapphire Shovel. 

Might be every shovel.. not sure.
You'll have to test that.

EDIT: It just happened while i was NOT sneaking.

Also here's the crash message:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraft.item.ItemSpade.func_180614_a(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumHand;Lnet/minecraft/util/EnumFacing;FFF)Lnet/minecraft/util/EnumActionResult;

Other than that, love the mod. Keep up the great work!

**Comment by SilentChaos512** [comment]
Thanks for reporting this. In the future, be sure to give a full crash report (I think I'll be OK without it this time). Upload it to a site like Pastebin or Gist and give the link. It contains important info like the Minecraft/Forge versions and a full mods list.

I think it's safe to assume this is 1.10.2. And it would be all shovels, they're all the same item. Should be an easy fix.

**Comment by Gbergz** [comment]
Alright, yea sorry for not bringing a full crash log. 
And yes this is 1.10.2 Sorry for not mentioning that.
