### ISSUE TITLE
Crash in Creative Menu

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SilentGems#134]
Attempting to look at the second page of creative menu tabs (with only SG and SL installed) causes a crash.

https://gist.github.com/M4thG33k/75cdb2c90cf45ccab2df0b09351f1f6d

Edit: Using the most recent version of both Forge and SL/SG.

**Comment by hextrace** [comment]
Crashlog:  https://paste.ee/p/DaC7a
Minecraft ver:  1.10.2
Latest versions of SilentGems, Lib, and Extra ...

Piggy-backing to add more info ...

While not as stripped down, it appears that when clicking on the search tab in Creative, it causes a client crash.

**Comment by SilentChaos512** [comment]
@hextrace That crash seems unrelated to the first. I can't reproduce it, so I'm guessing some mod enchantment is responsible. Please give me a log file as well so I can track it down (crashing the game is not necessary, I just need the list of enchantments the Silent Lib dumps to the log).

**Comment by SilentChaos512** [comment]
@M4thG33k I think I have a fix for your crash, but I'm out of time right now, have to head to work. It's related to the new cross compatible creative tab class in Silent Lib not working if the stack is of a block. I'll have it fixed late tonight.

**Comment by hextrace** [comment]
@SilentChaos512 not to leave this hanging - I ended up rebuilding the modpack from scratch to get rid of some of the bloat (still using your and M4thG33k's mods). If I run into the problem again I'll issue another bug report to also include a dump the enchantments along with the crash-report.
