### ISSUE TITLE
[1.10.2] Right-Click with Shovel Crash

### ISSUE THREAD

**Issue by hextrace** [SilentChaos512/SilentGems#135]
Crashlog:  https://paste.ee/p/L3J4Y
MC Ver: 1.10.2
silentlib 2.0.5
silentgems 2.3.4

Client crashed when right-clicking on an Iron Door with a flint shovel.

**Comment by SilentChaos512** [comment]
Duplicate of #133, already fixed for next version. Just waiting for some other issues to be sorted out.

**Comment by hextrace** [comment]
My apologies ... I thought I checked to make sure, but I guess I didn't look closely enough.
