### ISSUE TITLE
1.10.2 no draining on chaos gems

### ISSUE THREAD

**Issue by Dowdysfate** [SilentChaos512/SilentGems#136]
I found out when you make a chaos gem with (example) flight on it, charge it a bit and just place the activated gem into a chest (or any storage). It wont drain any chaos charge (making it free unlimited flight) and works in different dimensions

**Comment by SilentChaos512** [comment]
Should apply to 1.11 as well. This bug existed in SG1 at one point and must have resurfaced in the rewrite.

**Comment by DennHenda** [comment]
Just had this happen on my 1.11.2 server.  I have a Flight + Recharge Gem.  If I activate it and drop it with Q, it functions normal and I no longer am able to fly.  If I click and move it from inventory, even dropping it to another player, I can fly indefinitely.  Which they can then do the same, and place it in a chest or share with another player.
So basically everyone on my server can fly forever now. lol

I understand there are newer versions, but these are the ones we're currently running:
SilentLib-1.11.x-2.0.5-45
SilentsGems-1.11.x-2.3.4-153
