### ISSUE TITLE
Crashing while loading up.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#137]
The game crashes while loading up the pack.
Minecraft Version 1.10.2
Latest Version Of SilentGems & SilentLib used.

Crash report here:
https://paste.ee/p/6xJOY

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/bf9f62416e968c289df2ac278c5ef97b

**Comment by SilentChaos512** [comment]
The 1.10.2 build of Silent Lib is missing some classes... again. I should have waited until after work to deploy, my bad for being in a rush. Strange it didn't crash my test pack though.
