### ISSUE TITLE
[1.10.2] Creative Tab Crash

### ISSUE THREAD

**Issue by hextrace** [SilentChaos512/SilentGems#139]
As promised, I'd reopen the issue if it happened again.  This time with all the additional enchantment data.  Crash happens specifically when I click on the Minecraft Creative Search Tab.  JEI search does not appear to be affected.

Crashlog: https://paste.ee/p/Kbggx

P.S. It can never be said enough but, "Thank you for all the work you do."

**Comment by SilentChaos512** [comment]
Thanks. I tried all the mods with enchantments in the list, but couldn't get it to crash. And I'm still not sure how [that line](https://github.com/SilentChaos512/SilentGems/blob/master/common/net/silentchaos512/gems/item/ItemEnchantmentToken.java#L282) creates an "array index out of bounds" when there are no arrays being accessed. I think I can still prevent the crash, but it would be better to know what is going wrong.

**Comment by SilentChaos512** [comment]
Any news on this? Does it still crash with the latest version?

**Comment by hextrace** [comment]
Just tested with the latest betas on Curseforge. Things appear to be working now.
