### ISSUE TITLE
Can't link teleporters on a server

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#14]
I don't get it, because in a previous version it was working fine; I place the two teleporters down in different places, but using the teleporter linker just says "Teleporter link started." and then when I right click on the second teleporter, it says the same message. At first I thought the issue was me attempting it cross-dimensionally, but then I tried in the same dimension(the Nether), and it still didn't work. I'm also noticing that the overlay showing the exp costs the further you get away isn't popping up either.

Actually I just grabbed a new linker from the creative menu and it's working with that(the exp overlay is popping up, anyways), so maybe it's just an issue with the teleporter linkers crafted in survival?

**Comment by SilentChaos512** [comment]
Probably an NBT issue, just fixed one like that for chaos gems. Should be an easy fix.

**Comment by SilentChaos512** [comment]
Fixed for version 1.3.10. Crafted teleporter linkers should work in 1.3.9 as long as they are not shift-clicked out of the crafting grid when crafting.
