### ISSUE TITLE
[1.10.2] Crash Using Torch Bandolier

### ISSUE THREAD

**Issue by joeamaroq** [SilentChaos512/SilentGems#140]
https://pastebin.com/LrjNjfLp

(edit) Extracted crash report for readability --SilentChaos512

**Comment by SilentChaos512** [comment]
Thanks for reporting. Next time be sure to upload the crash report to another site (Pastebin, Gist, etc.) and provide a link. Not a big deal, but it makes managing issues a bit easier.
