### ISSUE TITLE
name plate

### ISSUE THREAD

**Issue by jazzyworld** [SilentChaos512/SilentGems#141]
the anvil does what the silentgems:craftingmaterial (name plate) already does

my suggestion is to make it shift or ctrl right click on an entity with a named name plate in hand to rename the already placed object to what the name plate is made to.
the issue is that though you can rename anything, anvil or name plate, once you place said object in the world, its display name reverts back to the original.
example: hopper... renamed one hopper using the anvil naming system and another using the name plate, both had the specified name while in my inventory, but once i place the hopper into the world, its name was 'hopper'.  the only difference was that inside the hopper gui, the name was what the anvil/name plate set its name to. 
with my suggestion, the anvil can be used for non-placeable items, swords and armor etc, but the name plate can be used as a ctrl or shift click an already placed object to rename it in the world environment, so things like the storage scanner (rftools) or even Waila or The One Probe can see "furnace input" or "OreCrusherOutput" instead of just another listing of 'furnace' or 'crusher'.

**Comment by SilentChaos512** [comment]
I think I get what you're saying (that name plates don't work correctly on blocks?), but I'll have to try this myself. Names plates were originally added to rename tools that are "too expensive" to do through an anvil, and as a substitute for name tags. I've never tried it on blocks.
