### ISSUE TITLE
[Config Request] Option to disable spawning with the new guide book

### ISSUE THREAD

**Issue by thephoenixlodge** [SilentChaos512/SilentGems#142]
As per the title. Nothing against the book itself, I have it set up that the player receives an Akashic Tome with your guide included in it shortly after the start of the world, so having them spawn with it as well is a bit redundant.

**Comment by SilentChaos512** [comment]
Consider it done. Don't know why, but I thought Akashic Tome did something different. I'll have to try that out later.
