### ISSUE TITLE
[1.11.2] Server crash at start

### ISSUE THREAD

**Issue by kwpugh** [SilentChaos512/SilentGems#145]
Forge:      forge-1.11.2-13.20.0.2282-universal.jar

Mod:
SilentLib-1.11.x-2.1.1-56.jar
SilentsGems-1.11.x-2.3.9-168.jar

Crash report:    https://gist.github.com/kwpugh/fddc965b957c8f618f9edb2babf9e439

**Comment by EmosewaGamer** [comment]
I get the same

**Comment by SilentChaos512** [comment]
Likely caused by the new guide book features. I'm at work right now, so I
won't be able to fix it until late tonight.
