### ISSUE TITLE
Idea: Gem Pouch

### ISSUE THREAD

**Issue by joeamaroq** [SilentChaos512/SilentGems#146]
Mining with Silent's Gems in the pack can clutter the inventory quite rapidly. Would it be an idea to have a kind of back pack/pouch just for the 32 gem types? With auto pickup etc. and possibly more than one stack (256 or 1024) per gem type (tiered?)?

**Comment by SilentChaos512** [comment]
If you are on 1.10.2, you could use Gemulation's Shinies Bag. Looks like it hasn't updated to 1.11.2 yet though.

**Comment by joeamaroq** [comment]
Didn't know about that mod. Looks good. Have to check it out. Thanks for replying!
