### ISSUE TITLE
Tons of console spam on a server

### ISSUE THREAD

**Issue by Lewdicolo** [SilentChaos512/SilentGems#147]
Getting a ridiculous amount of console spam. Here's a pastebin of a sample

https://pastebin.com/7sE98PK1

Thanks!

**Comment by SilentChaos512** [comment]
Minecraft version? And versions of Gems and Lib?

**Comment by Lewdicolo** [comment]
1.10. Running  SilentsGems-1.11.x-2.3.7-161 and SilentLib-1.10.2-2.1.0-53

**Comment by SilentChaos512** [comment]
I think I see the problem. Strange it doesn't crash.

**Comment by SilentChaos512** [comment]
Little update on this: I encountered this today as a crash on a LAN game, so I can confirm this is fixed for next version. It's caused by trying to mine certain blocks with paxels. Might be 1.10.2-specific, but not sure.
