### ISSUE TITLE
Ruby Paxel Missing JEI Textures.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#148]
![2017-04-29_18 55 53](https://cloud.githubusercontent.com/assets/10351221/25559976/8305a77a-2d0d-11e7-8a19-09f119065fe4.png)
Title says it all 

https://minecraft.curseforge.com/projects/silents-gems/files/2412841

https://minecraft.curseforge.com/projects/silent-lib/files/2412839

**Comment by SilentChaos512** [comment]
Specifically ruby, or other types too? I haven't seen this happen myself,
and I am playing on 1.10.2 as well.

**Comment by P3rf3ctXZer0** [comment]
Just Ruby

**Comment by P3rf3ctXZer0** [comment]
Ruby everything is missing JEI Textures.

**Comment by SilentChaos512** [comment]
Interesting. Earliest I can look at it is tomorrow night. Any additional
information you can provide would be great, such as JEI version.

**Comment by P3rf3ctXZer0** [comment]
No problem.

**Comment by SilentChaos512** [comment]
I didn't see the screenshot on mobile. That looks like an NBT-less tool. So it's not ruby, it's a tool that is literally made of nothing. So I'm guessing it's just the Block Drops tab that has this issue? Do you know what mod adds it? Not sure how fixable this is though.

**Comment by P3rf3ctXZer0** [comment]
"So I'm guessing it's just the Block Drops tab that has this issue?" Yes it seems that way. @SilentChaos512

**Comment by SilentChaos512** [comment]
I wasn't able to find a way to randomize tools in GUIs, but I made the tooltips for data-less tools more descriptive, instead of just "You broke it!" (the fact that that message displays was kind of a bug anyway). I also fixed the "error" textures so they won't show missing textures. Hopefully that helps.
