### ISSUE TITLE
[Request + Ideas] Glow Rose Enhancements

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#15]
For example:

Idea 1: Make the glow roses renewable somehow;
- Allow them to be duplicated by bonemealing them, or have them sometimes show up with other flowers when bonemeal is used on grass.
- Maybe you can create 'seeds'   or '(gem name) fertilizer' or another kind of item to be used on grass blocks out of the gem shards and regular bone meal, which would then grow several their respective glow roses.

If some way to obtain more glow roses besides exploring new areas already exists in the mod, I'd love to know it!

Idea 2: Perhaps make a type of flower pot that the glow roses can be put in while retaining their glow/light source effect, since vanilla ones don't work to my knowledge. Maybe even a chaos-essence infused flower pot of sorts that enhances the glow effect somehow, like making the glow rose shine its light in a larger radius than default(could depend on the config setting, I know there's a configurable light level option for them by default), or gives potion effects to nearby players depending on what kind of flower it is(and maybe put a corresponding NEGATIVE effect on monsters that draw near to it; the next idea kinda ties into this). Bonus points if the flower pot changes its color depending on the glow rose inside of it... Hehe.

Idea 3: Maybe, if it's possible, allow each glow rose to be used as a potion ingredient in a brewing stand somehow? I suppose you'd need to assign each type of gem a default potion effect thematically to do that. Could base it loosely on the types of enchantment tokens that are made with each gem type. Also, maybe use gem shards of the same type for a potion that's by default more powerful than using just a glow rose.

For example, rubies are typically used in enchantment tokens that enhance the power/strength of a sword or bow(sharpness or power), so the obvious choice for that would be Strength as a potion effect. You could use a ruby glow rose, maybe, to get a strength I potion, but if you used a ruby shard instead, it could give you strength II or III instead, but with a shorter duration as the power increases.

If just using the glow rose itself would be too cheap for a potion ingredient, you could also 'infuse' them somehow first, like with some chaos essence, before they can be used in potions.

I personally like the glow roses quite a bit, they're pretty, and they're a good source of dye besides. S'ok if you don't wanna do any of this stuff though.

**Comment by SilentChaos512** [comment]
It is possible to grow glow roses with bonemeal, but they have trouble spawning when non-vanilla tall grass is around/created as well.

I like some of these ideas, and will play around with them as time permits.

**Comment by SilentChaos512** [comment]
It's been a while since I added it, but 2a647fa57e5e1db131c7d6e2b24296ca27e12330 added chaos flower pots, which can hold glow roses and amplify their light, while also placing additional light sources a short distance away (Minecraft 1.9+ only). Still looking into other potential uses for glow roses.

**Comment by TyoAtrosa** [comment]
Possibly add a way to grow specific glow roses by placing a block of the desired gem in the ground surrounded by dirt and bonemealing it, growing only the desired rose? maybe also allow the dies from them to be used to decorate items without repairing them, as a way to change the appearance of tools and armor without wasting valuable gems.

Love the flower pots, how about a hanging planter version? either hang from wall or ceiling would be awesome.

How about Gem Golems, crafted by placing a Chaos Node or Pylon atop 4 Gem blocks like an iron golem, with each color of gem giving it different stats and abilities? possibly allow them to be commanded with a scepter.

**Comment by scottosx** [comment]
It is needed to have a type of bonemeal like the Floral Fertilizer in Botania which will place a variety of glow roses. As is, there is no way to use this mod in a SkyBlock world. If there is then I would like to know how.

**Comment by scottosx** [comment]
I do see now that SkyResources is supporting your mod for gem production. https://mods.curse.com/mc-mods/minecraft/243482-sky-resources  You can even get Chaos essence but it is really a grind, no automation.

I have also been playing with the Void Ore Miner from Environmental Tech. https://mods.curse.com/mc-mods/minecraft/245453-environmental-tech

It pulls your ores from the Void but not the Chaos Ore for some reason. I have had it running for several MC days and have pulled over 1000 ores. Again, your gems are coming up but you can't get very far without Chaos Essence.

**Comment by SilentChaos512** [comment]
I'll get the glow rose fertilizer in the next update. Bonemeal used to work, but I think I didn't add that back in during the rewrite, for whatever reason.

Second comment is unrelated, so I wish you had made a new issue, but...

I just checked out SkyResources. It does seem to have built-in support for Gems (always nice to see, I thought my work was kind of niche). I can see how getting the Chaos Essence could be a pain.

An idea I've had before (or maybe suggested to me) was a block that can create Chaos Essence. Ideally something that takes a lot of Chaos energy to produce each piece, but that would be perfect for sky block packs. I'll look into that when I get some time, or maybe I'll ask M4thG33k to add it to Gemulation if he wants.

**Comment by scottosx** [comment]
A suggested recipe for the Glow Rose Fertilizer is one bonemeal and chaos essence, assuming there is a way to get the essence in limited resource cases.

Glow roses and the Chaos flower pot could have great use in a sky block where you need lots of light to keep mobs at bay. They would also liven up what is otherwise a pretty dreary world.
