### ISSUE TITLE
Tomahawks do not throw

### ISSUE THREAD

**Issue by aziel13** [SilentChaos512/SilentGems#152]
It appears the the right click functionality for tomahawks is not working in silents gems 2.3.8. I also tried updating to the latest release for minecraft 1.10.2 (v2.3.11) but i still could not throw an axe.
 I originally thought it might be an issue related to playing on a pack with a large number of mods(FTB BEYOND with 18 other mods in addition to silents gems). So I also tried this with only just enough items v 3.14.7.416 installed in addition to the required version of silent lib for each and I was still unable to get it to throw an axe.

**Comment by SilentChaos512** [comment]
Looks like a cross compatibility bug. Works fine on 1.11 (aside from the usual broken renderers), wrong methods being called on 1.10.
