### ISSUE TITLE
Material Grader + Hopper

### ISSUE THREAD

**Issue by TamaKun89** [SilentChaos512/SilentGems#153]
When I am using the material grader connected to a hopper i'll get this: 
![material_grader](https://cloud.githubusercontent.com/assets/19834703/25845758/5c81768e-34af-11e7-9909-0b01c9945aaa.png)

The error on the console is thrown every time i am opening the grader, one item with quantity 0 will always be there. Everything actually works fine so it's just a minor bug, no items get lost or anything, at least till now.

Error Log:

> [11:52:49] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.silentchaos512.gems.inventory.ContainerMaterialGrader.func_75138_a()Lnet/minecraft/util/NonNullList;
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> Caused by: java.lang.NoSuchMethodError: net.silentchaos512.gems.inventory.ContainerMaterialGrader.func_75138_a()Lnet/minecraft/util/NonNullList;
> 	at net.silentchaos512.gems.inventory.ContainerMaterialGrader.func_75132_a(ContainerMaterialGrader.java:34) ~[ContainerMaterialGrader.class:?]
> 	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) ~[FMLNetworkHandler.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
> 	at net.silentchaos512.gems.block.BlockMaterialGrader.clOnBlockActivated(BlockMaterialGrader.java:79) ~[BlockMaterialGrader.class:?]
> 	at net.silentchaos512.lib.block.BlockContainerSL.func_180639_a(BlockContainerSL.java:179) ~[BlockContainerSL.class:?]
> 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
> 	... 5 more

**Comment by SilentChaos512** [comment]
1.10.2?

**Comment by TamaKun89** [comment]
yes 1.10.2 (knew i forgot something important, kinda embarassing knowing i am a software developer in training, well hope i'm not forgetting important stuff in my exams tomorrow :P)
