### ISSUE TITLE
Extract items and pylon render bug

### ISSUE THREAD

**Issue by DennHenda** [SilentChaos512/SilentGems#156]
Couple of small ones.
Can't seem to extract items from holding gems or torch bandoliers, though I haven't tried without other mods so I don't know if it's a conflict issue. It's been that way for awhile now, just didn't have any problem till I needed to pull something from a holding gem.

The sword/katana/scepter spells look awesome, but now pylons fire big cubes everywhere.

**Comment by SilentChaos512** [comment]
What Minecraft version are you playing on?

1. I've seen the extraction issue occasionally on FoolCraft (adding in my mods, of course), but it usually works on the second or third attempt. If sneak-left-clicking in the air doesn't work, try looking at a block while you try. Let me know if you can find anything that works.
2. So I fix one set of renderers and the other set breaks. Seems about right...

**Comment by DennHenda** [comment]
I'm on 1.11.2, also I haven't tried in single player, only on a server. I've tried all sorts of methods, tried with auto collect on/off, shift left clicking everywhere on blocks and in the air, even tried in off hand.
I will test with just your mods, and try to narrow it down by adding one or two at a time.

**Comment by DennHenda** [comment]
Interestingly, item extraction works on single player! Perhaps there is a setting on the server that has unintentionally disabled it?

**Comment by SilentChaos512** [comment]
I have a fix for the extraction bug, just needs a bit more work. Do sword
projectiles also not work on servers? That should be the case, but I forgot
to test. I'll make sure both are fixed, but won't be able to work on this
anymore until late tomorrow.

**Comment by DennHenda** [comment]
Yes, sword projectiles work offline and online.  Just the pylons are weird for me.
