### ISSUE TITLE
Forge 2298 Server is Crash  

### ISSUE THREAD

**Issue by 2mrwtoday** [SilentChaos512/SilentGems#158]
**Crash Log:**
https://pastebin.com/L8DpJRH2

Server is crash why could it be ?

**Comment by SilentChaos512** [comment]
Any additional information you can provide would be great. I can't get this crash to happen. One odd thing I noticed is that "heliodor" is spelled with a dotless i in your crash report (line 54). Any idea why?

**Comment by 2mrwtoday** [comment]
I don't know. This error occurs only in 2 modes silentgems and ironchests.

**Comment by SilentChaos512** [comment]
I'm stumped. Running a server does not crash for me. Try updating Forge and re-downloading Silent's Gems. I wonder if maybe this is something to do with your system locale, although I can't see how that would be a problem.

**Comment by 2mrwtoday** [comment]
No problem after setting the operating system's language to English. Thanks for being helpful !

**Comment by SilentChaos512** [comment]
That's strange, but I'm glad to hear it's fixed.
