### ISSUE TITLE
Holding Gem Server Minor Text Issue

### ISSUE THREAD

**Issue by FatalError379** [SilentChaos512/SilentGems#159]
The Holding Gems, when turning them off and on, on a server, with [Shift+RightClick] it comes up as "autofill:2On" and "autofill:4Off". the auto-fill does work though. 
SilentGems Version:1.11.x-2.3.12-181
SilentLib Version:1.11.x-2.1.3-59

**Comment by SilentChaos512** [comment]
Try updating to the latest versions of Gems/Lib, that should fix the
left-click issue at least. Let me know what is still broken after that.
