### ISSUE TITLE
Chaos Pylon Particles Spastic

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SilentGems#16]
It seems as though what used to be straight-line particles between pylons and the altar are now randomly placed particles in the general area. I'm not sure if this was intended or not, but thought I should report it just in case...

**Comment by SilentChaos512** [comment]
I was wondering when this would get reported. Something broke when porting from 1.8 -> 1.8.9, but I'm not sure what. I'll look into it sometime.

**Comment by M4thG33k** [comment]
Depending on when I get the models working, I could take a look at the particles too...if you want the help...
