### ISSUE TITLE
[Feature Request?] Right click with harvest tool and bandolier

### ISSUE THREAD

**Issue by Ozzymud** [SilentChaos512/SilentGems#161]
Is this feature supposed to only work with your tools? The book kind of makes it look like any harvest tool will work. Works find with a SG pick but does not with Tinker tools, the Adventurer's Pickaxe, vanilla tools, or any others I tested.  

Would it be possible to get a config option to add "harvest tools" to a list? Something like:

    S:"Bandolier Tools" <
        tconstruct:pickaxe
        tconstruct:hammer
        psi:psimetal_pickaxe
        convenientadditions:adventurerspickaxe
        minecraft:stone_pickaxe
        embers:pickaxe_copper
     >

The list would be a pretty long one. This would be a really cool addition especially for like the Tinkers' Hammer, it used to have that functionality by default in 1.7.10 and I sorely miss it :)

**Comment by SilentChaos512** [comment]
It is supposed to be only gem harvest tools. Looks like it might be possible to override or add to the right-click behavior of items from other mods. I'll see what I can do.

By the way, super-tier gem pickaxes/shovels/paxels have the Area Miner skill, which let's them mine a 3x3 when activated. Just like hammers/excavators.

**Comment by Ozzymud** [comment]
That's handy info for sure. My tinkers pick has already been replaced by a higher tier gem pick, I love the vein miner feature of it. There are some ores it does not detect as well, maybe a similar config for that as well?
