### ISSUE TITLE
Post Init crash with Ender IO

### ISSUE THREAD

**Issue by Revvilo** [SilentChaos512/SilentGems#165]
After updating Silent's Gems my pack is now crashing due to a tussle between Ender IO and Silent's Gems reportedly caused by SG asking `[net.silentchaos512.gems.item.ItemEnchantmentToken:canApplyEnchantsTogether:201]` about the enchantment "Soulbound" from Ender IO.
Which is then throwing
`java.lang.NoSuchMethodException: net.minecraft.enchantment.Enchantment.func_191560_c(net.minecraft.enchantment.Enchantment)`.

- Tested with _just_ Ender IO and Silent's Gems
- Downgrading Silent's Gems to the previous version (2.3.14-182) fixes the crash
- Log with Debug Mode on • https://pastebin.com/bUzbb9Yi
- MC Ver • 1.10.2
- Silent's Gems Ver (that causes crash) • 2.3.15-184
- Silent Lib Ver • 2.1.4-61

**Comment by SilentChaos512** [comment]
Not entirely sure how this wasn't broken before, but I definitely broke it this time. Will fix right away.
