### ISSUE TITLE
[Compat] Placing blocks with a tool ignores "LevelUp!"'s NoPlacing NBT tag

### ISSUE THREAD

**Issue by thephoenixlodge** [SilentChaos512/SilentGems#166]
To prevent infinite duplication of ores with it's mining skill, LevelUp! applies a custom NBT tag which prevents the placing of the block.
As per the title, placing using a tool bypasses this, allowing infinite duplication of ores. Any chance compat could be added here?

**Comment by SilentChaos512** [comment]
Sure, I'll look into it.

**Comment by SilentChaos512** [comment]
I'm guessing you're playing on 1.10.2? I tried loading up the latest version of the mod in my development environment (1.11.2) and it's completely different from what I remember. The bonus ores are now items, but I should still be able to fix the issue with older versions.

**Comment by thephoenixlodge** [comment]
Sorry for the delayed response, but yea, 1.10.2. Looks like it got fixed in the latest version, so thanks.

**Comment by SilentChaos512** [comment]
Great, thanks for letting me know.
