### ISSUE TITLE
"Connection-crash" on Shift-left clicking with katana.

### ISSUE THREAD

**Issue by DeadSix27** [SilentChaos512/SilentGems#168]
Go into creative mode give yourself supercharged katana then shift left click, causes disconnect with errors (not a full on crash)

Stacktrace: https://gist.github.com/DeadSix27/aeea24a14c8bae8cf6d0b6baa27516b0

**Comment by SilentChaos512** [comment]
com.mjr.extraplanets... I'm guessing that's "More Planets Extras" by MJRLegends? I'm not having any issues on a 1.10.2 server with just Gems installed, so it's probably an issue with that mod.

**Comment by DeadSix27** [comment]
@SilentChaos512 Ah sorry, I didn't check the last entry in the stacktrace properly. I'll report that to more planets.

EDIT: Closed as this is not caused by @SilentChaos512 's mod
