### ISSUE TITLE
[1.12] Recipe list crash

### ISSUE THREAD

**Issue by donqixot** [SilentChaos512/SilentGems#170]
Thank you for this mod! It is really cool!
Using latest forge 14.21.1.2387, if I try to open inventory and press "Recipe" button (new 1.12 vanilla feature), I get crash. I double checked, it is from SilentGem+SilentLib. Crash report doesn't indicate it is from this mod, but nothing else is installed. I tried with other mods, no crash.
[crash-2017-06-29_10.08.56-client.txt](https://github.com/SilentChaos512/SilentGems/files/1112332/crash-2017-06-29_10.08.56-client.txt)

**Comment by SilentChaos512** [comment]
Confirmed, I'm also crashing with the latest Forge. Might take some time to figure out which recipe(s) are at fault.

**Comment by SilentChaos512** [comment]
Seems I was registering most recipes twice. Not sure how that caused this kind of crash, but it's fixed.
