### ISSUE TITLE
TiC support is broken

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#174]
Tried in both 1.10.2 and 1.11.2. TiC parts are not even being registered, as far as I can tell.

**Comment by Gr8umbreon** [comment]
I'm having this same issue but in 1.12. The Chaos Node keeps "Spitting" out the durability repair packet to try and repair a Tinkers Pickaxe but the durability does not move. Tested with Stone Tinkers Pickaxe at 71 durability.
