### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by TechnicianLP** [SilentChaos512/SilentGems#182]
- The build.gradle is incomplete/wrong there are dependencies (SilentLib, Baubles) missing as well as ones incompatible with the specified minecraft-version (Mantle, Tinkers) (which prevented me from running/compiling/making a pr)
- Registering things by calling `IForgeRegistry.register(thingy)` has been discouraged in favor of registry events (`RegistryEvent.Register<? extends IForgeRegistryEntry>`  which should be used for all registries in `ForgeRegistries.class` (this system was introduced in 1.10.2)(IRecipe should be added through json))
- The textures you stitch to the atlas could use a cleanup ([Texture-Atlas Dump](http://silentgems.tcnicn.com/minecraft_textures_atlas_blocks.png_mipmap_0.html)) (if you can tell me how i can get your mod to build, i could do that (without changing how things look ingame))

**Comment by SilentChaos512** [comment]
- I include Lib and Baubles by placing them in the libs folder. I didn't realize Tinkers had updated. I normally just leave dependencies like that alone until they update. That way my mod will still build without having the remove/edit any code.
- I am, see Silent Lib's SRegistry: https://github.com/SilentChaos512/SilentLib/blob/1.12/common/net/silentchaos512/lib/registry/SRegistry.java#L355. I'd rather not add recipes via JSON if I can avoid it. That would be hundreds of additional files.
- Sure, go ahead. The rendering side of things has never been my strong point.

**Comment by TechnicianLP** [comment]
if i understood you correctly - the 1.12 workspace works by just compiling against the outdated mods but not including them in the run-configuration?

**Comment by SilentChaos512** [comment]
Right. That way the code is never called. Then it just has to be updated whenever the other mod(s) update.

**Comment by TechnicianLP** [comment]
Finally managed to load a world in a dev-environemnt ... (5 hours of work yay - stupid intellij bugs)
[This](https://hastebin.com/sicelituyu.gradle) is what the current build.gradle looks like now (including a workaround for intellij)

**Comment by TechnicianLP** [comment]
Could you provide an export of your formatter-settings? (and/or codestyle preferences) (its quite a bit different than what i use normally ...)

**Comment by SilentChaos512** [comment]
I mostly follow Google's style guide for Java: https://google.github.io/styleguide/javaguide.html.
Here are my clean up and formatter exports from Eclipse:
[formatter.zip](https://github.com/SilentChaos512/SilentGems/files/1159581/formatter.zip)

**Comment by TechnicianLP** [comment]
- Ok ModelGemArmor now is a bit cleaner now (and works on armorstands) ([Changes on Fork](https://github.com/SilentChaos512/SilentGems/compare/1.12...TechnicianLP:1.12))
- Is the GemArmorModel-chestplate supposed to stick out by a pixel in the front?
- what is it with that newline at the start of each method? (some classes have it, some don't)

**Comment by SilentChaos512** [comment]
I didn't write the armor rendering code, that's M4thG33k's work. Can't say
I fully understand how it works. He follows a different style as well, and
I never bothered to format it.

I'll take a look at your work when I get home, and thank you for your help.

**Comment by TechnicianLP** [comment]
Btw: if you still have uncolored images of your items/blocks lying around ... i could use those ... (without having to uncolor them myself by guessing colors)

**Comment by SilentChaos512** [comment]
I don't, I usually started with ruby and adjusted HSV to create the others.
But you might check the "images" folder, there could be something you could
use as a reference in there.

**Comment by SilentChaos512** [comment]
There are a couple of things I don't understand here:
- In ItemGemArmor, you removed a couple of fields, but left references to them.
- There are errors in ArmorModelRenderer. I did just update Forge to 2435, maybe that has something to do with it. But compileDisplayList, displayList, and compiled are not visible.

**Comment by TechnicianLP** [comment]
forge has something called an 'AccessTtansformer' it reads a field called <modid>_at.cfg (silentgems_at.cfg) from your resources an changes the specified fields/methods to have at least the requested visibility - therefore you can then directly access them without reflection - but for it to work in your ide you have to rerun setupDecompWorkspace (and possibly refresh gradle)

**Comment by SilentChaos512** [comment]
Alright, I'll read up on that, thanks.

**Comment by TechnicianLP** [comment]
I just saw you already merged my changes - in the future please wait until i make a pr myself as the changes are not confirmed to be tested (or finished) otherwise ... 
I also saw you "fixed" the build.gradle again to increment the buildnuber again every time **any** gradle-task is run and to break intellij compatibility ... (did you have problems with it?)

**Comment by SilentChaos512** [comment]
Sorry, thought you had finished for some reason. I do remember having issues with the build.gradle, can't remember exactly what happened.
