### ISSUE TITLE
[1.10.2] Using swapping wand to collect nether gem ores causes crash

### ISSUE THREAD

**Issue by DwellerBenthos** [SilentChaos512/SilentGems#183]
This might be a bit rare, but playing Gangzcraft modpack, and using the swapping wand (from more wands mod I think?) which usually swaps a block in the world for one in your inventory (think a poor man's silk touch) causes a crash.

https://pastebin.com/9WPiUqjR

This doesn't happen with the overworld gem ores (at least the ones I've come across), just the ones in the nether. Some can swap correctly and appear in the inventory, but have the missing texture grid pattern, but otherwise work like normal (I haven't tried putting them in a machine to double them, which is why I'm using the wand to pick up the ores and not a pick to mine them directly). I also haven't tried an actual silk touch tool to see if the same thing happens, because I just thought of it :/ 

The ores did not swap to my inventory that I know of, but popped out onto the ground, I haven't been able to load the world save yet, I need to look at it in MC Edit to see what's wrong, as it crashes as soon as the world starts to load.

This mod pack did have Foam Fix, which I originally thought might be the problem as it was mentioned in the original crash, but I removed the mod and it still crashes, not sure if that's relevant or not.

**Comment by SilentChaos512** [comment]
Looks like the wand is causing the blocks to have the wrong metadata somehow, as in outside of the allowed [0, 15] range. I'll take a look into the cause as soon as possible.

**Comment by SilentChaos512** [comment]
I can't get this to crash in either 1.10.2 or 1.12. It does give blocks with incorrect metadata to the player, but they place correctly. But I might have a fix. Uploading a new build (2.4.3) to Curse, let me know whether or not it fixes the issue.

**Comment by DwellerBenthos** [comment]
OK, the new version seems to work OK, at least it doesn't crash, but the items are still the wrong metadata. One thing I failed to mention originally when the crash occurred was that my inventory was full, and the swapping action instead of placing the block in my inventory, popped the item out into the world and it was the entities that caused the crash. But I also had a similar crash with the swapping wand on another mod's nether items but I didn't think much of it at the time. It also placed items in the inventory that had the "no texture" error. 

In a test world, silk touch worked fine, and the ores were mined properly. Ores mined with the swapping wand, then placed, then mined with silk touch then changed back to the proper item.

This is using Not Enough Wands (notenoughwands-1.1x-1.5.5), maybe I should report the metadata error on their tracker?

**Comment by SilentChaos512** [comment]
Couldn't hurt to report it to Not Enough Wands. Be sure to link back to
this issue. If it's something I'm doing wrong, I'd like to fix it. But
their repo only has the 1.7.10 code, so I could only guess what the problem
is.

**Comment by DwellerBenthos** [comment]
Posted on their issues page, but I think McJty is on vacation right now, so it might be a bit before there's a response. The link is posted here.
