### ISSUE TITLE
1.12 Burner pylon item dupe

### ISSUE THREAD

**Issue by tyler489** [SilentChaos512/SilentGems#185]
put a burnable item into a burner pylon and breaking it results into 2 of that item droping when the pylon is broken.. if u put a non burnable item in the pylon and break it only the pylon drops deleting the item... this may have something to do with SPongeforge 
silent libs 2.2.6
Silents Gems 2.4.3

**Comment by SilentChaos512** [comment]
Not having any issues myself, must be Spongeforge.
