### ISSUE TITLE
[1.12] Mixed Handle Materials Result in Random Tools

### ISSUE THREAD

**Issue by Rhuunin** [SilentChaos512/SilentGems#186]
Just downloaded the mod and I noticed after making a new world that when I made a tomahawk with a feldspar head with a stick + bone handle that it did not yield a feldspar tool at all. It ended up giving me a randomly generated tool (supercharged turquoise, onyx/opal, blue topaz, etc.) well beyond the mundane tier I was working with.

Took it up in a creative world and found that using a mixture of flint and feldspar in the head with a monotype handle worked as intended, regardless of mixture or placement. It appears to only be the tool handle that does this, and this outcome results from all tiers of tool rod materials.

Tools I've found to be effected: axes, tomahawks, shovels, pickaxes, scepters, paxels. Basically anything with two tool rod elements in their recipe. Bows, curiously, are unaffected. The feldspar bow recipe doesn't seem to be working in JEI. Despite being listed in JEI, I can't pull up a recipe for it but can craft it normally.

Replication: Place the material for one of the affected silent's gem tools in a crafting grid. Make sure that one of the tool rods is of a different material of the same tier.

![2017-07-30_19 08 30](https://user-images.githubusercontent.com/28795527/28757878-83ebabea-755a-11e7-8568-ab62cbb612bd.png)
![2017-07-30_17 56 37](https://user-images.githubusercontent.com/28795527/28757879-83ebe664-755a-11e7-9ec3-67bdb98e2d2c.png)
![2017-07-30_17 57 29](https://user-images.githubusercontent.com/28795527/28757880-83ec17ec-755a-11e7-8434-eee18ee7c7cf.png)

**Comment by SilentChaos512** [comment]
I think I see what the problem is. Mixing rods is not intended, so it's
reverting to the "example recipe" used for JEI support. This produces a
data-less tool, which is then randomized (to support the give command, loot
bags, etc.) Thanks for taking the time to test and report this.
