### ISSUE TITLE
[1.12] Chaos Flower Pot rendering issue

### ISSUE THREAD

**Issue by angelnc1989** [SilentChaos512/SilentGems#187]
Minecraft 1.12
Forge 14.21.1.2426
Silent's Gems 2.4.3b-209
Silent Lib 2.2.7-85

Glow Roses in Chaos Flower Pots stop being rendered. When I first put them down they were definitly visible.
![2017-07-31_18 13 39](https://user-images.githubusercontent.com/5382585/28787495-b63ca938-761c-11e7-913b-597f26b4c3a4.png)

After breaking and replacing them it looks like this.
![2017-07-31_18 13 46](https://user-images.githubusercontent.com/5382585/28787496-b63f1c22-761c-11e7-82d7-8d027884b3c6.png)

![2017-07-31_18 16 09](https://user-images.githubusercontent.com/5382585/28787497-b643524c-761c-11e7-8bbf-b23f88a5a647.png)

**Comment by SilentChaos512** [comment]
Seems the flower pot is not loading its data properly. Not sure about the black square, that's not happening for me.

**Comment by angelnc1989** [comment]
I can't reproduce the black square anymore either.
