### ISSUE TITLE
When putting two of a same type of tool/armor in crafting it will make a "Gem" item.

### ISSUE THREAD

**Issue by S10MC2015** [SilentChaos512/SilentGems#188]
When i put two of the same tool into crafting it gives me a gem item with a missing nbt
![image](https://user-images.githubusercontent.com/30575036/28790010-63cd7972-761f-11e7-9631-1bd0a87795ad.png)

**Comment by SilentChaos512** [comment]
You shouldn't be able to do that at all. What Minecraft version is this? (edit) Never mind, I should have looked more closely.

**Comment by S10MC2015** [comment]
1.12 version 2.4.3

**Comment by S10MC2015** [comment]
that pick and sword are from the bug

**Comment by S10MC2015** [comment]
version 2.4.3

**Comment by SilentChaos512** [comment]
I meant the vanilla "repair" recipe is supposed to be disabled, but seems it isn't. Thanks for reporting this.

**Comment by S10MC2015** [comment]
no problem and thx for being fast

**Comment by S10MC2015** [comment]
also thx for being fast

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/28791084-1bf4649a-7623-11e7-8618-2dfc3bb798eb.png)
umm

**Comment by S10MC2015** [comment]
also doesnt randomize
![image](https://user-images.githubusercontent.com/30575036/28791202-8bf7bbf2-7623-11e7-9055-e654dc114b92.png)

**Comment by thephoenixlodge** [comment]
Since it seems this only got fixed in the 1.12 branch, I'd like to point out that the vanilla repairing being available and giving NBT-less (and such randomized) tools is also a bug in the 1.10/11 branch. Any chance the fix could be applied there too?

**Comment by SilentChaos512** [comment]
Yeah, I'll reopen the issue.
