### ISSUE TITLE
[1.12] [Version 2.4.3] I cannot craft ornate silver rods

### ISSUE THREAD

**Issue by S10MC2015** [SilentChaos512/SilentGems#190]
![image](https://user-images.githubusercontent.com/30575036/28822934-2a4a7328-76b3-11e7-84e2-e41e3dd0fd23.png)

**Comment by SilentChaos512** [comment]
It requires silver ingots in the empty spaces.

**Comment by S10MC2015** [comment]
ok
sorry

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/28842403-7b6e8c0c-76f5-11e7-8f5a-eaa8c4ffb52f.png)
whut

**Comment by SilentChaos512** [comment]
I'm guessing you have no silver in your mod pack?

**Comment by S10MC2015** [comment]
no
