### ISSUE TITLE
SG Hoes cause crash in EnderIO Farming Station

### ISSUE THREAD

**Issue by thephoenixlodge** [SilentChaos512/SilentGems#196]
### Versions
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- SilentLib: 1.10.2-2.1.5-63 (also reproduced on 1.10.2-2.2.6-66)
- Silent's Gems: 2.3.16-186 (also reproduced on 2.4.5-213)
- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta

### Expected behavior

Farming station to work as per normal.

### Actual behaviour

As per title, using a hoe from SG in the farming station results in a crash when the farming station tries to work.
Reproduced both in the Sprout modpack, and in an instance with only EnderCore, EIO, SilentLib, SG and JEI.
Crash log: https://pastebin.com/Zzdqne3M

### Steps to reproduce the problem

1. Place EIO farming station
2. Add SG Hoe, any sort of seed and power (basically, meet reqs for the station to run with a SG Hoe).
3. Crash

Partner issue on the EIO github: https://github.com/SleepyTrousers/EnderIO/issues/4304

**Comment by SilentChaos512** [comment]
Shouldn't be hard to fix, thanks for reporting.
