### ISSUE TITLE
Coffee Drops from rabbits??

### ISSUE THREAD

**Issue by Zer0Lyfe** [SilentChaos512/SilentGems#197]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: SilentsGems-1.12-2.4.5-215
Silent Lib Version: SilentLib-1.12-2.2.7-85

### Expected behavior

- not dropping coffee cups

### Actual behaviour

- dropping coffee cups

### Steps to reproduce the problem

1. go to the desert 
2. wait for the rabbit to drop a coffee cup
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
This is the intended behavior.

**Comment by Zer0Lyfe** [comment]
ok. thank you for the comment.
