### ISSUE TITLE
[Bug] Auto Smelt Enchantment Dropping More than Expected

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#198]
Minecraft Version: 1.12
Silent's Gems Version: 2.4.5
Silent Lib Version: 2.2.7
Also using Silent's Gems: Extra Parts 1.3.2 (not sure if it matters)

### Expected Behavior
Auto Smelt on a Pickaxe or Paxel gives one ingot or one stone if mining minecraft stone/cobble stone. This is constant no matter if it's Ruby, Crystallized Chaos, or Heliodor.

### Actual Behavior
Auto Smelt on a Pickaxe gives multiple ingots if mining Thermal Foundation Tin Ore, or multiple Graphite Bars from Coal ore (smelting byproduct of coal from Extreme Reactors) and consistently a STACK of stone when just mining normal stone or cobblestone.

### Steps to reproduce the problem

1. Pickaxe or Paxel, craft with Auto-Smelt token
2. Mine cobble or various ores

If this is intended behavior, is there any way to configure this? I'm really eager to SG as the main tool mod for my progression pack but this one feature struck out to me as too powerful.

**Comment by SilentChaos512** [comment]
The Auto Smelt enchantment isn't one of mine. Hover over the token and hold the Alt key. That should give you the mod's ID at least.

**Comment by KAfable** [comment]
All right thanks, after just some general testing, it seems to be operate fine before I turn on Area Miner ability, however after turning on the Area Miner ability it will give me 9 stacks of glass from mining 9 blocks of sand, and seems to persist after turning off the Area Miner skill.

The Auto-Smelt is added by Cyclic, I'l post on PrinceOfAmber's Github and reference this there. Thanks again!
