### ISSUE TITLE
[Enhancement] Textures

### ISSUE THREAD

**Issue by porteriscool** [SilentChaos512/SilentGems#20]
Would you possibly consider having both options of using 16bit and 32bit textures to allow those who want 16bit the option to use it, while also providing a smooth feel with the people who would like to use 32bit. At the end of the day, it's up to you to decide whether you want this implemented or not; just a suggestion.

**Comment by SilentChaos512** [comment]
I'll consider making a 16x resource pack if I ever feel bored. The main issue is the mod contains about 840 textures right now...
