### ISSUE TITLE
Suggestion: Add a option or something to make chaos nodes output less particles

### ISSUE THREAD

**Issue by S10MC2015** [SilentChaos512/SilentGems#200]
all in the title

**Comment by SilentChaos512** [comment]
I thought they already respected vanilla particle settings. Does that not
help?

**Comment by SilentChaos512** [comment]
I was hoping to get some more feedback on this. For reference, nodes DO respect vanilla particle settings. On Minimal, it's 1 per tick, Decreased is 2, and All is 3. Is one per tick still too much for your system to handle? Or do you just need a separate setting for nodes specifically?

**Comment by S10MC2015** [comment]
I just want a separate setting as modded MC and a pillar of nodes don't mix
well and sorry I didn't reply I just haven't been on github for a while

**Comment by SilentChaos512** [comment]
I almost forgot, what's your Minecraft version? The new setting implemented in 3dd0980e645d53166eef073a50d8403c2f3f697e has only been done for 1.12.x. I can also update the 1.10/1.11 branch if necessary.

**Comment by S10MC2015** [comment]
I use 1.12 so thanks. Have a nice day.
