### ISSUE TITLE
Crash when disabling gems ore generation

### ISSUE THREAD

**Issue by AfterRebelion** [SilentChaos512/SilentGems#203]
### Versions

Minecraft Version: 1.12.1
Silent's Gems Version: 2.4.6
Silent Lib Version: 2.2.7

### Expected behavior

- Gems ores doesn't spawn on world

### Actual behaviour

- [Crash](https://gist.github.com/AfterRebelion/1a76afaa774450463720891d24007e35)

### Steps to reproduce the problem

1. Put these values on the config:
        "gems (overworld)" {
            I:"Max Y"=0
            I:"Min Y"=0
            D:"Vein Count"=0.0
            I:"Vein Size"=0
        }
2. Load a world, and generate new chunks.
3. Crash

**Comment by SilentChaos512** [comment]
Set "Max Y" to a higher number for now, I'll add a sanity check later.

Er, just out of curiosity, what do you do with the mod with no gems?

**Comment by AfterRebelion** [comment]
I changed every value on my testing to be 1 (0.1 on the double), and as long as one of the values is 0, the crash still happens.

And I am making a custom pack, wheere the gems come from loot chests on dungeons and the like, so that is why I need to disable normal world generation.

**Comment by SilentChaos512** [comment]
The min Y must be less than the max Y. They can't be the same.

**Comment by AfterRebelion** [comment]
Ooohhhh... well, that works for now, then. Thanks for the help.

**Comment by SilentChaos512** [comment]
Closed by 5395c4772c89a616d0ebf0340719ea7924d7a030
