### ISSUE TITLE
What Are Soul Gems Used For?

### ISSUE THREAD

**Issue by tyler489** [SilentChaos512/SilentGems#204]
Was not sure where to post this but what are soul gems used for in 1.12... looked in the book and couldnt find any info on them

**Comment by SilentChaos512** [comment]
No use currently, they just slipped in with the latest patch.

**Comment by tyler489** [comment]
prehaps they can be made into something like Mob spawn eggs? or a Supercharged Gem spawner?

**Comment by hron84** [comment]
Do you plan keep them until the correspondent feature done, or you'll hide them in the next patch?

**Comment by tyler489** [comment]
Would love to see something like craft 9 of them into a {mob} Grabbag. In which when opened would give x amount of items from said mobs loottable

**Comment by SilentChaos512** [comment]
The latest alpha builds (Gems 2.5) remove the drops, at the very least. They were used in the failed experimental branch for crafting an item to allow tools to level up. Still not sure yet if that item will make it into the main branch.

My original thought (unrelated to above) was to have something vaguely like Thaumcraft's research system to unlock some items. Certain soul gems would be needed for each item, so you would need to hunt/farm specific things. Obviously this is just a rough idea, so something may or may not come of it.

For now though, I'm just going to finish up the new gems (lots of missing textures and such). Then I plan on experimenting with some configs to change difficulty/balance. If you haven't already, don't forget to vote on the strawpoll regarding difficulty: http://www.strawpoll.me/13966373.

**Comment by hron84** [comment]
Could you keep the gems as items and configure to be enabled or not? These items could allow some modpacks to make an expensive crafting of spawn eggs/spawners for example. I could imagine e.g. Modern Skyblock let you make a spawn egg infusing an egg with 4 soul gems by AA empowerer.
