### ISSUE TITLE
[1.12.1] Game crashing without Tinker's Construct

### ISSUE THREAD

**Issue by angelnc1989** [SilentChaos512/SilentGems#207]
### Versions

Minecraft Version: 1.12.1
Silent's Gems Version: 2.5.0-223
Silent Lib Version: 2.2.8-88

### Expected behavior

- Game starting

### Actual behaviour

- Game crashing

### Steps to reproduce the problem

Crashlog: https://pastebin.com/xzWTC86p

I updated Silent's Gems to the latest alpha and the game crashes on startup. I guess with Tinker's Construct it will start.

**Comment by SilentChaos512** [comment]
Shoot, I uploaded the wrong build. I won't be able to get the fixed version
up until later tonight. But yes, it should work with TiC. Avoid flint tools
if possible.
