### ISSUE TITLE
[1.12.2] Missing Localization

### ISSUE THREAD

**Issue by TheLimePixel** [SilentChaos512/SilentGems#208]
Just listing all the light gem things that have missing localization in the 2.5.0 update to hopefully help you keep track of things and make this version stable faster:

- [x] TIC Tools
![image](https://user-images.githubusercontent.com/25333164/30616153-99b5b132-9d91-11e7-822a-fe6e357881f3.png)

- [x] Gem Bricks
![image](https://user-images.githubusercontent.com/25333164/30616176-af3ecaf2-9d91-11e7-8afb-719ac92cc795.png)
![image](https://user-images.githubusercontent.com/25333164/30616197-c7ae277c-9d91-11e7-86fc-cf51609ed9fc.png)

- [x] Inverted Lamps (for all gems)
![image](https://user-images.githubusercontent.com/25333164/30616218-d7657a30-9d91-11e7-973d-ef9aede75d35.png)

- [x] Glass 
![image](https://user-images.githubusercontent.com/25333164/30616457-9ba34c88-9d92-11e7-9c81-5f8102fb023f.png)

- [x] Teleporters 
![image](https://user-images.githubusercontent.com/25333164/30616473-a62553b8-9d92-11e7-9e5c-36ce73809f6b.png)
![image](https://user-images.githubusercontent.com/25333164/30616501-b36475fe-9d92-11e7-83aa-93e1c9227125.png)

I'm just listing the things with broken localization as they're much easier to fix. When it comes to textures, the light Chaos gems and Home Charms and the Chaos Pylons also don't have them.

**Comment by SilentChaos512** [comment]
That's most of the blocks fixed. So that leaves:
- [x] Pylons (A long-time issue. Seriously, these break every Minecraft version...)
- [x] Return Home Charms
- [x] Shields (Colors don't work properly)
