### ISSUE TITLE
[1.10.2] Crash on load with heavily modded game

### ISSUE THREAD

**Issue by capt-slowpoke** [SilentChaos512/SilentGems#209]
### Versions

Minecraft Version: 1.10.2
Silent's Gems Version: 1.11.2-2.4.7-217
Silent Lib Version: 1.10.2-2.2.6-66

### Expected behavior

- 

### Actual behaviour

-Game is crashing before loading finishes, possible mod conflict?  Willing to troubleshoot further, but I don't know where to start. 
Crash log: 
[crash-2017-09-19_18.45.33-client.txt](https://github.com/SilentChaos512/SilentGems/files/1316185/crash-2017-09-19_18.45.33-client.txt)

**Comment by SilentChaos512** [comment]
Log files might help. The crash report doesn't mention any mods in the stacktrace, it's just all vanilla classes. I checked, and the BlockModelShapes class does exist in 1.10.2, but it's client-side only. Not even sure what it's used for, I've never seen it.

**Comment by capt-slowpoke** [comment]
Here's the log file, would anything else be of use? 
[latest.log.txt](https://github.com/SilentChaos512/SilentGems/files/1319382/latest.log.txt)

**Comment by SilentChaos512** [comment]
Try updating Forge first, you're about 300 builds behind the latest.

**Comment by capt-slowpoke** [comment]
That was the problem, thanks.
