### ISSUE TITLE
[Bug/PEBKAC] Chaos Altar Transmutations not working

### ISSUE THREAD

**Issue by Timeslice42** [SilentChaos512/SilentGems#210]
Minecraft Version: 1.12.1
Silent's Gems Version: 2.4.8
Silent Lib Version: 2.2.8

I have the given transmutation recipe set up in the altar as shown in JEI (chaos shards + diamond catalyst or moonstone + slimeball, for example), the altar next to (two) chaos nodes, and a (fragile) chaos orb in my hand (or in a bauble slot), but the transmutation never happens. How do I make the transmutation start?

**Comment by SilentChaos512** [comment]
Try turning on debug mode (in the config under the "debug" category, set "Debug Mode" to true). Then check the altar's GUI. Do any of the number change as you insert/remove items from the altar?

Note that transmutations can take a while if the altar isn't charged up to begin with.

**Comment by Timeslice42** [comment]
It looks like my chaos orb and the chaos nodes are refusing to charge the altar, as its chaos always reads zero. Those same chaos nodes are happy to keep charging me, even while I'm standing directly on the altar.

**Comment by SilentChaos512** [comment]
It should be splitting the chaos evenly between you and the altar. An orb actually won't power the altar though. It has it's own buffer. Are the nodes within 6 blocks of the altar, and do they have a clear line of sight? Have you tried a pylon?

**Comment by Timeslice42** [comment]
![2017-09-25_16 24 44](https://user-images.githubusercontent.com/2825989/30829171-1fdc3788-a20e-11e7-8788-27e5a75f04c6.png)

**Comment by SilentChaos512** [comment]
Looks a bit too far away. The nodes look only 6 blocks out on each axis.

**Comment by Timeslice42** [comment]
So I moved the altar two blocks closer and now it's charging. I'd assumed that it would charge the altar at the same range it would me. Could you put this info in the guide, please? :)

At least now I'll be able to get more chaos gems so I can make pylons. Chaos gems were exceedingly hard to get in this skyblock, especially since I wasted 9 on two chaos orbs I thought I needed for the transmutation :P

**Comment by Timeslice42** [comment]
On a side note, it looks like the symbols on the altar got all jumbled up. Could that be because I enabled foamfix?

**Comment by SilentChaos512** [comment]
I'll make sure to update the guide. Leave the issue open for now. Not sure
about the texture problem, I'll look into it.

**Comment by Timeslice42** [comment]
Also, Optifine and BetterFPS is installed. I basically added all three at the same time.
