### ISSUE TITLE
minecraft version 1.12.1 silents gems 2.5.3 silents lib 2.2.9 harvesting issue

### ISSUE THREAD

**Issue by CharCharthemonkey** [SilentChaos512/SilentGems#213]
expected issue umm they work like normal tools

actual issue axes and shovels work for mining cobble and ores

steps to reproduce
craft any axe from the mod or shovel
mine cobble and ores
broken mod i think

**Comment by SilentChaos512** [comment]
Thanks for the report. I'm able to reproduce mining stone with an axe. I'll look into it.

**Comment by CharCharthemonkey** [comment]
![2017-10-05_18 40 13](https://user-images.githubusercontent.com/30783285/31314254-eaaffde8-abc1-11e7-843f-2bd015337d88.png)
![2017-10-05_18 40 31](https://user-images.githubusercontent.com/30783285/31314252-eaa94e8a-abc1-11e7-8b4d-4e5a665227ed.png)
![2017-10-05_18 41 08](https://user-images.githubusercontent.com/30783285/31314253-eaaa55d2-abc1-11e7-80a1-9b89ea187ea1.png)


these are wat shows for me using the tools in question
