### ISSUE TITLE
[Question] Any way to gate specific tools and tiers via CraftTweaker?

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#217]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.6

Hi I'm planning to use SG as the main tool mod for my upcoming 1.12.2 progression pack and had a question about possibility of gating the super tier at different times for different tools. For example I want to give the player the ability to make Super tiered pickaxes without giving them the entire super-tier suite of tools (as I think the combat weapons will be too powerful at that point in the pack).

The plan was to make all Super Tier tools that aren't a pickaxe require a later stage item - whereas Super Tier pickaxes will have the same recipe, is there a way to do this via CraftTweaker / is there CraftTweaker support with SG?

Was also hoping to apply this to Regular tier as well (although in my opinion the power level jump from Mundane to Regular isn't as material as the jump from Regular to Super so it's less important).

**Comment by SilentChaos512** [comment]
I'll look into adding CraftTweaker support. If for any reason that's not possible, I'll add my own solution.

**Comment by SilentChaos512** [comment]
Got everything working as far as I can tell. You can change recipes by tier, add arbitrary extra ingredients, and even change the shape of the tool recipe (for example, you could add/remove head material pieces if you wanted to). It also replaces the example recipes, so they will show up in JEI.

Here's an example script until I have a chance to write some proper documentation: https://gist.github.com/SilentChaos512/b57322c345ce58773bd73178fc932dbd

Please let me know how this works out for you. I tried to test this as thoroughly as possible, but haven't had a lot of time. It will be in version 2.5.7.

(edit) I'm also releasing 2.5.7 as an alpha build, so it will only be visible on CurseForge.
