### ISSUE TITLE
Dupe bug with Silent's Gems & Thermal Expansion

### ISSUE THREAD

**Issue by 1persON768** [SilentChaos512/SilentGems#218]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.4-228
Silent Lib Version: 1.12-2.2.9-89

### Expected behavior

- Thermal Expansion items not to dupe

### Actual behaviour

- Thermal Expansion machine/item duplicates

### Steps to reproduce the problem

1. Place any mineable block on top of Thermal Expansion machine
2. Use Silent's gems paxel 3x3 mode to mine the block
3. It duplicates the Thermal Expansion item when it "drops" (some funky things discovered also i.e. Pulverizer produced Redstone Furnace but most of them were just duplicates of harvested items)

There is right way and wrong way to do AOE mining and vast majority do it wrong way (PSI also has this same issue Tinker's and TF do not)

**Comment by SilentChaos512** [comment]
Confirmed. Definitely seems like TE is doing something weird with it's drops. Vanilla tile entities have no issues. I'll see if there's anything I can do to prevent this.
