### ISSUE TITLE
crafting anything with a chaos gem will only keep chaos gem

### ISSUE THREAD

**Issue by krakaen** [SilentChaos512/SilentGems#219]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.5.6-232
Silent Lib Version: 2.2.10-91

### Expected behavior

- when crafting something with the chaos gem that should not do anything, the recipe should not work or not use the item in the crafting and lose such item.

### Actual behaviour

- The item added with the Chaos gem gets destroyed in the process, does not matter what item is place with it in the crafting inventory or table.
ex : Chaos gem + Katana will destroy the Katana and only give back the Chaos gem

### Steps to reproduce the problem

1. place chaos gem and an item in the crafting bench
2. craft
3. lose everything but the chaos crystal
4. do not Profit

**Comment by SilentChaos512** [comment]
Looks like an old casualty of the 1.12 update that's gone undetected for a while. I'll get it fixed.

**Comment by krakaen** [comment]
Thanks, BTW, really like the mod, good job on it :)
