### ISSUE TITLE
silents-gems-1.9-2.0.0-alpha-5 crashes dedicated forger server 1.9 build 1809 on startup

### ISSUE THREAD

**Issue by kreezxil** [SilentChaos512/SilentGems#22]
Issue: silents-gems-1.9-2.0.0-alpha-5 crashes dedicated forger server 1.9 build 1809 on startup

crash report:
https://gist.github.com/02a811313777193ad2aa

fml server latest:
https://gist.github.com/23bf8494e19a9785f93f

**Comment by SilentChaos512** [comment]
Looks like an easy fix, should be done soon.
