### ISSUE TITLE
Improper tools crafted with Iblis installed

### ISSUE THREAD

**Issue by darkphan** [SilentChaos512/SilentGems#221]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.6-236+
Silent Lib Version: 2.2.11-92

### Expected behavior

Craft proper tools with supercharged gems.

### Actual behaviour

Completely random tools appears to be crafted, including who crafted the tool.

### Steps to reproduce the problem

1. Install versions of Silent's Gems, listed above. Install Iblis.
2. Attempt to craft supercharged tool.
3. ...
4. Profit (well not really profit :/)

**Comment by SilentChaos512** [comment]
Seems like Iblis is changing the priority of recipes somehow. So instead of the "real" recipe, you're crafting the example recipes that exist just for JEI. I should be able to work around the issue on my end, but it might be worth reporting to Iblis as well.

**Comment by SilentChaos512** [comment]
Not quite what I originally thought. It's not the example recipes, the NBT is getting wiped from the crafting output. I don't think I can fix that myself.

**Comment by darkphan** [comment]
What is interesting is if you go back a few versions of Silent Gems and SilentLib the issue does not occur.

**Comment by SilentChaos512** [comment]
I see, 2.5.6 seems fine, but the recipe code was rewritten in 2.5.7 to support CraftTweaker. That must be part of the problem.

**Comment by Foghrye4** [comment]
Currently I use `wrappedRecipe.getRecipeOutput().copy()`. I should use `wrappedRecipe.getCraftingResult(InventoryCrafting)` instead as input of `getCraftingResult()` function of wrapped recipe. This should fix issue. I will release fixed version as soon as possible.
https://github.com/Foghrye4/Iblis/blob/MC_1.12/src/main/java/iblis/crafting/PlayerSensitiveShapedRecipeWrapper.java#L39

**Comment by Foghrye4** [comment]
Fixed in Iblis mod version 0.3.22
![screenshot from 2017-10-31 19-36-34](https://user-images.githubusercontent.com/6910858/32236363-fe607cd2-be72-11e7-8425-abb183565f3d.png)

**Comment by SilentChaos512** [comment]
Looks like everything works now, thanks @Foghrye4!
