### ISSUE TITLE
1.12.2: Extra Parts mod isn't rendering anymore/Cross-post from Silents Extra Parts Github

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [SilentChaos512/SilentGems#222]
### Versions

FTB Horizons 3, 1.1.0
Minecraft Version: 1.12.2
Extra Parts Version: 1.12-1.4.0-30
Silent's Gems Version: 1.12-2.5.8-238
Silent Lib Version: 1.12-2.2.11-92

### Expected behavior

- Visual textures of Feldspar equipment and other Extra Parts tools/weapons. 

### Actual behavior

- Wielding a stick with a ghost item: In this case, a feldspar sword and machete. The polished item textures and extra parts textures of the items themselves are also missing in JEI. 

### Steps to reproduce the problem

1. Witnessing the item
2. Redownload/install the three mods in question, relaunch pack. 
3. Delete and regenerate default configs
Feldspar Sword ![screen shot 2017-11-03 at 6 19 47 pm](https://user-images.githubusercontent.com/16616656/32400903-ab765200-c0c3-11e7-931f-1ba474f6b264.png)
Feldspar Machete ![screen shot 2017-11-03 at 6 19 56 pm](https://user-images.githubusercontent.com/16616656/32400904-ab93dbc2-c0c3-11e7-9a51-ed81da527ecc.png)
 JEI ![screen shot 2017-11-03 at 6 20 11 pm](https://user-images.githubusercontent.com/16616656/32400905-aba8b088-c0c3-11e7-8726-16984cec0ac8.png)
4. Profit? NOPE
5. Downgrade to 1.12.1.3.3.29, relaunch?
6. Nope. Doesn't want to play with 1.12.2. 

Result: I downgraded to 1.12.2.5.7.236 for Silent's Gems, and the textures returned.

**Comment by SilentChaos512** [comment]
Fixed by new build of extra parts.
https://github.com/SilentChaos512/SGExtraParts/issues/7
