### ISSUE TITLE
Silent's Gems Integration with tinkers...

### ISSUE THREAD

**Issue by JunkynioyPH** [SilentChaos512/SilentGems#224]
### Versions

Minecraft Version: 1.10-1.12.2
Silent's Gems Version: X.X.X
Silent Lib Version: X.X.X

### Expected behavior

silents gems should have colors in tinkers tools

### Actual behaviour

its all white

### Steps to reproduce the problem

none. i just dont know
![where did the colors go](https://user-images.githubusercontent.com/33281422/32404198-3837debc-c186-11e7-8677-404634ff919c.PNG)

**Comment by JunkynioyPH** [comment]
i added modern warefare, and the colors comes back but the downside with modern ware fare, it casues other texture not to render... so i am back to this problem....

**Comment by SilentChaos512** [comment]
Strange that Modern Warfare fixes it, but that's what I'm seeing. Testing on Minecraft 1.12.2 with Gems 2.5.9 and Lib 2.2.11.

From your original post, you say this problem also occurs in 1.10.x and 1.11.x?

**Comment by JunkynioyPH** [comment]
I believe so, its just everytime:
 silent's gems + tinkers = silent gems stuff in tinkers NO COLOR and i tried mixing those together on 1.8.9 but theres no integration, but i have no tried it with 1.9

**Comment by JunkynioyPH** [comment]
SILENT's GEMS + Tinkers = silent gems stuff on tinkers are WHITE

**Comment by JunkynioyPH** [comment]
Its just annoys me :P and wanting it to be fixed, so some other people that gets anoyyed with it having no color will say "is the silent gems + tinkers thing fixed? (Looks up...) (tested it) YESS" sorry i am just a 13yr that just dont know what to do when stuff like this happen... :(

**Comment by SilentChaos512** [comment]
I'm at work right now, but I'll try to fix this when I get home. I can't
say how long it will take. There is basically no documentation on adding
TiC materials, so it's a lot of guesswork. Colors worked in the past, so I
guess a TiC update changed something.

**Comment by JunkynioyPH** [comment]
Sorry for interupting you then, and thank you that you understood what happend :D

**Comment by JunkynioyPH** [comment]
As long as it is fixed, everone is happy sir :D
