### ISSUE TITLE
Silent Gems Machete Crafting Issue

### ISSUE THREAD

**Issue by tfox83** [SilentChaos512/SilentGems#225]
Minecraft Version: 1.12.2
Silent's Gems v2.5.6
Silent's Gems: Extra Parts v1.4.0
Silent Lib v2.2.10

Attempting to craft a Silent's Gems Machete using any combination of gems & tool rod at a crafting table (also Cyclic Workbench) shows "Gem Machete (#5692)" Example recipe in the crafting output box. 

Clicking the crafting output box to craft and receive weapon grants the player a totally random Machete (totally random gem/part combination). instead of combination used in crafting recipe. 

Link to report: https://forum.feed-the-beast.com/threads/silents-gems-machete-crafting-recipe-bugged.260825/

**Comment by SilentChaos512** [comment]
Doesn't seem to happen in Horizons 1.1.0, but it does in 1.0.0. Not sure what causes it. If it's still an issue, updating Gems to 2.5.9 should fix it. I stopped actually registering the example recipes in that version, just passing them to JEI instead.

**Comment by tfox83** [comment]
Ok will do, thanks for the quick response!
