### ISSUE TITLE
Missing Texture Bug

### ISSUE THREAD

**Issue by tfox83** [SilentChaos512/SilentGems#226]
Minecraft Version: 1.12.2
Silent's Gems v2.5.6
Silent's Gems: Extra Parts v1.4.0
Silent Lib v2.2.10

If you decorate (repair) a silent's gems tool with the gem underneath the tool, it'll turn into the no texture texture (purple/black squares). Still works, but distracting

Report Link: https://forum.feed-the-beast.com/threads/silents-gems-glitch-out-bug.260957/

**Comment by SilentChaos512** [comment]
Gems 2.5.8 fixed this issue. 2.5.9 fixed some other decorating issues. Placing materials below the tool seems to work correctly in Horizons 1.1.0.

**Comment by tfox83** [comment]
Ok thanks, will relay this information
