### ISSUE TITLE
Can't find Silent Lib in mods folder

### ISSUE THREAD

**Issue by Snakche** [SilentChaos512/SilentGems#227]
Silent's Gems is looking for Silent Lib 1.1.0 or newer in mods folder, but it is already in the folder.  Could there be a problem with the version of Silent's Gems or Silent Lib?

Silent Lib: 1.10.2 - 2.2.6-66
Silent's Gems: 1.10.2 - 2.2.4- 101

**Comment by Snakche** [comment]
I made sure to download both from curse

**Comment by Snakche** [comment]
I've solved my problem!  I went to check the overview on curse, and found that I needed Silent's Gems 1.11.2 in order to run Minecraft version 1.10.2!

**Comment by SilentChaos512** [comment]
Good to hear. I know the versioning was a bit confusing for MC 10/11, since my mods usually supported both versions. Never doing that again.
