### ISSUE TITLE
Adding fire resistance to a chaos gem drains chaos even when not on fire

### ISSUE THREAD

**Issue by DwellerBenthos** [SilentChaos512/SilentGems#229]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.5.8
Silent Lib Version: 2.2.11

### Expected behavior

- Add a fire resistance rune to a chaos gem should cancel fire damage and use chaos only when on fire.

### Actual behaviour

- Chaos is drained at a constant rate even when not on fire.

### Steps to reproduce the problem

1. Create chaos gem, charge with chaos as normal.
2. Add fire resistance rune.
3. Note chaos draining from gem even when player is not on fire. Didn't test when player is on fire.
4. Profit

**Comment by SilentChaos512** [comment]
This might be more difficult to do than it sounds, but I'll look into it.

**Comment by DwellerBenthos** [comment]
So this is as intended? With fire resistance on the gem, chaos will drain all the time? Even when the player is not on fire? Seems strange to me, as it's a very fast drain, unless you're standing next to 6 or 8 passive pylons, the drain will empty a gem in a few minutes.

**Comment by SilentChaos512** [comment]
That is intended behavior, all the potion effect buffs drain at all times. But I do like the idea of some effects draining only as needed.

But it shouldn't be draining that quickly. At 40 per tick, it should last over 40 minutes with no capacity upgrades.

**Comment by DwellerBenthos** [comment]
OK, understood. I didn't time it, but it looked like it was draining about 1000 per second. It seemed pretty fast. I think I had one capacity upgrade on it and 3 million was half gone in about 10-15 minutes. And I think I had a recharge or two on that as well. I was mostly expecting it to work like the fire charm from another mod that only takes damage when the player is on fire.

Another player on my server told me the speed upgrade does the same thing, which is expected now, but I would think it would only be using chaos when you are moving at speed, not standing still. Not sure if that's possible or not. I guess the idea was that players would have several gems with different abilities and turn them on and off as needed, but it seems to me that players stack as many attributes on one gem as possible, and leave it active all the time. At least the players on our server seem to do that.

**Comment by SilentChaos512** [comment]
I decided to change fire resistance to only drain when the player is burning, but increased the drain by 10 times. Seems reasonable to do this for fire resistance since you never know when you could run into fire or lava. I'll leave the other effects alone for now. The idea is you should have different gems for different situations and activate them as needed.
