### ISSUE TITLE
[1.9] Enchanted versions of tools not rendering correctly

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/SilentGems#23]
Version: 2.0.0-alpha 6
SilentLib 1.0.1-6
Forge Version: 12.16.0.1811
Example: https://gyazo.com/25189a89fae1142d0030c927c5485b72
I know it's still alpha and this may be something you just haven't gotten to doing yet, just thought I'd mention it in case it wasn't known! :)

**Comment by SilentChaos512** [comment]
This is a problem I've had since 1.8. I'm tempted to just disable the effect since I can't seem to find a fix.

**Comment by TyoAtrosa** [comment]
The Enchanted effect on armor completely ruins the look of the armor, could we either get this disabled as well or have a way to remove it?

**Comment by SilentChaos512** [comment]
Enchanted glow for tools and armor will be left disabled.
