### ISSUE TITLE
Upgrade base for adding tips to tools is currently uncraftable

### ISSUE THREAD

**Issue by aridhol** [SilentChaos512/SilentGems#230]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.10-247
Silent Lib Version: 1.12-2.2.12-93

### Expected behavior

- Blank upgrade card for adding tips crafted shapelessly with two flint, one plank, one stick

### Actual behaviour

- Uncraftable

### Steps to reproduce the problem

1. Put these mods in your mods folder, in a completely fresh instance
2. Play the game, find the materials, then attempt to craft (usually takes me 30 seconds to 1 minute)
3. ...
4. Profit
5. Actually, not profit, because it won't work. Whoops. Working as intended with versions:
SilentLib-1.12-2.2.10-91 and SilentsGems-1.12-2.5.6-232

**Comment by SilentChaos512** [comment]
Thanks for reporting, I noticed this problem too. Seems like the ore
dictionary entry for flint was either removed or changed. As a temporary
fix, you could add the recipe via CraftTweaker.
