### ISSUE TITLE
Crescent Hammer causes Material Grader to lose contents

### ISSUE THREAD

**Issue by kmadstarh** [SilentChaos512/SilentGems#231]
Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 2.2.12-93
Thermal Expansion: 5.3.6.20

Expected behavior

- Thermal Expansion's Crescent Hammer rotates machines/blocks without changing contents.

Actual behaviour

- Using Crescent Hammer causes Material Grader to lose Chaos/Item Contents when rotating machine.

Steps to reproduce the problem

1. Place Items / Chaos inside Material Grader
2. Use TE Crescent Hammer to rotate Material Grader
3. Observe loss of items/chaos

**Comment by SilentChaos512** [comment]
This will be difficult to fix with the CoFH mods being closed-source. I'm not sure what kind of code they use to rotate blocks. So, this might be a low priority.

**Comment by drazisil** [comment]
@SilentChaos512 TE isn't closed source, as far as I can see. https://github.com/CoFH/ThermalExpansion

However, I didn't see the Crescent Hammer during a quick look, so not sure how helpful this is.
