### ISSUE TITLE
Suggestion: A few mining upgrades to add to current tokens

### ISSUE THREAD

**Issue by DwellerBenthos** [SilentChaos512/SilentGems#232]
It would be cool if a few mining upgrades could be added to mining tools as new tokens to craft with picks, axes, shovels, etc:

1x1x3 Tunneling: An upgrade that will mine a 1x1x3 set of blocks. The block vertically above and below the block being mined will be mined as well. Or, if pointing up or down, the blocks to the sides get mined. This would make branch mining easier by making a 3 block high tunnel very fast.

1x3x3 Tunneling: Same as above, only mines 9 blocks, the one being mined and the 8 directly around it. For making larger, 3x3 tunnels.

3x3x3 Cube mining: Same as above only 27 blocks are mined, the 1x3x3 directly facing the player and the 2x3x3 behind that set.

5x5x5 Cube mining: Same as above, only a larger area for creating rooms fast or clearing an area quickly.

Veinmining: Mine an entire vein of ore (or an entire tree with an axe, etc) by mining one block. No matter what the shape. Maybe higher levels of the upgrade allow larger and larger veins to be mined at once.

All these use durability equivalent to the amount of blocks mined. Also maybe hunger. 

When the block being mined directly is of one type of material, and is adjacent to a block of another material, only blocks of the same material get mined along with the original block. A possible upgrade to the "cube" mining abilities is to mine the cube shape no matter what materials are enclosed in it.

A keybind that can toggle on/off the abilities would be handy as well.

Just some ideas, thought I'd throw them out there.

**Comment by SilentChaos512** [comment]
I wouldn't mind adding a way to mine different shapes (you know Area Miner already does 1x3x3, right?) I wouldn't want to do it with enchantments though, that could have some odd side effects.

One question: Do you think it would be better to allow only one "shape" on a tool at a time, or should there be some way to cycle between them? If I just upgrade Area Miner, there's already a keybinding to toggle it on/off.

**Comment by DwellerBenthos** [comment]
OK, I'll have to look at area miner, wasn't aware of it, thanks.

I would think a keybind to cycle between modes on a single tool would be better, rather than having 2-3 different tools that each do a different mining operation. Kind of like how better wands (or whatever it's called) lets you cycle between line fill, vertical, horizontal, or large are fills.

hmmm... can't find anything listed under "area miner" - what is it, a tool, or add-on?

**Comment by SilentChaos512** [comment]
Area Miner is a built-in ability of super-tier pickaxes, shovels, and paxels (sometimes axes, depending on your config). Use the "Toggle Special" keybinding (default Shift+C) to toggle it on/off.

**Comment by DwellerBenthos** [comment]
Ah, OK, I'll have to look at that.
