### ISSUE TITLE
Duplicating items with holding gem and unbreaking/mending

### ISSUE THREAD

**Issue by krakaen** [SilentChaos512/SilentGems#233]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 1.4.1-34

### Expected behavior

- Storing 1 block in the holding gem should allow you to put 1 block down.

### Actual behaviour

- when putting Unbreaking on the holding gem, you can place more than the number of blocks that are in the gem.

### Steps to reproduce the problem

1. enchant an holding gem with unbreaking
2. put some blocks in there
3. start placing more blocks than you have in the gem
4. get rich from duping chaos ore

**Comment by SilentChaos512** [comment]
OK, that's funny. But easy to fix.
