### ISSUE TITLE
Diamond Upgrade didn't work on pickaxes == we can't mine obsidian/chaos ore

### ISSUE THREAD

**Issue by damaskinos** [SilentChaos512/SilentGems#235]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: Latest
Silent Lib Version: Latest

### Expected behavior

- Mine Obsidian and Chaos Ore

### Actual behaviour

- Applied to a lot of picks the Diamond Upgrade (base  + diamond) to upgrade the lvl 2 mining to 3, to mine obsidian and chaos ore. It applies the item, but didnt upgrade to lvl 3.

### Steps to reproduce the problem

1. Craft the pickaxe (with gems, obsiusly)
2. Craft the diamond base
3. Apply the base to the pickaxe.
4. Profit (Meeec error, I can't pick obsidian or chaos orb)

**Comment by SilentChaos512** [comment]
It's fixed in 2.6.0, if you're willing to try the new alpha build. It's available on CurseForge.

**Comment by SilentChaos512** [comment]
Fixed by ce6dfc2cf5e22a2f40895659d704722528ed9a73.
