### ISSUE TITLE
Crash when different tool rod materials are in crafting grid

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#238]
### Versions

Minecraft Version: 1.12.2
SilentsGems-1.12-2.5.10-247
SilentLib-1.12-2.2.12-93
Crash log: https://paste.ubuntu.com/25964281/

### Expected behavior

Not crashing when I swap out parts on the crafting table. 

### Actual behaviour

Game crashes if tool rods are not made of the same material. 

### Steps to reproduce the problem

Put 3 gems at top of crafting grid to make a pickaxe.
Place 1 wooden stick and 1 bone in crafting table to complete pattern. -> crash
-or-
Place 3 gems and 2 iron rods in crafting table for a pickaxe.
Attempt to switch one iron rod out with a different material -> crash

**Comment by SilentChaos512** [comment]
Never seen this crash before, and a related bug (#186) was fixed a long time ago. But I'll add an additional null check just to make sure nothing is slipping through.

**Comment by superfluke** [comment]
Another user noted that switching out gems didn't cause any problems and that the crash doesn't happen when swapping handle parts on swords and daggers.

**Comment by SilentChaos512** [comment]
Should be fixed in both 2.5.11 and 2.6.1, whichever version you're comfortable using. Reopen if you still have problems after updating.
