### ISSUE TITLE
NPE when decorating a pick with a diamond in bottom right

### ISSUE THREAD

**Issue by LlubNek** [SilentChaos512/SilentGems#24]
Silent's Gems crashed with a NullPointerException when I placed a diamond in the bottom right corner of the crafting grid with a gem pick in the middle.

Here's the crash report:
http://pastebin.com/9QP9XGAF

And the game output:
http://pastebin.com/CXxPpSRG

**Comment by SilentChaos512** [comment]
Thanks for reporting this, I probably wouldn't have found it on my own.
