### ISSUE TITLE
[Suggestion] SG Shears

### ISSUE THREAD

**Issue by mtjohnson47** [SilentChaos512/SilentGems#240]
I suggest adding shears using the following recipe:

□G□
T□G
□T□

G = gem, T = tool rod.  □ is an empty space in the crafting grid

Super class shears can trim an entire tree at once (max 40 leaves), or 3x3 area on non-trees.  Already chopped trees would probably use the 3x3 to make it easier on the tree detection code.

**Comment by SilentChaos512** [comment]
Sounds good. I've got some ideas on how to do this with minimal extra models/textures too.
