### ISSUE TITLE
Suggestion - Appraiser Villager 

### ISSUE THREAD

**Issue by mtjohnson47** [SilentChaos512/SilentGems#241]
The material grader is a fun part of tool building.  However, it requires Chaos, making it fairly high level.

I suggest adding a villager who trades a gem and emerald for an appraised (graded) gem.  The appraiser isn't quite as skilled as a machine though, so he can only Grade up to B on regular gems, and A on super tier gems.  A on regular or S/SS/SSS grades still require the material grader.

Perhaps 3 emeralds for super tier gems, though it's a bit pointless since if you can make super tier, you can make a grader.

**Comment by SilentChaos512** [comment]
That's an interesting idea. I've never messed around with the villager trader system, so I'm not sure how flexible it is. It might only be possible to have one gem type per trade. I'll look into it when I get some time.
