### ISSUE TITLE
Gems do not work as Tinkers' parts in SMP server.

### ISSUE THREAD

**Issue by MystFoxcoon** [SilentChaos512/SilentGems#245]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.11-250
Silent Lib Version: 1.12-2.2.12-93
Tinker's Construct Version: 1.12-2.7.4.34
Modpack and Version (if applicable): N/A

### Expected behavior

- Creating item parts in Tinker's Construct using gems and a pattern.

### Actual behaviour

- Resulting item (for example: opal tool binding) displays the correct item in the part builder, but the item cannot be removed from there to the inventory. If shift-clicked, it moves to the hotbar, but teleports back onto the table when the item is interacted with in the inventory.

### Steps to reproduce the problem

1. Host forge server with tinker's and silentsgems + extra parts
2. Place part builder and put a gem and a pattern inside
3. ...
4. Profit

Other notes:

(NOTE: This ONLY occurs on an SMP forge server, in single player it works as intended!)

When the server launches it says: 
![image](https://user-images.githubusercontent.com/33846252/33041474-a76f06da-cdfb-11e7-853e-a66af92f6996.png)

I did not disable anything in either mod. Everything should be running on default preferences.
Tried copying all the config files from my client and putting them in the server as suggested by a thread I read about a similar issue, no luck.

This problem only happens with Silent's Gems items, other materials like iron, copper, etc. work as intended.

**Comment by SilentChaos512** [comment]
Thanks for reporting. Seems to happen because I'm calling a client-side-only method when registering TiC parts. The "Are Tinkers tools disabled" bit is a guess at the cause (NoSuchMethodError), although it's different in this case.

Just for my reference, this is the stacktrace it produces: https://gist.github.com/SilentChaos512/454ad14ed70149d65acb3d26306e434d

**Comment by Airradda** [comment]
To further comment on this, if you spawn/cheat the tool part in, it will look at function normally. However, when creating a tool with the part it will appear normal, but upon pulling the item out will result in a pick with the minimal stats possible based on that part.

Discovered this when attempting to make a Supercharged Heliodor Head and ended up with a pick with a missing head texture with a mining speed of 1 and level of Stone with the head named "Pickaxe Head"
