### ISSUE TITLE
Poison Chaos Gem probably has the opposite of the desired effect

### ISSUE THREAD

**Issue by ZeekDaGeek** [SilentChaos512/SilentGems#246]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.5.11
Silent Lib Version: 2.2.12
Modpack and Version (if applicable): Modern Skyblock 2 v2.7.2

### Expected behavior

- Adding poison to a Chaos Gem would poison me.

### Actual behaviour

- The poison potion effect refreshes so quickly that you never get hurt. 

### Steps to reproduce the problem

1. Add Poison Runes to a Chaos Gem, that's it.

I was attempting to use poison + hunger to damage me and use up my food as fast as possible and instead I stumbled on a poison immunity instead, nothing can poison me to harm me, sounds good but it actually prevents what I wanted to have happen in the first place. :P

**Comment by SilentChaos512** [comment]
That's definitely not the intended effect. It must be similar to regeneration, so I need to lengthen the apply time.
