### ISSUE TITLE
Automation of crop soul gems

### ISSUE THREAD

**Issue by CharCharthemonkey** [SilentChaos512/SilentGems#248]
just wondering does silents gems work with automating tech to get the soul gems?

**Comment by SilentChaos512** [comment]
Should work if the machine uses a fake player to do the kills.

**Comment by CharCharthemonkey** [comment]
so immersive enginnering closhes wouldnt work then?

**Comment by SilentChaos512** [comment]
I'm not familiar with them.

**Comment by CharCharthemonkey** [comment]
its the garden closhes from immersive enginnering u might of seen darkphan or king using them in his test packs

**Comment by CharCharthemonkey** [comment]
![2017-09-14_16 36 00](https://user-images.githubusercontent.com/30783285/33238130-25a9f7f4-d24c-11e7-9348-4659a8e08f6e.png)
these are the closhes

**Comment by SilentChaos512** [comment]
Oh, thought you meant the soul gems that drop from mobs not the crop ones.

This took a while to find. First, it's spelled "cloche". And internally it's called "bell jar". Go figure. Glancing at the code for the tile entity, it most likely won't create soul gems. It would need to fire BlockEvent.HarvestDropsEvent. Instead it looks like the cloches use a custom handler for creating drops.

Nothing I can do without an event to catch. You could ask the Immersive Engineering author to fire some event. If they decide to add their own, I can add support for that too.

**Comment by CharCharthemonkey** [comment]
well is there anyway of automating it for crops or should i only focus on ones from mobs? just wondering cause i checked the book and it wasnt really clear on which should be more focused on in general so any info will be greatly welcome plz and ty

**Comment by SilentChaos512** [comment]
Sorry, been a crazy week and I lost track of this. I'm not sure what could be used to automate crop soul gems, I haven't tried it. Overall, the mob soul gems are "better", especially the ones dropped by hostile mobs. The flora and fauna elements have some of the weakest benefits. That was intentional, since I knew crops and passive mobs would be the easiest to farm early on.

**Comment by CharCharthemonkey** [comment]
ok so basically aim for mob soul drops then ty
