### ISSUE TITLE
Found gem duplication bug,  (trust me, MUST FIX!)

### ISSUE THREAD

**Issue by cliffordlittle** [SilentChaos512/SilentGems#249]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.10-247
Silent Lib Version: 1.12-2.2.12-93
Modpack and Version (if applicable): FTB Horizons III  1.2.1

### Expected behavior

- Because of the severity of the issue, i will not even be posting HINTS...

### Actual behaviour

- Actualy behavior is not duping items...

### Steps to reproduce the problem

1. Email me (cliffordlittle@gmail.com)  idc who gets my email.
2. You tell me how you would like the information
3. ...
4. Profit

**Comment by cliffordlittle** [comment]
ShadowNode Server Moderators notified,   hopefully they can help push a fix,.

**Comment by SilentChaos512** [comment]
I'd rather just have the information here, but if you insist you can just message me via CurseForge: https://minecraft.curseforge.com/members/SilentChaos512.

**Comment by cliffordlittle** [comment]
This dupe is affecting astral sorcery gems as well, if it matter.  Just
whatever

**Comment by SilentChaos512** [comment]
The recipe is fixed in Gems 2.5.11 and higher. Horizons III version 1.3.0 updates to 2.5.11.

**Comment by cliffordlittle** [comment]
Ok,  thanx Silent.
