### ISSUE TITLE
NullPointerException via Ticking Entity

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SilentGems#25]
I figured I would make this official. I get this crash when I have the following mods installed: Silent's Gems, Silent Lib, JEI, and WIT.

https://gist.github.com/M4thG33k/f22b5ca5940e49491c05a1bbf838b73f

**Comment by SilentChaos512** [comment]
I noticed the crash report is a bit different from the other two you sent me. Is it the same kind of crash, just occurring at random?

So strange that I haven't encountered a similar issue myself.

**Comment by M4thG33k** [comment]
Yeah, I can't reproduce it consistently. It has happened when I've broken a block, placed a block, and when the game is just sitting still (I open my inventory and switch to another desktop application). I wish I could pinpoint the issue better...
