### ISSUE TITLE
Gem bows pull back with redstone arsenal quivers, but do not fire

### ISSUE THREAD

**Issue by Hexicube** [SilentChaos512/SilentGems#250]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10-247
Silent Lib Version: 2.2.12-93
Modpack and Version (if applicable): Horizons III v1.2.1

### Expected behavior

- Either bow fires with quiver and no arrows, or bow does not pull back at all

### Actual behaviour

- Bow pulls back, but does not fire

### Steps to reproduce the problem

1. Acquire gem bow and charged redstone arsenal quiver
2. Attempt to fire without actual arrows

From what I can tell, the issue appears to be that pulling the bow back checks the nock event for success but releasing does not check the loose event.

Given that this mod directly modifies the damage of a fired arrow (and therefore can't use the loose event), it shouldn't be using the nock event to break out early with a success. Only returning a failure from that event and ignoring success should fix the issue.

Also, support for redstone arsenal quivers would be nice.

**Comment by SilentChaos512** [comment]
Confirmed still broken in 2.5.11. Thanks for the info, I'll look into it. Looks like Redstone Arsenal is closed-source though.
