### ISSUE TITLE
NBT Errors with Cyclic Workbench and Cyclic Inventory craftingtable

### ISSUE THREAD

**Issue by Quostin** [SilentChaos512/SilentGems#251]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.11-250
Silent Lib Version: 1.12-2.2.13-94
Modpack and Version (if applicable): Mech and Magic 1.12.2-RC4

### Expected behavior

- To make the actual tool with the gems selected

### Actual behaviour

- Gives a random tool than what you used.

### Steps to reproduce the problem

1. Use Cyclic Workbench or Cyclic Inventory
2. Place Gems down as what recipe shows
3. pulls the Error NBT item into inventory.
4. Select the new tool...

![image](https://user-images.githubusercontent.com/13752478/33291801-144729ec-d395-11e7-8b02-10c609e23272.png)

![image](https://user-images.githubusercontent.com/13752478/33291823-265410fa-d395-11e7-8b82-14707295f107.png)

Used aquamarine in the examples above, but it does that for all gems using the Cyclic Workbench and Cyclic Inventory.

**Comment by SilentChaos512** [comment]
This most likely needs to be fixed on Cyclic's end.

**Comment by Y0ungSandwich** [comment]
I've forwarded the Info to Lothrazar. We figured as much we just happened to also notice other crafting issues in the mod, or at least in our pack:


![unknown](https://user-images.githubusercontent.com/3539387/33294343-353d0a1e-d39e-11e7-9c20-aa3cf862a4ed.png)

Not sure if they are related but the above image happens in any crafting grid if you try to make more than one at a time.

**Comment by Lothrazar** [comment]
Cyclic author here, looking into this now.  

Is there some sort of onCrafted event I can hook into?

I think this is the offending line, but all it does is grab the output.  Unless maybe the .copy() is ignoring NBT?.  

https://github.com/PrinceOfAmber/Cyclic/blob/04b525a5ba3a52c86a2f4750f717730e178ecae5/src/main/java/com/lothrazar/cyclicmagic/component/workbench/ContainerWorkBench.java#L63

**Comment by SilentChaos512** [comment]
@PrinceOfAmber Try using IRecipe#getCraftingResult instead. My recipe needs access to the InventoryCrafting to produce the right output.

This is the recipe class: https://github.com/SilentChaos512/SilentGems/blob/1.12/common/net/silentchaos512/gems/recipe/RecipeMixedMaterialItem.java#L173

**Comment by SilentChaos512** [comment]
Confirmed fixed in latest version of Cyclic.
