### ISSUE TITLE
Server crash removing items from Holding Gem

### ISSUE THREAD

**Issue by LTibbetts** [SilentChaos512/SilentGems#252]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.10
Silent Lib Version: 2.2.12
Modpack and Version (if applicable): Horizon III (Twitch Launcher) (FTBHorizonsIII-1.12.2.zip (Beta))

### Expected 

Removing large amount of cobblestone from Holding Gems. 

### Actual behaviour

- Crashes the Server

### Steps to reproduce the problem

1. Holding Gem in hot bar
2. Turn Auto-fill off
3. Spam Crouch + Left Click
4. Server Crash

### Crash Log
[crash-2017-11-28_23.17.55-server.txt](https://github.com/SilentChaos512/SilentGems/files/1512625/crash-2017-11-28_23.17.55-server.txt)

**Comment by SilentChaos512** [comment]
I remember seeing this crash sporadically in the past. But I should be able to fix this now. I think spamming does make it more likely to happen, so I recommend extracting stacks slowly (maybe a few per second at most) until the fix is published.
