### ISSUE TITLE
Crash when using super gem axe power

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#253]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.2-251
Silent Lib Version: 2.2.13-94
Modpack and Version (if applicable): Undiscovered 1.3.0

### Expected behavior

- Not crashing when I use the lumberjack skill

### Actual behaviour

- Crashing when I use the lumberjack skill

### Steps to reproduce the problem

1. Make axe with supercharged gems
2. Turn on special ability 
3. Chop tree
4. Crash
5. Despair at the thought of all the trees that remain chopped

Full crash log: https://paste.ubuntu.com/26098119/

**Comment by SilentChaos512** [comment]
I see what I did wrong. As a temporary workaround, you could attach a tool soul to the axe, if you have the materials to craft one.
