### ISSUE TITLE
New silents gems version need Silent lib 2.2.14

### ISSUE THREAD

**Issue by crimso** [SilentChaos512/SilentGems#254]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.6.3-253
Silent Lib Version: 2.2.13-94
Modpack and Version (if applicable): Direwolf 20s with extra mods added

Hello

The new silents gems version needs Slient lib 2.2.14 what is not updated yet, not so big problem I just informing you :)

Thank you

**Comment by SilentChaos512** [comment]
Uploading now, my bad. Here's a temporary Dropbox link: [https://www.dropbox.com/s/avvi60slnrlsewi/SilentLib-1.12-2.2.14-95.jar?dl=0](https://www.dropbox.com/s/avvi60slnrlsewi/SilentLib-1.12-2.2.14-95.jar?dl=0)

**Comment by crimso** [comment]
Hello,

Super thank you :)
