### ISSUE TITLE
[1.11.x] Game crash when adding second enchantment

### ISSUE THREAD

**Issue by Tyfyter** [SilentChaos512/SilentGems#255]
### Versions

Minecraft Version: 1.11.1
Silent's Gems Version: 2.2.6-106
Silent Lib Version: 1.2.0-30
Modpack and Version (if applicable): N/A

### Expected behavior

- it just adds the second enchantment

### Actual behaviour

- it crashes

### Steps to reproduce the problem

1. make a sword
2. apply an enchantment to it with enchantment tokens
3. try to apply another enchantment to it with enchantment tokens
4. ~~Profit~~ Crash

**Comment by SilentChaos512** [comment]
Try the latest versions first. For Gems, the last version to support 1.11.x was 2.3.14. For Lib, try 2.1.6 or 2.1.5. You may need to update Minecraft to 1.11.2. It that doesn't help, you need to provide a crash report.
