### ISSUE TITLE
Remove tools gaining XP from fake players

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#256]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.3-253
Silent Lib Version: 2.2.14-95
Modpack and Version (if applicable): N/A

### Expected behavior

- Tools only gain xp when used by a player

### Actual behaviour

- Tools can be buffed to absurd levels with a little time in a mech user (fake player): https://puu.sh/yBiUD.mp4

If possible, I think removing the ability for fake players to generate tool XP would be an improvement.

**Comment by SilentChaos512** [comment]
I'll add a config for that. Thanks for reporting, I never thought to check
that.

**Comment by SilentChaos512** [comment]
New config will be disabled by default, so anyone who wants fake players to generate XP will need to enable it.

Kind of unrelated, but what are your thoughts on the current XP curve? Do you think level ups come too quickly? I don't have a lot of time to play, so it's hard for me to get a feel for it.

**Comment by superfluke** [comment]
Nice, thanks for that. I've been trying to put together a modpack, so my overall experience playing with the system has been brief. From what I've noticed levels seem to come a bit too fast for the bonuses you get. I'll try and remember to give a better review when I'm not playing in cheaty-tester mode.

**Comment by Ozzymud** [comment]
Darn, got back too late, commenting on the "Do you think level ups come too quickly?" Playing the pack @superfluke is talking about. Finally got the super tier and made a pick and wood axe... the leveling is insane... at least 4 times too fast. A super tier sword that dropped from a zombie earlier and I stood for hours at a mob farm is like level 20... the axe I just made 30 trees(TALL) ago is at level 27. (Info shows 550 blocks mined)

![image](https://user-images.githubusercontent.com/6426344/34083279-5f972c16-e322-11e7-8516-f8ffd7cc1fba.png)

**Comment by SilentChaos512** [comment]
That does seem a bit crazy. I do want the first few levels to go quickly at least, so I guess I'll make the curve steeper. I feel like wood blocks should also give less XP. Too easy to just lumberjack a jungle tree or two and get a level.

**Comment by Ozzymud** [comment]
The pick is also fast, obviously not as fast as the whole tree axe, but taking one into the nether and mining a straight 1x2 tunnel... it levels pretty darn fast.
