### ISSUE TITLE
Cannot break blocks while flying

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#257]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.3-253
Silent Lib Version: 2.2.14-95
Modpack and Version (if applicable): N/A

### Expected behavior

- Blocks tremble in fear of my mighty pick while I soar through the sky. 

### Actual behaviour

- Blocks are indestructible while flying, including insta break things such as grass and flowers. Possible due to the aerial skill. 

https://streamable.com/915wy

**Comment by SilentChaos512** [comment]
Seems I lost a pair of parentheses somehow. Could have sworn I tested this, too...
