### ISSUE TITLE
Loot chests having gems with invalid metadata

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#258]
**### Versions**
Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11
Silent Lib Version: 2.2.14
Modpack and Version (if applicable): Custom pack

**### Expected behavior**
Loot chest should have Pearl gems or whatever the highest metadata of the gems are.

**### Actual behaviour**
Seems like the loot table is assigning gems of a metadata of 48, which I'm just assuming was a typo as the highest metadata gems go up to 47.
https://imgur.com/a/0E0pj

**### Steps to reproduce the problem**
1. Use a loot generator or find desert temples/abandoned mineshafts (I'm using Cyclics creative loot generator)
2. Some of the chests will have normal gems from metadata 1-47, and one might have the invalid entry.

**Comment by SilentChaos512** [comment]
Looking at my code, it does seem to be doing 0-48 instead of 0-47. Easy fix.
