### ISSUE TITLE
Part black list does not work for tool rods

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#259]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.6.3-253
Silent Lib Version: 2.2.14-95
Modpack and Version (if applicable): N/A

### Expected behavior

- Adding silentgems:rodiron should prevent tools being crafting with iron rods

### Actual behaviour

- Only gems seem to work in the config blacklist

**Comment by superfluke** [comment]
Tool rods in the blacklist work properly now, however the items still show as usable in jei. Would it be possible to not add these blacklisted parts to the silents gems jei recipes

**Comment by SilentChaos512** [comment]
Should be doable. I'll reopen the issue until it's fixed.
