### ISSUE TITLE
SilentGem possibly causing an issue with C&B block placement

### ISSUE THREAD

**Issue by jc2xs** [SilentChaos512/SilentGems#261]
Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11-250
Silent Lib Version: 2.2.15-96
C&B Version: 14.11
Modpack and Version (if applicable): EOD Synthesis 1.2.3

### Expected behavior
Using the shift key to place a Chisel & Bits positive template and left clicking should place the block.  Removing Silent's Gems and the Lib from the pack does resolve the issue.

### Actual behaviour
It will make the sound like it is placing it but will not place the block.

### Steps to reproduce the problem
With a C&B bits make a structure/item then make a positive of it.  Then try to place the new block using shift and left click.  Disabling just Silent's lib and gems does enable this functionality work.  Verified that there are no other shift key binding conflicts.

https://github.com/End-of-Days-Modpack-Team/Synthesis/issues/7

**Comment by SilentChaos512** [comment]
Will be fixed in version 2.6.5.
