### ISSUE TITLE
Using chaos altar with multiple pylons? (UPDATE)

### ISSUE THREAD

**Issue by Anime37** [SilentChaos512/SilentGems#264]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: SilentsGems-1.12-2.6.4-254
Silent Lib Version: SilentLib-1.12-2.2.15-96
Modpack and Version (if applicable): Modern Skyblock 2

### Expected behavior

- Both pylons to charge the altar at the same time

### Actual behaviour

- Only one is doing so, while the other one is just burning fuel (it seems)

### Steps to reproduce the problem

1. Space 2 pylons next to the altar
2. Watch the particles
3. ...
4. Non-Profit

### Visual explanation

![untitled](https://user-images.githubusercontent.com/30175255/34319018-b260d5da-e7de-11e7-8d98-04feff60dfba.png)

**Comment by SilentChaos512** [comment]
Can't seem to reproduce this. Tried building a similar structure in my test world and it works. Pylons on all four sides, even tried building on top of a valid TiC smeltery.

What are the xyz coordinates of the altar in your world? It might be a quadrant-specific bug, or it could be caused by rounding errors.

**Comment by Anime37** [comment]
Not sure about the xyz coordinates. I just know that its all in the same chunk, since i'm OCD about having everything be within the chunk and stuff. I use 2 altars instead now, each getting powered by 1 burner pylon. I'll check the coordinates later, coz it takes quite a bit for this modpack to launch on my laptop.

Oh and the 2nd pylon didnt burn fuel, it was just being idle.

**Comment by SilentChaos512** [comment]
~~You should be able to see your coordinates on the F3 screen. Some mini-maps display them too. I wanted the coordinates to better test it, but if you can't find them that's fine.~~ (edit: did not read your comment very well, my bad)

Either way, I think the only fix would be to reposition your setup. For whatever reason, that one pylon cannot "see" around the block it's on top of. Make sure pylons/nodes have a direct line-of-sight and are no more than 6 blocks away in any direction.

**Comment by Anime37** [comment]
Ya, i broke and put down the altar again and both pylons energize it now, sorry for a false alarm,

**Comment by Anime37** [comment]
It seems to be an issue after all.

Whenever the altar completes an operation (for example processes a full stack of chaos shards), all the pylons around it, except one, stop giving it power. For now, the workaround (for me atleast) seems to be this:

1) proccess a stack of chaos shards
2) break the altar and put it back again
3) repeat

If i dont do this, only one pylon is active after an operation.

I'm not sure if its the reason that the altar completes the operation or if its something with the altar's internal power buffer.
