### ISSUE TITLE
MAJOR BUG (Duplication!)

### ISSUE THREAD

**Issue by Akitori** [SilentChaos512/SilentGems#266]
Version
Minecraft 1.12.2
Silent's Gems 2.6.5
Silent Lib 2.2.16

Right so I'm using silent's gems and i found out these nifty Holding Gems. I use it for stone, no big deal...

Except i checked the usage of this item. Apparently it can have mending on it? I was curious, so i threw mending on it...

![2017-12-27_19 17 07](https://user-images.githubusercontent.com/24502131/34397290-9a1e8418-eb3a-11e7-84c4-7383f8ce71fc.png)

Mending didn't work, so i paid it no mind...then i took it to a flux reconstructor, a machine from another mod that repairs items using experience... I didn't think it would work, but...

![2017-12-27_19 21 01](https://user-images.githubusercontent.com/24502131/34397353-1f1f1632-eb3b-11e7-94af-0ccfddb7d4c3.png)

I put it in for a few second and uh...

![2017-12-27_19 21 39](https://user-images.githubusercontent.com/24502131/34397361-2eb5636c-eb3b-11e7-82ef-2fff75fe3123.png)

I think this is a very critical, if not gamebreaking bug. This only happens on the holding gems, normal chaos gems and whatnot are not affected.

**Comment by SilentChaos512** [comment]
Somehow I'm not surprised. Thanks for reporting.

Good guess on the Mending by the way, that was reported and fixed not too long ago (#233).
