### ISSUE TITLE
SGProperties NBT tag being added to other mods items

### ISSUE THREAD

**Issue by superfluke** [SilentChaos512/SilentGems#267]
### Versions

Minecraft Version: 1.12.2
SilentsGems-1.12-2.6.4-254
SilentLib-1.12-2.2.15-96
Modpack and Version (if applicable): Undiscovered 1.7.1

### Expected behavior

- Silent gem nbt tags not attaching to items they are not needed on 

### Actual behaviour

- SGProperties being overly friendly with other mods items

![image](https://user-images.githubusercontent.com/20022336/34415425-a9e20ce4-ebbc-11e7-9b7a-a5510fb4e622.png)

![image](https://user-images.githubusercontent.com/20022336/34415435-b6054bc6-ebbc-11e7-882f-76a2e28d7279.png)

Not totally game breaking but it does get in the way for crafttweaker recipes picking up the extra nbt, quests that are nbt specific, or in the case of the calc circuits not stacking in drawers with the extra tag.

**Comment by SilentChaos512** [comment]
Should be fixed in version 2.6.5.
