### ISSUE TITLE
Pickaxe with enchants from Tool Soul won't let me mine redstone

### ISSUE THREAD

**Issue by jinkhya** [SilentChaos512/SilentGems#268]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.6.4-254
Silent Lib Version: S1.12-2.2.15-96
Modpack and Version (if applicable): Undiscovered

### Expected behavior

Ability to mine redstone with a Silent gem pickaxe with enchants that you get from leveling the tool with the Tool Soul.

### Actual behaviour

When I try to mine redstone, it doesn't mine it. The redstone ore disappears for a few seconds, doesn't drop anything and reappears after a while.

Here is what the console is returning when I try to mine redstone : 
https://pastebin.com/hPTpfAz2

Here is a screenshot of my pickaxe : 
https://gyazo.com/faeba1d69eb546c276af7c927bd7cfd2

Redstone is the only ore I found that I can't mine with that pickaxe and I have mined a lot of different ores with it. 

Thanks in advance

**Comment by SilentChaos512** [comment]
Already fixed, I just don't have a build ready to release yet.

**Comment by jinkhya** [comment]
ah alright thanks for fixing it then 👍
