### ISSUE TITLE
[Questions/Requests] EnderSlime and LootTables

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#269]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11
Silent Lib Version: 2.2.16
Modpack and Version (if applicable): https://minecraft.curseforge.com/projects/interaction

Hi, would it be possible for entities to have a LootTable for SoulGems so I can alter the drop chances? Also can the same be said for EnderSlime? (So far in my pack it's been sulfur and Enderslime soul gems as their drops, but would like to modify that as well).

Thanks!

**Comment by SilentChaos512** [comment]
Probably easier to just add a config for soul gem drop chances. I'll take a look at making a loot table for the ender slime.
