### ISSUE TITLE
1.8.9-Crash w/ Placemod Mod Called ArrayIndexOutOfBoundsException: 5

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/SilentGems#27]
1.3.12-109, forge 1777
Config Option for placemod: Denstiy 0.50

Placemod link: 
http://minecraft.curseforge.com/projects/placemod

Placemod crash report of this: 
https://github.com/ternsip/Placemod-1.9/issues/1#issuecomment-204932271

Crash Log:
http://pastebin.com/qS3ZKDAW

**Comment by SilentChaos512** [comment]
Should be fixed, silly typo. I also checked the other block classes, just to be sure.

**Comment by WenXin20** [comment]
Ok, thanks
