### ISSUE TITLE
Block Drops Drops Not Calculated - Silent Gems Issues

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#270]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.6
Silent Lib Version: 2.2.16
Block Drops JEI Version: 1.4.0
Just Enough Items Version: 4.8.5.138

### Expected behavior
It generate proper drops

### Actual behaviour
https://github.com/MrRiegel/BlockDrops/issues/42

PS this time I double checked my research.

**Comment by SilentChaos512** [comment]
The flower pot still drops correctly, right? It's just the JEI plugin that doesn't list correctly?

**Comment by P3rf3ctXZer0** [comment]
Correct
