### ISSUE TITLE
Flight stops working sometimes when on server.

### ISSUE THREAD

**Issue by SynexWolf** [SilentChaos512/SilentGems#272]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11-250
Silent Lib Version: 2.2.16-97
Modpack and Version (if applicable): N/A

### Expected behavior

- Not fall out of the sky.

### Actual behaviour

- Falling out of the sky when having an active gem with a flight rune.

### Steps to reproduce the problem

On a server, with low-ish tps, it causes the user to fall out of the sky even when the gem is active and has enough chaos.

**Comment by SilentChaos512** [comment]
This might be tricky to fix, but I'll see what I can do.
