### ISSUE TITLE
Tried crafting a pickaxe with gems. Shows a white pick and the tool tip gives an error about NBT data.

### ISSUE THREAD

**Issue by BrandonZV** [SilentChaos512/SilentGems#273]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.5.11-250
Silent Lib Version: 1.12-2.2.16-97
Modpack and Version (if applicable): FTB Horizons III Version 1.6.0

### Expected behavior

- I crafted stone tool rods and tried gems on top. I expect it to give me a pickaxe. It didn't.
### Actual behaviour

- I get a white icon of a pickaxe. I'll attach a picture.
![image](https://user-images.githubusercontent.com/35254141/34710927-d374130c-f4e2-11e7-9638-a4b045d3bc42.png)

I decided to craft the white pickaxe to see what would happen. When it entered my inventory, it turned into a random pickaxe. This is what I got.
![image](https://user-images.githubusercontent.com/35254141/34710956-f7617cbe-f4e2-11e7-8d7f-8aed4d04e1ec.png)

### Steps to reproduce the problem

 I am using the interface of the Simple Storage Network mod. When I use a regular crafting table, it works just fine.

**Comment by SilentChaos512** [comment]
This is an issue with the crafting interface of the other mod, nothing I can do to fix it. They are most likely calling the wrong method to get the crafting result.
