### ISSUE TITLE
[Suggestion] Dimension Blacklist

### ISSUE THREAD

**Issue by foxanthony1** [SilentChaos512/SilentGems#274]
It'd be nice to be able to blacklist ores by dimension. Right now I'm removing Chaos ore from world gen and making a crafting recipe for the essence. I'd like to be able to have players mine it in another dimension instead of crafting it.

No big deal, really. It'd just be a nice option.

Great mod. Thanks.

**Comment by SilentChaos512** [comment]
Sounds good. I was thinking of trying a few things with ore generation anyway.
