### ISSUE TITLE
Crash caused by "Rendering screen" error

### ISSUE THREAD

**Issue by faeldray** [SilentChaos512/SilentGems#278]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.7-258
Silent Lib Version: 2.2.16-97
Modpack and Version (if applicable): Custom pack, not available publicly because I'm still working on it

### Expected behavior

- Not crashing

### Actual behaviour

- Crashing

### Steps to reproduce the problem

1. Was using the CraftTweaker GUI to add in enchantment token recipes (for modded enchantments).
2. Searched for "grave" in JEI to get a material.
3. Moused over the first item listed under the Gravestone-Extended mod (the game crashes before a tooltip pops up so I couldn't tell you more about it).
4. Game crashes. Here's the crash log: [https://pastebin.com/shnAfgA1](https://pastebin.com/shnAfgA1)

**Comment by SilentChaos512** [comment]
I submitted an issue to Gravestone-Extended. It would be best if fixed on their end, but I'll add some error handling code to catch any similar problems.

**Comment by faeldray** [comment]
Thanks! I wasn't sure if which mod was the root problem so I just went with the one listed in the crash report.
