### ISSUE TITLE
Killing entities drops loot in LivingDeathEvent instead of LivingDropsEvent

### ISSUE THREAD

**Issue by ChiriVulpes** [SilentChaos512/SilentGems#280]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: all of them probably

### Expected behavior

Drops should use `LivingDropsEvent`, and therefore be removable by other mods with lower event priority.

### Actual behaviour

Drops are spawned manually in `LivingDeathEvent`.

### Example usage (why this should be fixed):

My mod, Soulus, has configs which can disable all drops from creatures not spawned by the Soulus Summoner. An in-development pack, "We Gonna Die 3", by Darkphan, uses this config so that to get creature drops you must progress through Soulus. Since the drops are spawned manually in `LivingDeathEvent`, my conditional drop removal can't touch them.

**Comment by ChiriVulpes** [comment]
The drops are still spawned manually. Drops should be added to the `List<EntityItem>` returned by `event.getDrops()`. This allows subsequent event handlers to remove them from the list.

**Comment by SilentChaos512** [comment]
Ah, right. I should have known that.

**Comment by ChiriVulpes** [comment]
Thanks for the fix! 🎉
