### ISSUE TITLE
Scepters not firing

### ISSUE THREAD

**Issue by DidaskalosDD** [SilentChaos512/SilentGems#281]
### Versions

Minecraft Version: 1.10.2
Silent's Gems Version: 2.1.10-92
Silent Lib Version: 1.1.0-23
Modpack and Version (if applicable): Breakfast Special 2.7e

### Expected behavior

- Documentation I've encountered so far leads me to believe that a scepter swung while sneaking will fire magical projectiles that home in on mobs.

### Actual behaviour

- No projectiles are produced either with or without activation ("c" key)

### Steps to reproduce the problem

1. Make scepter
2. Sneak and swing
3. ...
4. Get hit by zombie
5. If some kind of magical charge or chaos is required to power the scepter, I have not been able to find it where it should be found.

**Comment by SilentChaos512** [comment]
Are there no updates for that pack? Ask the author to update if not. Those
are some ancient versions.

**Comment by DidaskalosDD** [comment]
Maybe I should have mentioned the Forge version, which seems to be the limiting factor.  It's 12.18.3.2185.  The latest 1.10.2 versions of Gems require something newer.  Is there an easy way to tell the latest Gems compatible with this Forge?

**Comment by DidaskalosDD** [comment]
OK, I found Gems 2.3.16-183 and Lib 2.1.5-63.  They work with Forge 2185 but no projectiles.  Oh well.  The bow is still getting it done.

**Comment by SilentChaos512** [comment]
First make sure you have chaos (stand near a node or get a chaos orb.) If
that doesn't help, are you playing on a server?

**Comment by DidaskalosDD** [comment]
Got it.  It wasn't clear to me that it was chaos powered.  Thanks!
