### ISSUE TITLE
Holding gem SUPER LOUD

### ISSUE THREAD

**Issue by cortus** [SilentChaos512/SilentGems#282]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.6.8b-263
Silent Lib Version: 1.12-2.2.16-97
Modpack and Version (if applicable): N/A

At some point in a recent update, the sound when an item enters a holding gem has increased a lot.  It's not so bad when it's one block, but when it's a bunch of blocks, it is VERY loud.  I didn't see any options for it in the config file, but was wonder if there is a way to adjust this?

**Comment by SilentChaos512** [comment]
Seems I set the sound category to "Players". I might need to change that.

**Comment by SilentChaos512** [comment]
OK, category is right, I just need to reduce the volume.
