### ISSUE TITLE
Enchantment Tokens don't seem to work in crafting grid anymore

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#283]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.8
Silent Lib Version: 2.2.16
Modpack and Version (if applicable): Alpha version of  https://minecraft.curseforge.com/projects/interaction (I'm developing it)
![image](https://user-images.githubusercontent.com/26587049/35646766-3d302d04-069e-11e8-9eab-1e2933c371e4.png)
![image](https://user-images.githubusercontent.com/26587049/35646789-505de484-069e-11e8-8a12-d198e8ff502e.png)

### Expected behavior

Crafts a Satchel / Pick / Sword with Holding IV, Efficiency, Sharpness respectively.

### Actual behaviour

- Nothing shows up in the crafting grid.
![image](https://user-images.githubusercontent.com/26587049/35646717-1779b7f6-069e-11e8-9d27-006a4fd45ef4.png)

**Comment by SilentChaos512** [comment]
Seems to function correctly for me. I'd guess it's a mod interaction. Can you reproduce the issue with just Gems/Lib, CoFH mods, and CraftTweaker +your scripts (if you are using those)?
