### ISSUE TITLE
Glitch through Thut Elevator with flight

### ISSUE THREAD

**Issue by TookUrSweetRoll** [SilentChaos512/SilentGems#284]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 5.11-250
Silent Lib Version: 2.16-97
Modpack and Version (if applicable): N/A

### Expected behavior

Using the flight crystal, I glitch through Thut Elevator, but only going down.  The ride up is smooth and enjoyable.  Not sure if it's you or him, I will post to both.  You can close this without responding, just wanted to make you aware of the (potential) issue.  Great mod.

thutcore 5.13.2
thuttech 6.0.10

### Steps to reproduce the problem

1. Make elevator
2. Make crystal
3. Ride elevator
4. Fall
(sorry i'm not terribly clever)

**Comment by SilentChaos512** [comment]
Probably Thut's, since I just activate vanilla's creative flight. I'll leave this issue open until a solution is found.

Link to other issue for reference: https://github.com/Thutmose/Thut/issues/95
