### ISSUE TITLE
Ender Slime conflicting w/Rolik's Extended Minecraft (EXMC) Mod

### ISSUE THREAD

**Issue by mahilo3550** [SilentChaos512/SilentGems#285]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.6.8b-263
Silent Lib Version: 1.12-2.2.16-97
Rolik's Extended Minecraft Mod Version: 1.0.1/1.0.2
Modpack and Version (if applicable): N/A

Game will no longer start up successfully. You can only use the latest version of Silent's Gems before Ender Slime was implemented to successfully run with Rolik's Extended Minecraft Mod. Could most likely be fixed by enabling the ability to remove Ender Slime from the config file of one or both mods. Perhaps some communication with that mod's author? Link to that mod's Curse page: https://minecraft.curseforge.com/projects/roliks-extended-minecraft-mod

**Comment by SilentChaos512** [comment]
Crash report?
