### ISSUE TITLE
[1.12.2] Crash Report - Tick Loop

### ISSUE THREAD

**Issue by MokahTGS** [SilentChaos512/SilentGems#289]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.6.8b-263
Silent Lib Version: 1.12.2.2.16-97
Modpack and Version (if applicable): N/A
Forge 14.23.2.2611

### Actual behaviour

Crash Log: https://pastebin.com/d2KiV1Ls

**Comment by SilentChaos512** [comment]
Should be fixed in latest version, reopen if not.
