### ISSUE TITLE
[1.12.2] Ender Slime Spawn Rates Too High

### ISSUE THREAD

**Issue by MokahTGS** [SilentChaos512/SilentGems#292]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentsGems-1.12-2.6.9b-265 (server hotfix)
Silent Lib Version: 
Modpack and Version (if applicable): N/A

### Expected behavior
One or two slimes per chunk

### Actual behaviour
5-6 slimes per chunk and then they keep spawning.

Please add some spawn controls to the configs so that we can control the numbers of slimes that spawn.

**Comment by SilentChaos512** [comment]
Added configs and cut spawn weight and max group size in half.
