### ISSUE TITLE
[Suggestion Alternative Ore Generation Config

### ISSUE THREAD

**Issue by KAfable** [SilentChaos512/SilentGems#294]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.9
Silent Lib Version: 2.2.16
Modpack and Version (if applicable): [Interaction](https://minecraft.curseforge.com/projects/interaction) 

### Suggestion
Would it be possible to have an alternative ore generation system? In this system instead of having 48 different gem blocks (between Silents Gem + SGE), you could just have one block universal gem block like a 'Gem Ore'. From there it can just drop one of the 48 gems, or 24, etc. (and then having a secondary/tertiary gem block for Netherrack/Endstone textures).

The oregen is just a tad bit awkward when there are so many gem ores added by one single mod and this could be a nice way consolidate all of them.

**Comment by mattrix444** [comment]
i like the sound of this idea. kinda of like a roulette ore so you never know if you gonna get something you want or not :)
