### ISSUE TITLE
[Suggestion]: A way to move the Chaos Bar HUD when using Chaos Gems.

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/SilentGems#296]
Currently at the moment there's no way to move the Chaos Gem Bar whenever you have Chaos Gems enabled. Would be nice to be able to move them somewhere else if possible.

There's also that Chaos Bar that's above the Hunger Bar, could that be moved around as well?

**Comment by SonicX8000** [comment]
Just curious given the time, but has there been any word on this?

**Comment by SilentChaos512** [comment]
Will work on this today.
