### ISSUE TITLE
Gem geodes spawn in the sky in superflat worlds.

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#297]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.6.9b
Silent Lib Version: 2.2.17
Modpack and Version (if applicable): N/A

### The Issue

It seems the gem geodes are spawning in the sky in superflat worlds (and possibly other world types where the sky is in geode range?) They always have an air block in the center and one block on each side. The blocks are usually gems, sometimes hardened rock.

![2018-03-26_19 56 27](https://user-images.githubusercontent.com/5721949/37940982-39ba65dc-3131-11e8-8dd2-4665706aff04.png)

(edit) The same structures can also spawn in deep oceans.

**Comment by brisingraerowing** [comment]
Glad to see you already know about this. Cool mod, BTW. Love the enchantment tokens.

**Comment by brisingraerowing** [comment]
I just found a cluster of hardened netherrack with a couple of nether gem ores inside it in the overworld. Related to this?

**Comment by SilentChaos512** [comment]
The gem geodes are meant to spawn in the overworld. Gems in the center with a hardened rock netherrack/endstone shell.

**Comment by brisingraerowing** [comment]
Ah. OK.
