### ISSUE TITLE
[Suggestion] Table of Gem Stats

### ISSUE THREAD

**Issue by OmegaPaladin** [SilentChaos512/SilentGems#298]
Would it be possible to have a table of the different gems and their stats either in the in-game book or on the Wiki here?  It would be useful for comparison and planning which gems to use.  I had thought about manually transcribing the data, but I thought that it would be faster for you to dump the data directly.

**Comment by SilentChaos512** [comment]
Will do. For now, you could view them in this source file: [EnumGem.java](https://github.com/SilentChaos512/SilentGems/blob/1.12/common/net/silentchaos512/gems/lib/EnumGem.java). Hopefully my abbreviations make sense.

**Comment by SilentChaos512** [comment]
Updated wiki page on gems: https://github.com/SilentChaos512/SilentGems/wiki/Gems
