### ISSUE TITLE
When you log into minecraft and this happens

### ISSUE THREAD

**Issue by wamc2017** [SilentChaos512/SilentGems#299]
![untitled](https://user-images.githubusercontent.com/33242447/38168743-67a2952c-3556-11e8-874a-96536b5b687e.png)

Happy easter and aprils fools day... :D (Sorry for the spam!)

**Comment by SilentChaos512** [comment]
Huh, what version is that? Looks like the old shield textures there...

**Comment by wamc2017** [comment]
Hmm, that's a version ported to snapshot 18w11a...
