### ISSUE TITLE
Graded Gems in Recipes

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SilentGems#30]
I'm not sure if this was intended or not, but once a gem has been graded, the only recipes that show up in JEI for that gem's use is the torch bandolier (it doesn't show any of the other, many, recipes that the gem can be used in). Those other recipes _do_ work, though, so it's not the end of the world.

**Comment by SilentChaos512** [comment]
I just need to add a JEI handler and tell it to ignore the grade NBT. JEI is a bit picky about items with NBT.
