### ISSUE TITLE
Fire Resistance Chaos Gem doesn't seem to do anything

### ISSUE THREAD

**Issue by corgiblu** [SilentChaos512/SilentGems#301]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.6.9b
Silent Lib Version: 2.2.18
Modpack and Version (if applicable): Modern Skyblock 3 3.1 with some mods added (iron backpacks, dynamic surroundings, serene seasons, exotic Birds, /dank/null, I think a few more but don't remember. Have game running so can't do modlist right now.)

### Expected behavior

- Protects from fire damage, draining chaos doing so.

### Actual behaviour

- Says it's consuming when on fire but doesn't, also doesn't stop fire damage. Doesn't seem to actually consume any chaos either.

### Steps to reproduce the problem

1. Make chaos gem
2. Put fire Resistance rune and recharge rune on gem
3. light self on fire
4. Profit

**Comment by corgiblu** [comment]
Had to restart the game so I've got mod Lister installed now. https://www.modlister.com/user/beanaboston

**Comment by SilentChaos512** [comment]
Seems to function normally in unmodified MS3. It must be one of the mods you added.

**Comment by corgiblu** [comment]
Alright. Thanks for the reply. I'll try to figure out the culprit.

**Comment by corgiblu** [comment]
Well. I tried it in unmodified after unsuccessfully trying to do an A/B test, and it didn't work there either. I guess I'll just find another way to get fire resistance.
