### ISSUE TITLE
Configuration Option for Stats Tooltip

### ISSUE THREAD

**Issue by Drethic** [SilentChaos512/SilentGems#304]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 2.7.0-266
Silent Lib Version: 2.3.1-107
Modpack and Version (if applicable): Herekar's Mining Misadventures 0.19

### Expected behavior

A config option to enable/disable the stats tooltip
[Image of Stats Tooltip](https://i.imgur.com/mqBiZFl.png)

### Actual behaviour

No config options available to disable this.

### Steps to reproduce the problem

1. Load a game with Silent Gems installed

**Comment by SilentChaos512** [comment]
I plan to move this to it's own mod soon, so this will probably be removed next version.
