### ISSUE TITLE
[1.12.2] Oxygen Meter not in default location when moving the chaos bar. Intended?

### ISSUE THREAD

**Issue by SonicX8000** [SilentChaos512/SilentGems#305]
Minecraft: 1.12.2
Forge: 14.23.3.2686

Mods:
ScalingHealth-1.12-1.3.15-98
SilentLib-1.12.2-2.3.1-107
SilentsGems-1.12.2-2.7.1-268

-----
Unsure if intended, but the Oxygen Meter doesn't go back to the default position when you move the Chaos Bar to somewhere else.

Here's an image.
![](https://cdn.discordapp.com/attachments/377171551155650560/446511248851599385/silentgemchaosbarhud.PNG)

I moved the bar X: 20 & Y: 20 and the Oxygen Meter still thinks that the bar is there.

**Comment by SilentChaos512** [comment]
Not intended. Should be easy to fix.
