### ISSUE TITLE
Crash when opening inventory with silent gem armor and elytra equiped

### ISSUE THREAD

**Issue by daRussianman** [SilentChaos512/SilentGems#306]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12.2-2.7.1-268
Silent Lib Version: 1.12.2-2.3.1-107
Modpack and Version (if applicable): Darkphan's phanmilypack for his sub server

### Expected behavior

To be able to use elytra wings and silent gem armor 
### Actual behaviour

when equipping elytra wings and having a piece of silent gem armor in the inventory. then attempting to open the inventory again a crash happens
### Steps to reproduce the problem

Have elytra on the chest slot and a piece of silent gem armor of any type (helm leggings boots etc.) and 
attempting to opening the inventory it crashes before the inventory opens

Here is a log of the latest crash:
https://pastebin.com/x3Lzm9Cv

**Comment by SilentChaos512** [comment]
That's actually Equipment Tooltips crashing. I'll get it fixed.
