### ISSUE TITLE
Clientside Crash - Silent Gems JEI Issues

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#307]
### Versions

Minecraft Version: 1.12.2 - forge-1.12.2-14.23.4.2703-universal
Silent's Gems Version: SilentsGems-1.12.2-2.7.2-269
Silent Lib Version: SilentLib-1.12.2-2.3.1-107
JEI Version : jei_1.12.2-4.9.1.191
Modpack and Version (if applicable): N/A

### Expected behavior

- No Crash

### Actual behaviour

- https://gist.github.com/P3rf3ctXZer0/e3dd09bf886900f956d5d89f75ba1243

### Steps to reproduce the problem

1. Start Game
2. Have JEI and Silent Gems both Server Side
3. Browse JEI
4. Profit

**Comment by SilentChaos512** [comment]
Seems to be caused by Forge 2703, 2702 does not crash.

**Comment by P3rf3ctXZer0** [comment]
Yeah - unfortunately 703 is the current recommended. 
Build 2703:
	LexManos:
		Add potential support for models defining 'vanilla like' rotations in
		Forge's Modified Blockstate format.
	LexManos: Bump version in prep for new RB. 

This is why they changed some of the model handling definitions.
