### ISSUE TITLE
[Question] Can I blacklist the overworld?

### ISSUE THREAD

**Issue by judicius** [SilentChaos512/SilentGems#308]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.7.2b-270
Silent Lib Version: 2.3.1-107
Modpack and Version (if applicable): N/A

I'd like to cause gems to only spawn in Dimension ID 66. Does that mean I have to blacklist all other dimension IDS to force this?

ex: I black list all dimension ID's other than 66 for the Erebus.

        ##########################################################################################################
        # gems (overworld)
        #--------------------------------------------------------------------------------------------------------#
        # World generation for Gems (Overworld)
        ##########################################################################################################

        "gems (overworld)" {
           I:"Dimension Blacklist"=0,1,-1,7,20 <
             >
            I:"Max Y"=45
            I:"Min Y"=5
            D:"Vein Count"=10.0
            I:"Vein Size"=8
        }

**Comment by SilentChaos512** [comment]
Dimension IDs go between the angle brackets ("<" and ">") and one per line, no commas. I recommend using the in-game config GUI if possible (Mods menu, select the mod, click Config).

**Comment by judicius** [comment]
I appreciate it, seems like it's not world gening the way I want it to be. Nothing is world genning in dimension 66

**Comment by judicius** [comment]
Someone suggested that most oregen is based on minecraft stone and since that isn't in the dimension in question that it's probably why I'm not seeing the results I want. Is there currently a way to configure this to a mod specific stone type?

**Comment by judicius** [comment]
Closing as i opened a request here

[Feature Request] Config requests #309
