### ISSUE TITLE
[Feature Request] Config requests

### ISSUE THREAD

**Issue by judicius** [SilentChaos512/SilentGems#309]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.7.2b-270
Silent Lib Version: 2.3.1-107
Modpack and Version (if applicable): N/A

Ability in Config to blacklist dimensions for Chaos Nodes and Glow Rose
Ability to manipulate Ore Spawning to Mod specific block types such as "erebus:umberstone"
Ability to whitelist/blacklist ender slime spawns

**Comment by SilentChaos512** [comment]
That should be everything taken care of. Ender slime config already exists ("Spawn Weight" to 0 will disable them).
