### ISSUE TITLE
Toolhandeler hard crash

### ISSUE THREAD

**Issue by plenet10** [SilentChaos512/SilentGems#311]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentLib-1.12-2.2.18-100
Silent Lib Version: SilentsGems-1.12-2.6.9b-265
Modpack and Version (if applicable): Modern Skyblock 3 version 3.4(beta)

### Expected behavior

- Not crashing the client

### Actual behaviour

- Hardcrash

### Steps to reproduce the problem

I just play and when i pick up an item or do anything it hard crashes i look through the rerror message but i could not figure this one out. It has or atleast it says somthing to do with the toolhandeler

I will add the crashreport and the latest fml log.
The others were too big for pastbin
the pastbin link:
crashlog: https://pastebin.com/yVnXrmDe

[crash modern skyblock 3.zip](https://github.com/SilentChaos512/SilentGems/files/2102994/crash.modern.skyblock.3.zip)

**Comment by plenet10** [comment]
this was with forge 14.23.4.2708

**Comment by SilentChaos512** [comment]
Try updating to the latest version, 2.7.2b.

**Comment by superninjakiwi** [comment]
Same crash, updating seems to have fixed it.
