### ISSUE TITLE
Unable to craft  Summon Kitty or Puppy items

### ISSUE THREAD

**Issue by OmegaPaladin** [SilentChaos512/SilentGems#312]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12-2.6.9b-265
Silent Lib Version: 1.12-2.2.18-100
Custom Mod Pack

### Expected behavior

- Recipe will craft Summon Puppy & Summon Kitty as shown in JEI.

### Actual behaviour

- Recipe does not regardless of arrangement of items or crafting interface (2x2, 3x3, vanilla crafting table.)  Result field appears blank.
- Forestry Worktables will craft the summon kitty or puppy items, then revert them to back to their components within a few seconds.

These items can be obtained through creative mode without difficulty,

I checked carefully for an option to enable or disable crafting these in the config, without success.  I was doing this as an operator on a multiplayer server.  Yarn Balls and Rawhide Bones are craftable normally, along with just about all other Silent's Gems items.

**Comment by SilentChaos512** [comment]
I feel like I heard this somewhere before, but I believe it was on Modern Skyblock 3. What Forge version are you using?
