### ISSUE TITLE
Mining sound not stopping

### ISSUE THREAD

**Issue by NewtonAppolonius** [SilentChaos512/SilentGems#313]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentsGems-1.12.2-2.7.2b-270.jar
Silent Lib Version: SilentLib-1.12.2-2.3.2-109.jar
Modpack and Version (if applicable): FTB Horizons 3 with manually added mods

### Expected behavior
No ticking noise

### Actual behaviour
When I use my main Pickaxe I get the sound of a pickaxe striking a block.
But this sound effect then plays randomly even if I stop mining and only stops if I remove the pickaxe from my inventory.
I have narrowed it down to just this Pickaxe and not a generic problem.
I attach a zip file with a couple of screenshots which show the stats of the pick in question

![construction](https://user-images.githubusercontent.com/34678192/41984809-807f9ef6-7a29-11e8-8b4b-74d0f8c4cbd3.JPG)
![skills and properties](https://user-images.githubusercontent.com/34678192/41984810-80a93022-7a29-11e8-9799-7611661f5562.JPG)

### Steps to reproduce the problem

N/A

**Comment by SilentChaos512** [comment]
Must be the Mending soul skill, that plays the "anvil use" sound. Guess I should add a config for that.

**Comment by NewtonAppolonius** [comment]
That makes sense. Forgot to mention that when the sound occurs the Pick held in hand does a little up/down animation.
