### ISSUE TITLE
Crash using a Return Home charm

### ISSUE THREAD

**Issue by 1skandar** [SilentChaos512/SilentGems#314]
Silent's Gems Version: 271 (latest)

Modpack and Version (if applicable): Modular Mayhem Reloaded 2.0 (latest)

When teleporting home from the Nether to the Overworld Minecraft crashes with a ticking world exception. On logging back in after the crash sometimes the player ends up at a random location in the Overworld instead of on the bound Teleport Anchor.

Pastebin:
https://paste.ee/p/2zWdo

**Comment by SilentChaos512** [comment]
I think I have a fix. I'll get a new build uploaded later tonight.
