### ISSUE TITLE
Crash when rendering tools (I think)

### ISSUE THREAD

**Issue by General-Nonsense** [SilentChaos512/SilentGems#315]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11-250
Silent Lib Version: 2.2.13-94
Modpack and Version (if applicable): N/A

### Expected behavior

- game runs normally

### Actual behaviour

- crash when rendering tools

### Steps to reproduce the problem

1. I assume install the versions I have, I will include as much information as I can. I will try to fix the problem untill I get a reply. I might have the wrong versions.
[crash-2018-07-08_17.59.58-client.txt](https://github.com/SilentChaos512/SilentGems/files/2174221/crash-2018-07-08_17.59.58-client.txt)

crash report, I know a little on reading these, and I think it says the crash was from rendering a tool

i've added this to a modpack called its cozy inside, from twitch, current version.

**Comment by SilentChaos512** [comment]
Looks like a duplicate #307 and #311. You need to either update Gems to 2.7.2b or higher (and Lib to 2.3.1 or higher), or downgrade Forge.
