### ISSUE TITLE
Suggestion: add aoe mining tool

### ISSUE THREAD

**Issue by Trinsdar** [SilentChaos512/SilentGems#317]
could you add an area of effect mining tool?

**Comment by SilentChaos512** [comment]
Already exists, unless you mean a dedicated one. Super-tier pickaxes, shovels, and paxels have a toggle-able skill that allows them to mine a 3x3. The tool/armor mod splitting off from Gems in 1.13 has a hammer already designed.

**Comment by Trinsdar** [comment]
I did not know that. that's even better then a dedicated one.
though a dedicated one might be nice for before you have super-teir picks and such

**Comment by Trinsdar** [comment]
though a dedicated one might be nice for before you have super-teir picks and such
