### ISSUE TITLE
Silent gems or lib crashes server during startup.

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/SilentGems#318]
MC: 1.12.2
forge: 1,12,2 ending in 2705
SilentsGems-1.12.2-2.7.5-275
SilentLib-1.12.2-2.3.8-121

updated just today, ended up crashing server. log is here. backdating for now.

[crash-2018-07-16_02.27.58-server.txt](https://github.com/SilentChaos512/SilentGems/files/2196665/crash-2018-07-16_02.27.58-server.txt)

**Comment by SilentChaos512** [comment]
That is definitely a Lib crash. Just leave it here and I'll get it fixed today. Thanks for reporting.

**Comment by Darkmega18** [comment]
anytime.
