### ISSUE TITLE
[Suggestion/Idea] [1.7] Backport?

### ISSUE THREAD

**Issue by VexTheWanderer01** [SilentChaos512/SilentGems#322]
Minecraft Version: 1.7
Silent's Gems Version: 2.7.6
Silent Lib Version: 2.3.11
Hello, I am making a modpack, and am very interested in your mod. However, your mod does not include tanzanite in 1.7, could you please backport it? I require tanzanite for story and lore reasons. Thanks. - Ashlyn L.

**Comment by SilentChaos512** [comment]
No, I don't support anything below 1.10.2 anymore. I don't have the time to take on such a massive project on top of everything else. I suggest updating to a newer version. 1.7 is over 4 years old and few mods actively support it.

**Comment by VexTheWanderer01** [comment]
Oh, its not the latest version? I'll get to updating then...
