### ISSUE TITLE
silent gem crash on pack launch

### ISSUE THREAD

**Issue by TheNimbleNinja** [SilentChaos512/SilentGems#323]
### Versions

Minecraft Version: 1.12,2
Silent's Gems Version:1.12.2-2.7.5-275.jar
Silent Lib Version: 1.12.2-2.3.12-129.jar
Modpack and Version (if applicable): my custom modpack

### Expected behavior

- register chaos 

### Actual behaviour

-game crash

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit
https://gist.github.com/TheNimbleNinja/4ff6667fbbf7a44669d877f5b1157c59

**Comment by SilentChaos512** [comment]
Try updating Gems to version 2.7.8.
