### ISSUE TITLE
Silent Gems Crash on Load with Newest Library and Forge 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#324]
### Versions (Files are renamed because I am OCD) (All Packs are Multimc Instances)

Minecraft Version: 1.12.2
Silent's Gems Version: u-SilentsGems-1.12.2-2.7.8-281-b
Silent Lib Version: u-SilentLib-1.12.2-2.3.16-136-a
Modpack and Version (if applicable): mc-1.12.2-Pixel-8GB-rc1-r3 (This is the pack I had that was working https://www.dropbox.com/s/dx3fyn5kzqlwghl/mc-1.12.2-Pixel-4GB-rc4-r2.zip?dl=0 )

### Expected behavior

- No Crash

### Actual behaviour

- Crash

### Steps to reproduce the problem

1. Updated Forge and Silent Lib
2. Launched Private Modpack
3. Crashed.
4. Profit

### Crash Log
https://paste.dimdev.org/pidirehufo.mccrash

**Comment by SilentChaos512** [comment]
Version 2.7.9 should fix the issue.
