### ISSUE TITLE
Lag in MaterialGrader

### ISSUE THREAD

**Issue by LemADEC** [SilentChaos512/SilentGems#326]
### Versions

Minecraft Version: 1.12
Silent's Gems Version: 1.12.2-2.7.8-281
Silent Lib Version: 1.12.2-2.3.15-134
Modpack and Version (if applicable): https://www.technicpack.net/modpack/fsg-spectracraft.1282933/mods 1.0.1

### Expected behavior
- No lag

### Actual behaviour
- Lag observed when hopper is pushing gems into a full material grader

### Steps to reproduce the problem
1. Feel material grader with gems
2. Add hopper pushing different gems into the material grader
3. Profile with LagGoogles or WarmRoast

![image](https://user-images.githubusercontent.com/4776032/44118491-9d4d0312-a016-11e8-87c9-f1eb321a71a6.png)

**Comment by SilentChaos512** [comment]
Should be fixed for next version (planned to release tomorrow). The change (can be found [here](https://github.com/SilentChaos512/SilentGems/commit/cb9429d966627eeedbb08195285cd5385dc47ca5#diff-67a6fcc7014645b4b1616f2f5b265a73R241)) slipped in with another commit.
