### ISSUE TITLE
CTD after SG -292 update

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#327]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.1-292
Silent Lib Version: 3.0.0-144
SGExtraParts Version: 1.4.3-40
Modpack and Version (if applicable): Custom

### Expected behavior

- The pack loads as intended

### Actual behaviour

- CTD during start up

### Steps to reproduce the problem

1. Update all 3 mods to the versions above
2. Load the pack
3. Crash
4. Profit

Crash still occurs with ExtraParts disabled.

Excerpt from the debug log: https://pastebin.com/AnCW5LUA

**Comment by SilentChaos512** [comment]
I did not think to test the new version without Silent Gear... I'll have a fixed version uploaded soon.

**Comment by GamertechAU** [comment]
Cheers. Also I didn't know about Silent Gear, I'll look into that.

**Comment by GamertechAU** [comment]
New release loads fine. Thank you.

Tried out SilentGear and liking the look of it. Would love if your full plan for the mods was released for 1.12. Building a serious modpack and it would be an excellent fit.

**Comment by SilentChaos512** [comment]
Considering a stable (or maybe any) 1.13 Forge is still a few months out at least, it probably will. Thanks for trying it out.
