### ISSUE TITLE
Game crashes with Updating screen events crash when clicking on entry in ingame guide

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/SilentGems#328]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentsGems-1.12.2-2.8.2-293
Silent Lib Version: SilentLib-1.12.2-3.0.0-144
Modpack and Version (if applicable): https://minecraft.curseforge.com/projects/transcendence  version 0.1.5

### Expected behavior
to be able to read the changed entry in the book (it was highlighted green)

### Actual behaviour
Nope.avi
it crashed with this crash log
[crash-2018-08-22_03.25.45-client.txt](https://github.com/SilentChaos512/SilentGems/files/2307426/crash-2018-08-22_03.25.45-client.txt)

Potentially related to Foamfix? not sure. it has happened and not happened to other things lately, like crafttweaker ingame recipe maker gui.

### Steps to reproduce the problem
Atleast for me:

Open silent gems book
Search for "Legacy" then click on green highlighted topic about toolcrafting. 

What's up with the Legacy tooltip on all my tools now anyway?

**Comment by SilentChaos512** [comment]
That's crashing in my development environment as well, looks like Silent Lib's fault.

Anything marked with "Legacy Item" is going to be removed in 1.13, either because it's getting its own mod, or because it will be irrelevant (most likely due to Silent Gear).

**Comment by Darkmega18** [comment]
Ah, so, no negative repercussions for using them right now? just a friendly and slightly forboding warning that they'll be gone once gear is a thing? and cool, nice quick fix (hopefully). GG!

**Comment by SilentChaos512** [comment]
Right, nothing will be removed at any point in the 1.12.2 versions. The replacements are already in the works, but they won't fully replace anything until 1.13.

**Comment by Darkmega18** [comment]
roger-roger.
