### ISSUE TITLE
1.12.2 - CTD after update referencing SGExtraParts

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#333]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.3-295
Silent Lib Version: 3.0.3-148
SG Extra Parts Version: 1.4.4-42
Modpack and Version (if applicable): N/A

### Expected behavior

- Not crash on loading

### Actual behaviour

- CTD on loading the pack
- Error is: java.lang.NoSuchFieldError: craftingMaterial in SGExtraParts.
- After downgrading SG to 2.8.2-293 the pack loads normally

### Steps to reproduce the problem

1. Update to today's SG and Lib updates
2. Load the pack
3. Crash
4. All the Profit

[crash-2018-09-03_13.09.57-client.txt](https://github.com/SilentChaos512/SilentGems/files/2344088/crash-2018-09-03_13.09.57-client.txt)

**Comment by SilentChaos512** [comment]
Uploading Extra Parts 1.4.5, should be available soon.

**Comment by GamertechAU** [comment]
I disabled Extra Parts and updated SG again. The pack loads normally, but when loading into a world, it freezes and generates a crash file pointing to a JEI compatibility plugin

[crash-2018-09-03_13.51.58-server.txt](https://github.com/SilentChaos512/SilentGems/files/2344140/crash-2018-09-03_13.51.58-server.txt)

**Comment by SilentChaos512** [comment]
Same as #332, I accidentally referenced a Silent Gear class. A fixed version has been uploaded and is waiting for approval.

**Comment by GamertechAU** [comment]
Whoops, didn't see that one. Cheers

**Comment by GamertechAU** [comment]
Crashes fixed in latest release. Thanks
