### ISSUE TITLE
Particle Effects going missing?

### ISSUE THREAD

**Issue by 1skandar** [SilentChaos512/SilentGems#336]
Silent's Gems Version: 2.8.5-299
Silent Lib Version:3.0.5-152
Modpack and Version (if applicable): Modular Mayhem 2.3.1

I'm not exactly sure *what* is going on, but I've seen it twice now. After going around killing a bunch of mobs with my sword with Lightning enchant (that weakens and damages mobs over time) particle effects just seem to die. No more lightning effect around the mob, magic attacks from my scepter no longer show the magical bolt(s) and even vanilla effects like the smoke cloud from explosions (like a creeper exploding) just disappear. No errors show up in the log file, either. I can't be certain this is a Silent's Gems thing, but this is the first time (well, first and second) seeing this in dozens of hours playing (and developing) this pack and the only recent change is the sword with Lightning so I'm reporting it here first as my first candidate.

**Comment by SilentChaos512** [comment]
If I had to guess, it sounds like something is changing the particle settings if even vanilla effects disappear. I can't think of anything I'm doing that could cause that, but I'll keep an eye out for it.

**Comment by 1skandar** [comment]
I'm watching it as well. This one is going to be a headache as it doesn't show in the log and I've yet to be able to trigger this reliably. And Google has been spectacularly unhelpful. The only other mention of a bug like this was in 1.10 and that...isn't really making things any better. If I had to guess this bug is embedded in vanilla Minecraft itself, and requires some sort of odd edge case to trip. Because that is the kind of bug I'm good at finding. It's a talent I wish I didn't have.

**Comment by 1skandar** [comment]
Ok, further testing and it looks like teleporting triggers it. Not every time, but if you teleport enough you'll trigger this bug eventually, especially teleports across dimensions. I'm thinking this is a bug in vanilla itself, made more noticeable thanks to your Return Home Charm.

**Comment by darchitectlp** [comment]
Ok, I nearly went insane trying to figure this out. I'm in 1.10, though, so this may not apply, but @1skandar, do you have a bunch of java arguments set? I'm playing Sprout and these are the args I was using (found on some Reddit thread):

```
-XX:+UseG1GC -Xmx8G -Xms8G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```
I deleted everything except the `-Xmx8G -Xms8G` et voilà! No more disappearing particles! Hopefully this helps.

P.S. Loved me some Crash Landing. You working on anything for 1.12? I feel like none of the "inspired by" modpacks others made came close to touching yours.
