### ISSUE TITLE
SilentGems translation bug and skipping chaos nodes after update.

### ISSUE THREAD

**Issue by AngelSimmer64** [SilentChaos512/SilentGems#337]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 1.12.2-2.8.2-293
Silent Lib Version: SilentLib-1.12.2-3.0.1-145
Modpack and Version (if applicable): Starfall 1.12.2 

### Expected behavior

- SilentGems after update carries on as normal before update, it doesn't create console spam or lag.

### Actual behaviour

- Since I updated the server and modpack the console has been filled with errors, issues and general notes about SilentGems changing versions. I get very regularly translations it's trying to do and constantly skipping chaos nodes etc. Chaos nodes appear to be causing lag server lag too. 

One of the many logs here: https://pastebin.com/gnuETqgx

### Steps to reproduce the problem

1. Go from the SilentGems version 1.12.2-2.7.4-272 to 1.12.2-2.8.2-293 using the same world file.
2. Watch console
3. Profile lag
4. You should have the same issue?

**Comment by SilentChaos512** [comment]
I will disable the server translation warnings, they aren't particularly useful for Gems. As for the chaos nodes, try breaking and replacing them in creative mode (make a backup first, just in case). Don't use the node mover.
