### ISSUE TITLE
Return Home hotkey disabled

### ISSUE THREAD

**Issue by 1skandar** [SilentChaos512/SilentGems#338]
Silent's Gems Version: 2.8.5-299
Silent Lib Version:3.0.5-152
Modpack and Version (if applicable): Modular Mayhem 2.3.1

For whatever reason I cannot get the Return Home Charm to function via hotkey. I've made sure to clear out any conflicting keybings, even tried moving the keybind to several different keys and nothing. The charm will still work if you hold it in your hand an d right click, it just makes using it as a bauble a bit of a pain.

**Comment by SilentChaos512** [comment]
Issue fixed by Silent Lib 3.0.6.
