### ISSUE TITLE
Crafting SG armour in RS grid takes more materials than intended

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#339]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.5-299
Silent Lib Version: 3.0.6-154
Modpack and Version (if applicable): Chaotic Progression 1.0.7
Refined Storage version: 1.6.5

### Expected behavior

- Crafting SG armour with lattice and gems in an RS crafting grid to take 1 craft worth of gems.

### Actual behaviour

- Crafting SG armour pieces in an RS crafting grid takes 2 crafts worth of gems. Crafting in other crafting stations only uses 1, and only seems to affect SG items.

### Steps to reproduce the problem

1. Craft an SG armour piece out of lattice
2. Craft a complete armour piece in an RS crafting grid with multiple units of gems around it
3. The craft takes more gems than intended

Clip of the bug: https://clips.twitch.tv/BlitheMotionlessAniseAllenHuhu

**Comment by GamertechAU** [comment]
Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.13-312
Silent Lib Version: 3.0.10-161
Modpack and Version (if applicable): Chaotic Progression 1.2.0
Refined Storage version: 1.6.12

Due to Stalebot's prodding, this is still a thing in the above updated mod versions.

**Comment by SilentChaos512** [comment]
Tested and confirmed with latest versions of everything. No idea why this is happening, but I noticed a couple things:
- Extra ingredients are only consumed if they are in the crafting grid. No extra items pulled from storage.
- Emptied stacks are removed from the grid. Normal recipes will refill the grid so you can keep crafting.
I'm guessing those two things are related. I'll take a poke at my recipe handlers, see what I'm doing wrong.

**Comment by GamertechAU** [comment]
Confirmed fixed in 2.8.14-313. Cheers Silent
