### ISSUE TITLE
[Suggestion] Enchantment token support for Cyclic

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#340]
### Versions
Minecraft Version: 1.12.2

Cyclic adds some useful enchants such as magnet. JEI shows the tokens, but they currently aren't assigned recipes.

If possible, could they be added please Silent?

**Comment by GamertechAU** [comment]
Updated to 2.8.7, getting a crash referencing the Cyclic excavation enchant

https://pastebin.com/PR0qbxX9

I've disabled that enchant as I'm using Ore Excavator, so looks like it needs to detect and ignore disabled enchants.

**Comment by SilentChaos512** [comment]
That's strange, I wouldn't expect Cyclic to unregister objects like that. Or is it another mod you are using to remove the enchantment? Either way, I'll find some way to account for it.

**Comment by GamertechAU** [comment]
Disabled directly from the cyclicmagic config. There are entries to disable each separate enchantment which completely removes them from the game.

**Comment by GamertechAU** [comment]
Re-enabled the enchant and the pack loads fine, with all the Cyclic tokens showing recipes, so the updates themselves seem to be working fine Silent.

**Comment by GamertechAU** [comment]
Forgot to update this. Enchants are working as intended now. Thanks
