### ISSUE TITLE
[Enhancement] Server startup improvements

### ISSUE THREAD

**Issue by sscards55** [SilentChaos512/SilentGems#341]
So when Forge starts up a server, it remaps all the block/item IDs in that world. For some reason that means it goes through all of the tooltips. You have a tooltip event subscriber that queries the oreDictionary entries of that item. This unfortunately means CPU cycles used for an ultimately pointless task and memory allotment for objects that exist only to be garbage collected.

### Steps to improve

          ‪‭Only useful for loading multiple worlds per Minecraft start.
                                                          ↓
1. Create event handlers for server started and server stopping/stopped events.
2. Register/unregister tooltip event handler reducing world/server loading times.
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
The problem with that is it breaks tooltip searching in JEI. Not sure how many people use that, but it's not a feature I would want to give up. I did find a small optimization for the method is question, shaves about 1.8 seconds off launch time on my system.

**Comment by sscards55** [comment]
I realized my original suggestion was probably over engineered. What about setting a flag during Server about to start and unsetting during server started and checking for that. Unless this also affects JEI.
