### ISSUE TITLE
Error with Silent Gems + Selims Enchants

### ISSUE THREAD

**Issue by Darkmega18** [SilentChaos512/SilentGems#343]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: SilentsGems-1.12.2-2.8.5-299
Silent Lib Version: SilentLib-1.12.2-3.0.6-154
Modpack and Version (if applicable): Transcendence, 0.1.8

Not sure on what causes the issue but one of my players on my discord sent me this pastebin:
https://pastebin.com/Kh6LJZB0

I'm not sure if it's an outright crash or just something playing up in the background and spitting errors to console cause it doesn't have the usual crash report bits on the start and end but the player said it was related to Selim's enchantments and silent gems. 

Looks like something to do with the enchantment tokens. So I brought it to you since they're yours. 

edit: Turns out this is from a crash on startup in a server environment. it works fine in singleplayer apparently. the player in question had to take out selims for the mean time.

**Comment by SilentChaos512** [comment]
Selim's Enchants will need to fix that. I imagine it's because they use `ChatFormatting` instead of `TextFormatting`.

**Comment by Darkmega18** [comment]
Alrighty, I'll pass it on.
