### ISSUE TITLE
[Crash] Tool parts with missing items

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/SilentGems#344]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.6-303
Silent Lib Version: 3.0.6-154
Modpack and Version (if applicable): N/A

[Crash report](https://paste.dimdev.org/ufanuseyad.mccrash)

**Comment by SilentChaos512** [comment]
That's a strange one. I see a way to prevent the crash at least, and I'll add some extra log information to track down the specific mod at fault (if you want to do that). My guess is this is a mod compatibility issue in Extra Parts.

Also edited your post to make the crash report link easier to find, just FYI.

**Comment by SilentChaos512** [comment]
Issue seems related to Expanded Arcanum. It uses the same mod ID Ebon Arts did... "ea" (not a very good ID to begin with). I am disabling Ebon Arts support since it has not updated past 1.11.
