### ISSUE TITLE
Broken OreDic entries

### ISSUE THREAD

**Issue by Shattered2909** [SilentChaos512/SilentGems#347]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.8-305
Silent Lib Version: 3.0.8-158
Modpack and Version (if applicable): Darkest Journey 2 (my own, dev instance)

The oredicts of Green Sapphires and Beryls are mixed up.

**Comment by SilentChaos512** [comment]
Beryl was renamed to green sapphire. I decided to keep both entries for now, for compatibility. Is this an issue for your mod pack?

**Comment by P3rf3ctXZer0** [comment]
Gems are not working anymore!! 
![does not work](https://user-images.githubusercontent.com/10351221/51700842-aea42980-1fd5-11e9-8cc1-656742e7466f.jpg)
