### ISSUE TITLE
[1.9]-2.0.7-alpha-21 server crash

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/SilentGems#35]
When attempting to boot up a server on the newest release of Silent Gems for 1.9, I get the following [Crash Report](https://gist.github.com/dirtyfargo/66cd97b13969bcde18bb2e6d8bd87d7a)
Forge Version: 12.16.0.1865
Silentlib: 1.0.5-11

**Comment by SilentChaos512** [comment]
Sorry about that. I need to remember to launch a server every so often... Looks like an easy fix though.

**Comment by dirtyfargo** [comment]
No worries and thanks again for the quick reply =)
