### ISSUE TITLE
Torch Bandolier recipe missing

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#350]
### Versions

Minecraft Version: 1.12.2
Silent's Gems Version: 2.8.10-308
Silent Lib Version: 3.0.9-159
Modpack and Version (if applicable): Chaotic Progression 1.0.12

### Expected behavior

- Torch Bandolier to be craftable

### Actual behaviour

-  Not sure which version it happened, but now only the info page shows in JEI, no recipe and can't find a recipe file in the jar for it.

**Comment by KelleyEngineering** [comment]
Since the Torch Bandolier is a Legacy Item and is gonna be removed anyway, it may make more sense to download the Standalone mod instead to get ahead of the curve. It's also by SilentChaos.

**Comment by SilentChaos512** [comment]
Recipe must have been lost in the JSON conversion last month. I'll get it fixed this week.
