### ISSUE TITLE
[Question] Mods dropping silent gems weapons now?

### ISSUE THREAD

**Issue by Routhinator** [SilentChaos512/SilentGems#353]
Updated to the latest release to fix the crash with #352 and now found that any mobs are dropping Silent Gems katana, swords and machetes. Is this an intentional change and is there a way to disable it?

The concern here is that in order to deal with all the junk drops a trash can with NBT and META matching disabled is required in a storage system, and this will also have the negative effect of trashing player made weapons if they are accidentally added.

**Comment by KelleyEngineering** [comment]
This is intentional. You can disable it in the configs or limit how often these weapons drop

**Comment by KelleyEngineering** [comment]
![sgems equipment](https://user-images.githubusercontent.com/27598014/52356787-ddbd9080-2a02-11e9-962d-850cc6ca18ae.png)

**Comment by Routhinator** [comment]
Cheers, thank you.
