### ISSUE TITLE
Error loading mods when starting up game.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#354]
### Versions

Minecraft Version: 1.13.2
Silent's Gems Version: 3.0.0+5
Silent Lib Version: 4.0.0+2
Modpack and Version (if applicable): N/A
Forge Version: 25.0.44

### Expected behavior

-  Loading up as normal.

### Actual behaviour

- Error Loading mods: Silent's Gems 3

### Steps to reproduce the problem

1. Start the game
2. Wait
3. Popup screen (error)
4. Close game.

-------
This was on an instance with only SilentGems & SilentLib.

Logs:
[Hastebin](https://hastebin.com/udidohideh)

**Comment by SilentChaos512** [comment]
Looks like something went wrong during the build process, looking into it.

**Comment by SilentChaos512** [comment]
Should be fixed in 3.0.1

**Comment by Gbergz** [comment]
Doesn't appear to be fixed in the newest version.

**Comment by SilentChaos512** [comment]
OK, uploading the file manually this time. Should be approved in 20 minutes or so.

**Comment by Gbergz** [comment]
Game now loads, thanks for the fixes! :) 👍
