### ISSUE TITLE
[Feature Request] Support Forge Multipart

### ISSUE THREAD

**Issue by Routhinator** [SilentChaos512/SilentGems#355]
This is just a feature request.

I love the Onyx brick and want to use it extensively, but would like to be able to make stairs and edging with it. Was sad to see none of the blocks seem to work with Forge Multipart. Any possibility of adding this feature?

**Comment by Ommina** [comment]
If you do not wish to wait for native support, you can add such aesthetic blocks yourself via the microblocks.cfg file -- if you are on a server, do note that the same changes will need to be made there.

**Comment by Routhinator** [comment]
So trying to get this working, I've added this to client and server, but doesn't seem to work:

```
#Configuration file for adding microblock materials for aesthetic blocks added by mods
#Each line needs to be of the form <name>:<meta>
#<name> is the registry key of the block/item enclosed in quotes. NEI can help you find these
#<meta> may be ommitted, in which case it defaults to 0, otherwise it can be a number, a comma separated list of numbers, or a dash separated range
#Ex. "dirt" "minecraft:planks":3 "iron_ore":1,2,3,5 "ThermalFoundation:Storage":0-15
"silentgems:gemblock":0-15
"silentgems:gemblocklight":0-15
"silentgems:gemblockdark":0-15
"silentgems:gemblocksuper":0-15
"silentgems:gemblocksuperlight":0-15
"silentgems:gemblocksuperdark":0-15
"silentgems:gembbrickcoated":0-15
"silentgems:gembbrickcoatedlight":0-15
"silentgems:gembbrickcoateddark":0-15
"silentgems:gembbrickspeckled":0-15
"silentgems:gembbrickspeckledlight":0-15
"silentgems:gembbrickspeckleddark":0-15
"silentgems:gemglass":0-15
"silentgems:gemglasslight":0-15
"silentgems:gemglassdark":0-15
"silentgems:gemlamp":0-15
"silentgems:gemlamplight":0-15
"silentgems:gemlampdark":0-15
"silentgems:miscblock":0-15
"silentgems:fluffyblock":0-15

```

**Comment by Routhinator** [comment]
Actually this works. I was a dumbass and missed that I accidentally put two b's for bricks.

**Comment by Ommina** [comment]
Ha.  For what it is worth, I went over that config repeatedly, trying to figure out why it wasn't working for you.  I checked the punctuation, the modid, the quotes, the lot.  Not once did I notice the extra 'b' in brick.
