### ISSUE TITLE
[1.14.x] Missing Things

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#357]
## Missing things the mod needs and other issues
- [x] New chaos system (chaos pollution/corruption, what should I call it?)
- [x] Chaos Gems + Runes
- [x] Chaos Orbs
- [ ] Drawing Compass
- [x] Ender slime spawns (and fix the loot table!)
- [x] Fluffy puffs - some recipes are missing (feathers, string, wool)
- [x] Fluffy puff seeds are unobtainable
- [x] Gear souls (formerly tool souls)
- [ ] Holding Gem (maybe rethink this a bit, lower priority)
- [x] Pedestals
    - [x] Chaos gem support (apply effects to nearby entities)
    - [x] Chaos orb support (absorb chaos produced by blocks)
- [x] Return Home Charms
- [x] Secret donut effects
- [x] Soul Gems
    - [x] Drop rate configs (median and deviation)
- [x] Teleporters
    - [ ] Need to update the textures...
- [x] Token Enchanter (Enchantment Token maker)
    - [ ] Textures needed
- [ ] Transmutation Altar (formerly Chaos Altar)
    - Mostly coded, but needs some tweaking. Handling of catalysts should be reviewed.

## No longer needed
- Chaos Pylons (replaced by pedestals with chaos orbs)

All the chaos items are dependent on the chaos system, but many could be made to work without it for the time being. Orbs ~and pylons~ could be used to "absorb" generated chaos. Orbs placed on pedestals (a new block type) will absorb chaos produced by nearby blocks.

Need to decide on an implementation for soul gems. Could probably just grab the entire entity list and work with that. Or might be better to manually create the variants.

**Comment by VampireSultana** [comment]
[crash-2019-03-10_04.50.27-client.txt](https://github.com/SilentChaos512/SilentGems/files/2955035/crash-2019-03-10_04.50.27-client.txt)
[crash-2019-03-10_20.44.31-client.txt](https://github.com/SilentChaos512/SilentGems/files/2955036/crash-2019-03-10_20.44.31-client.txt)

The top one is a crash report that happened when I tried reaching page 28 and 29, and the second is a crash report from when I tried making a sword with the ornate rods. Once again as I've said before,  I’m running the game on 1.13.2-forge-25.0.6. Thank you for your time, and thank you for informing me about the issue tracker, I didn't know there was one!
