### ISSUE TITLE
2 Issues with Rendering and Crashing

### ISSUE THREAD

**Issue by VampireSultana** [SilentChaos512/SilentGems#359]
I didn't know where to post this issue since it involves both Silent's gems and Silent Gear.

### Versions

- **Silent's Gems**: 3.0.5
- **Silent Lib**: 4.0.4
- **Forge**: 1.13.2-forge-25.0.6
- **Silent Gear**: 1.0.4

### Actual behaviour
-With both Silent Gems and Silent Gear installed, along with the JEI mod, I have 29 pages of items on the right of the screen. Yet every time I try to access the last 2 pages, 28 and 29, the game crashes. 
-I can create a sword with the new gems, but it states that a rod is missing. Once I place a rod in the crafting table along with the blueprint and gems, the game crashes.
Both of these issues are 'Item Rendering' crashes I believe. Not sure if this is an issue with the Mods, or my computer. 

### Links/Images

When I tried to pages 28 and 29:
[crash-2019-03-10_04.50.27-client.txt](https://github.com/SilentChaos512/SilentGems/files/2955091/crash-2019-03-10_04.50.27-client.txt)

When I tried to craft a sword with the ornate rod:
[crash-2019-03-10_20.44.31-client.txt](https://github.com/SilentChaos512/SilentGems/files/2955092/crash-2019-03-10_20.44.31-client.txt)

### Steps to reproduce the problem

1. Install SilentLib, Silent's Gems, Silent Gear, and JEI mods.

1. Try to craft a sword with an ornate rod (Causes a Crash)
2. Attempt to go to pages 28 and 29, within the JEI mod on the right side of the screen. (Causes a Crash)

**Comment by SilentChaos512** [comment]
Thanks for taking the time to report this. That definitely looks like the crash I found and fixed yesterday. An update (Gems 3.0.6) should be released sometime soon.

**Comment by VampireSultana** [comment]
Thank you so much! The game works like a charm now!
