### ISSUE TITLE
[1.9] Return Home Charm obstruction check failure

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#36]
In some cases, it seems the Return Home Charm will falsely claim the destination is obstructed, even when it is not. This occurs when teleportation is cross-dimension, unknown if this occurs in the same dimension. This is an issue that has cropped up in previous versions, and changes to the safety check code were needed for 1.9.
Reported by dhalek on the CurseForge page for Silent's Gems.

**Comment by dhalek** [comment]
I observed this in the nether. With a view distance of 12 chunks, I could teleport 189 blocks but I got the obstruction message when being about 192 blocks away. This is 12*16 so I suspect it occurs when the destination chunk gets unloaded. In the overworld I did not have this problem.
Hope that helps finding the issue.

**Comment by SilentChaos512** [comment]
Looks like the main problem was the code checking the dimension the player was in, instead of the target dimension.
