### ISSUE TITLE
Material Grader is hit-or-miss with pipe / duct functionality

### ISSUE THREAD

**Issue by RonRicoSuave** [SilentChaos512/SilentGems#362]
Note:  This also seems to affect the part analyzer from silent gear, which I'm guessing shares similar code.  

### Versions

- **Silent's Gems**: 2.8.16
- **Silent Lib**: 3.0.10
- **Silent Gear**: 0.5.2
- **Forge**: 14.23.5.2815
- **Modpack** (if applicable): Custom

### Expected behavior
As per manual, items can be extracted from bottom face of grader with pipes and inserted on other sides.

- 

### Actual behaviour
Pipes tested / Functionality
- Thermal Foundation:  Signalum plated itemduct with resonant servo ignoring redstone and empty blacklist.  Pipe connects, but nothing extracted. 
- EnderIO:  Pipe will not connect. 
- Integrated Dynamics logic pipes:  All combinations of interfaces / export / import on grader and chest failed to extract.
- Mekanism Logistics Pipes:  Works as expected, can insert to sides and extract from bottom.  Also extracts input item from any side but bottom.
- AE2 with unfiltered import bus to storage system with multiple empty 16k drives:  Fails to extract. 

This is mainly an issue because not all packs have Mekanism, and the pipes don't have a reasonable facade option AFAIK which isn't great when you have to run them through the floor because of the sided output.  I'm not sure what trickery mekanism does (it always seems to work when every other option fails) but enderio failing was kind of surprising.  

- 

- 

### Steps to reproduce the problem

1.  Attach any of the above pipes to grader.
2. Watch as things do or do not happen. 

### Suggestion
Allow extracting products from all sides but top and inserting to same, but keep the top or bottom able to pull the current stack waiting to be analyzed if that functionality is needed since it tends to be the rarer use case...   

### Last Comment
Your April 1st addition made me LOL.

**Comment by Gamertech** [comment]
To add to this, Mekanica (new Mekanism fork) updated their pipe capability handling to the most recent standards in 1.2.0, and no longer connects to the SG Chaos Altar and Grader. Still connects to every other mod I'm using in the pack.

Likely either of these commits:
https://github.com/mekanica/mekanica/commit/66d0bca37c53caee9316fd58a484283bb56861b5
https://github.com/mekanica/mekanica/commit/cf8ef8ad5f8b18fca3035b3d2f9cef13f56defd7

**Comment by Gamertech** [comment]
Hey Silent, updated to Silent Gems 2.8.17+319, but the grader and altar still wont connect to Mekanism logistics pipes as of Mek 9.7.2.373

**Comment by SilentChaos512** [comment]
Both blocks should work with Mekanism pipes in 2.8.19

**Comment by Gamertech** [comment]
Can confirm working after the update. Cheers Silent.
