### ISSUE TITLE
1.13 silent gmes asking for silentlib 4.0.7 or above even though its installed

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/SilentGems#363]
### Versions

- **Silent's Gems**: 3.0.11+26
- **Silent Lib**: 4.0.7+20
- **Forge**: forge-25.0.141
- **Modpack** (if applicable): Custom

### Expected behavior
Launch pack and it run without problems

### Actual behaviour
Launched game and mods asking for lib version that is actually there

### Links/Images

http://puu.sh/DeSX4/092cce68b1.png what comes up when launched

latest log: 
[latest.txt](https://github.com/SilentChaos512/SilentGems/files/3078387/latest.txt)

### Steps to reproduce the problem

1.load up instance with the listed versions
2.get screen as shown in links
3.close game and be sad

**Comment by SilentChaos512** [comment]
Are you sure? Not seeing it in the list of mods in your log file. Make sure the file is in the right spot. If it is, try downloading again.

**Comment by SDUBZ** [comment]
The new lib is also crashing fun ores too thought i would let you know

**Comment by SDUBZ** [comment]
okay i deleted old files and fresh ones were used , what is going on with the twitch launcher then

**Comment by SDUBZ** [comment]
but its crashing on world load 
[crash-2019-04-15_14.34.19-server.txt](https://github.com/SilentChaos512/SilentGems/files/3078458/crash-2019-04-15_14.34.19-server.txt)

**Comment by SilentChaos512** [comment]
That one is caused by a mod with broken capabilities. No easy way to tell which because it crashes in random places, you'll just have to try disabling mods.

**Comment by SDUBZ** [comment]
thats was my plan to go through and see what one is caausing it because i noticed there is like 5 mods triggering same even, do you know if they have introduced a loading phase in forge yet to handle this better

**Comment by SDUBZ** [comment]
okay culprit seems to be iron chest mod thoguht i would let you know so you can tell other users if they have that mod installed too :)

**Comment by SilentChaos512** [comment]
That's odd, I'm using iron chests without any issues.

**Comment by SDUBZ** [comment]
okay forge Forge: forge-25.0.146 fixes capability issues but now silent gems and gears is crashing from a tags issue will make new issue once i work more and thank you for the work you have done
