### ISSUE TITLE
1.13 java.lang.NoSuchMethodError: net.silentchaos512.gear.crafting.ingredient

### ISSUE THREAD

**Issue by SDUBZ** [SilentChaos512/SilentGems#364]
Versions
Silent's Gems: 3.0.11+26
Silent Lib: 4.0.7+20
Forge: forge-25.0.141
Modpack (if applicable): Custom
Expected behavior
Launch pack and it run without problems

Actual behaviour
Load into a fresh world and get crash on world load 
Tobe noted it seems to be a jei conflict of some sort

latest log:
[latest.txt](https://github.com/SilentChaos512/SilentGems/files/3078488/latest.txt)

Crash report:
[crash-2019-04-15_14.59.58-server.txt](https://github.com/SilentChaos512/SilentGems/files/3078490/crash-2019-04-15_14.59.58-server.txt)

Steps to reproduce the problem
1.load up instance with the listed versions
2.get crash on wolrd load
3.close game and be sad

### Steps to reproduce the problem

1.Load up instance 
2.start a fresh world 
3.game crashes

**Comment by SilentChaos512** [comment]
I forgot I needed to make a small change to Silent Gear for Gems' JEI plugin. I'll get that uploaded ASAP.
