### ISSUE TITLE
[1.13.2] Client Crash - java.lang.NoClassDefFoundError: net/silentchaos512/gear/util/GearHelper

### ISSUE THREAD

**Issue by Siriuo** [SilentChaos512/SilentGems#365]
### Versions
- **Silent's Gems**: 1.13.2-3.0.11+26
- **Silent Lib**: 1.13.2-4.0.7+20
- **Forge**: 1.13.2 - 25.0.141
- **Modpack** (if applicable): Custom

### Expected behavior
Client to launch

### Actual behaviour
Client crashes with the below crash log.

### Links/Images
https://pastebin.com/DqPrMz1N

### Steps to reproduce the problem
Launch the client

**Comment by SilentChaos512** [comment]
Looks like I forgot to check if Silent Gear is loaded there. I'll get this fixed later today.

**Comment by Siriuo** [comment]
Adding Silent Gear fixed the issue for me. Just had another issue when opening the inventory. Not sure if this is related to Gear. See below crash log. Silent Gear version: 1.13.2-1.0.7+17

https://pastebin.com/LLid2Q2P
