### ISSUE TITLE
Tipped upgrades usable as fuel

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SilentGems#37]
Don't even ask me how I found this one, but Iron-Tipped upgrades seem to be usable as fuel (and have the same burn time as a block of coal. (The emerald-tipped upgrade also seems to be usable as fuel with a burn of roughly 256 items-worth). The other tip upgrades do not burn. Just thought you should know...

**Comment by M4thG33k** [comment]
On further inspection, there seem to be a lot of non-fuel things giving high burn times (including glass panes, etc with burn times of 6400 and 64000 which I believe correspond to the burn time of chaos coal and chaos coal blocks). I'm wondering if it has something to do with how you've registered the burn time for the chaos coal (I notice that you only check the item damage and not the item itself, which may(?) cause the issue.) I had a similar problem with my charcoal blocks, but I completely disabled all of my mods and still had this issue.

**Comment by SilentChaos512** [comment]
You're right, checking that the stack is the right item when getting the burn time seems to be necessary. Easy enough fix, thankfully.
