### ISSUE TITLE
Game won't start with newer versions

### ISSUE THREAD

**Issue by VampireSultana** [SilentChaos512/SilentGems#371]
### Versions

- **Silent's Gems**: 1.13.2-3.0.12+28
- **Silent Lib**: 1.13.2-4.0.9+24
- **Forge**: 1.13.2-forge-25.0.76
- **Silent Gear**: 1.13.2-1.0.12+24

### Expected behavior
I expect the game to start. But the mods Silent Gems and Silent Gear refuses to load with the game.

### Actual behaviour
The game will not start. I will post screenshots and the log report.

### Links/Images

[latest.log](https://github.com/SilentChaos512/SilentGems/files/3218959/latest.log)

![Untitled](https://user-images.githubusercontent.com/48464007/58362303-b4b2f580-7e63-11e9-9ca7-ad750a4cc5da.jpg)

![Mod Error](https://user-images.githubusercontent.com/48464007/58362304-b67cb900-7e63-11e9-98b5-51195c3058a5.jpg)

**Comment by SilentChaos512** [comment]
Update Forge to a more recent version. This is caused by a mismatch of Night Config versions, which Forge updated in 25.0.149.

**Comment by VampireSultana** [comment]
I have just updated forge to 25.0.215, It starts, but now it shows me this before I load in:
![Mod Error](https://user-images.githubusercontent.com/48464007/58363131-81756400-7e6d-11e9-9cc0-8f7039aed487.jpg)
[latest.log](https://github.com/SilentChaos512/SilentGems/files/3219015/latest.log)
What am I doing wrong??

**Comment by SilentChaos512** [comment]
Those look like 1.12 mods.

**Comment by VampireSultana** [comment]
It seems so.. But that SilentGems mod is one I had just downloaded today, It's the new Release that you uploaded April 25th 2019. It says it's for 1.12.2, but without it, it removes a massive amount of items from my game.
![removed items](https://user-images.githubusercontent.com/48464007/58363323-23964b80-7e70-11e9-9559-f30bc8263202.jpg)

**Comment by SilentChaos512** [comment]
Those items are only in the 1.13.2 version. And you can't load 2.8.17 in any version except 1.12.2. If you are getting this with Gems 3.0+ in your mods folder, it might be related to #366.

**Comment by VampireSultana** [comment]
I have SilentGems-1.13.2-3.0.12+28.jar in my mods folder. I looked at #366 but I don't really understand what could be the problem, because 2.8.17 worked fine this morning on 1.13.2 for some reason until I decided to try and update the files.

**Comment by SilentChaos512** [comment]
Forge definitely cannot load mods from earlier versions. It used to just ignore them, now it gives an error if invalid files are in the mods folder.

The problem with #366 is I still don't know what causes it. Something just seems to randomly prevent mods from loading correctly, while still launching launching the game without any visible errors.

Try clearing out all the 1.12.2 mods from your mods folder, then send me your debug.log, if one is being created.

**Comment by VampireSultana** [comment]
Alright, I removed the mods from the folder, I went to start the game, but I once it gave me the same list of items being removed, I closed the application. This log was updated not too long ago. 
[debug.log](https://github.com/SilentChaos512/SilentGems/files/3219057/debug.log)
Should I have started the game?

**Comment by SilentChaos512** [comment]
Ah, OK, I should have looked at the last screenshot more closely. I did remove some items for blocks that you can't normally get (in your inventory), like powered lamps. The blocks still exist. 148 missing items sounds correct. Backup your world just in case, but it should be fine to load.

**Comment by VampireSultana** [comment]
So I'm not actually losing anything? The items you removed are in fact the items that the launcher is detecting are gone?

**Comment by SilentChaos512** [comment]
Right, the removed items were unnecessary. Should be potted glowroses, lit lamps, and lit inverted lamps. The blocks still exist, but you can't get them in your inventory, so I removed the item forms of them. _To clarify, blocks exist in the world, items exist in inventories. Most blocks have items as well, but some don't._

**Comment by VampireSultana** [comment]
I understand now! Yes, everything still seems to be there! I did back up my world just in case. But yes, it's fine now! Thank you for helping me figure it all out!
