### ISSUE TITLE
Entire server lags when one person teleports.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#372]
### Versions

- **Silent's Gems**: 
- **Silent Lib**: 
- **Forge**: 
- **https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0016** (if applicable): Custom

### Expected behavior

No lag like ftb teleport

- 
Right click = no teleport lag
### Actual behaviour

Extreme 5 second lag serverwide

- 
*Make teleport make it cross dimensions

### Links/Images

- 

### Steps to reproduce the problem

1. Make teleporter and link it 
2. Use teleporter
3. lag like crazy.

**Comment by P3rf3ctXZer0** [comment]
Also on same server this error started happening infinitely [11:35:27] [Netty Server IO #16/WARN] [Silent's Gems]:     Unlocalized names do not match! Did the tool change slots?
![2019-06-03 11_36_49-Window](https://user-images.githubusercontent.com/10351221/58818695-1b6aa880-85f4-11e9-9371-1448e27522b0.jpg)

@SilentChaos512 please help asap.

**Comment by P3rf3ctXZer0** [comment]
That occurred after I disabled teleporter recipes.

**Comment by SilentChaos512** [comment]
Is there anything in particular that triggers that log spam? Is it related to teleporting, or is it just constant? Log spam can definitely cause server lag.

Also, I believe the teleporter recipes configs do not work anymore.

(edit) You forgot to include mod versions.

**Comment by P3rf3ctXZer0** [comment]
From what I can tell nothing actually triggered the log spam unless it is because I shut off recipes

u-SilentLib-1.12.2-3.0.13+167-d-r.jar 5/23/2019 09:54 PM
u-SilentsGems-1.12.2-2.8.17+319-r.jar 5/23/2019 09:52 PM
u-SilentsGems-TiC-1.12.2-0.1.1-5-b.jar 5/24/2019 06:41 PM

The lag actually existed before the spam ironically enough and even with the spam the server is not lagging. Everything is included in the change-log in detail.

The server only actually lags when using the teleporters.

**Comment by P3rf3ctXZer0** [comment]
Changelog
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0016

**Comment by SilentChaos512** [comment]
Version 2.8.18 rewrites the teleporter code to be more similar to FTB Utilities. Let me know if it helps or not. My testing showed it to be very fast. I also disabled the logging message you mentioned. It's probably nothing to worry about, unless you have tools or armor with broken names.

**Comment by P3rf3ctXZer0** [comment]
Thank you I will test it immediately.

**Comment by P3rf3ctXZer0** [comment]
Oh yeah teleporting works perfect - sorry my pc was down for about 3 days and I then I forgot to get back to you @SilentChaos512 thanks for the fix :D
