### ISSUE TITLE
[1.14.2] Advancement for crafting a pedestal given on first login of a new world.

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#373]
### Versions

- **Silent's Gems**: SilentGems-1.14.2-3.1.0+36
- **Silent Lib**: SilentLib-1.14.2-4.1.1+28
- **Forge**: 1.14.2 32
- **Modpack** (if applicable): Custom

### Expected behavior

Not get the advancement for starting a new world, get it when you craft one.

- 

### Actual behaviour **<--- Behavior is spelled wrong in the template**

- 

### Links/Images

![2019-06-17_16 04 22](https://user-images.githubusercontent.com/4427684/59639968-edb85000-9119-11e9-93c1-9d3089fa0550.png)

- 

### Steps to reproduce the problem

1. Start a new world.
2.
3.

**Comment by SilentChaos512** [comment]
I hadn't noticed the issue template error. That's what I get for copy-pasting...
