### ISSUE TITLE
Silent Lib crashes game when I shift+ click "Destroy Items" in creative Tab

### ISSUE THREAD

**Issue by marios-andr** [SilentChaos512/SilentGems#376]
## Versions

- **Silent's Gems**: 3.1.0+36
- **Silent Gear**: Not Installed 
- **Silent Lib**: 4.1.1+28 
- **Forge**: 26.0.35
- **Modpack**: N/A

## Expected Behavior

- Silent Lib or Gems will crash minecraft if I shift + click "Destroy Items" button in Creative Invenory 

## Actual Behavior

- Basically what I said ^ ^ ^

## Links/Images

- https://pastebin.com/LLbmUyit

## Steps to Reproduce the Problem

1. Open your inventory in creative
2. Then shift + click " Destroy Items" Button (What you would normally do to clear your inventory)
3. That's when minecraft crashes and a window appears in the minecraft launcher 
(NOTE: This is in minecraft 1.14.2)

**Comment by SilentChaos512** [comment]
No luck reproducing this with latest versions, can you try updating? A full crash report would have been nice too... What you pasted only tells me something is trying to access a Silent Gear class.
