### ISSUE TITLE
Crash with GuideAPI

### ISSUE THREAD

**Issue by gl0x** [SilentChaos512/SilentGems#38]
http://pastebin.com/bawuHJ30

**Comment by gl0x** [comment]
Fixed when downgrading to GuideAPI-30, assuming SilentGems was referencing an old method or something like that.

**Comment by SilentChaos512** [comment]
Looks like build 31 of Guide-API made some very drastic changes. Continue to use build 30 for now, I'll update as soon as I get the chance.
