### ISSUE TITLE
Server and single player crash - IllegalStateException: Entity is already tracked!

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#380]
## Versions

- **Silent's Gems**: SilentGems-1.14.3-3.2.1+50
- **Silent Gear**: SilentGear-1.14.3-1.2.0+40
- **Silent Lib**: SilentLib-1.14.3-4.2.0+31
- **Forge**: forge-1.14.3-27.0.24
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

## Expected Behavior

- A soul gem drops with the mob info

## Actual Behavior

- soul gems drop with no information and the server crashes.
![unknown](https://user-images.githubusercontent.com/4427684/60737876-7b1ce200-9f19-11e9-8047-3921f7df5212.png)

## Links/Images
Crash report with only silent gems and one other mod. Single player.
https://gist.github.com/litjohn50/e84a9eb74c2e20a1bb1fa7bed6625fae

- Crash report on the server-
https://paste.fedoraproject.org/paste/YSt5swg2tk~y3qGBPuLXvg
https://paste.fedoraproject.org/paste/mXII-RqMF3ZXQFCPp9vk2w
https://paste.fedoraproject.org/paste/zaBnUMsk921520WicnFNbA
https://paste.fedoraproject.org/paste/B2B-E9Tk9OI9ATiYNH9nmA
https://paste.fedoraproject.org/paste/TUs2V8d2ka3rVmhDOCmzng

Not sure if this is related, still searching for the cause of this-
https://paste.fedoraproject.org/paste/KttOOOafom78ht3R826X6Q

## Steps to Reproduce the Problem

1.start a world 
2.kill things
3.crash

**Comment by SilentChaos512** [comment]
I just noticed that soul gems are missing information on the client when playing on a server. The information is based on the world seed, so it gets generated on the server when it's starting up. I just need to send it to the client.

For the crash, I encountered something recently elsewhere, so it should be an easy fix.

**Comment by ProsperCraft** [comment]
Did you see anything here?
https://paste.fedoraproject.org/paste/KttOOOafom78ht3R826X6Q

**Comment by SilentChaos512** [comment]
Not sure what to make of that one. My first thought is maybe a mod that does something with boss health bars, or something similar? I don't believe I'm doing anything that could cause that crash.

**Comment by ProsperCraft** [comment]
This is still happening in single player and on the server- here is a crash report with only Silentgems in single player- 
https://gist.github.com/litjohn50/f81f37b9b24bd6c48712846998a99990
SilentGems-1.14.3-3.2.2+52
SilentGear-1.14.3-1.2.0+40
SilentLib-1.14.3-4.2.2+33

**Comment by ProsperCraft** [comment]
Server crash - https://paste.fedoraproject.org/paste/qzkl60I8Ya29vgj4w-Z4PA

**Comment by ProsperCraft** [comment]
Removed from the server until you can figure out the crashes-
https://paste.fedoraproject.org/paste/MBllm7YuLts8hK8Odt8IbQ
https://paste.fedoraproject.org/paste/e9RVawU4wMxC1CAuexhUZg
https://paste.fedoraproject.org/paste/XjKxGGosHl1DcLXlKUWKdw

**Comment by SilentChaos512** [comment]
I think Silent Gear might be the problem, the sinew drops specifically. I'll try to get an update rolled out today.
