### ISSUE TITLE
Conflict with bamboo mod

### ISSUE THREAD

**Issue by HowQi** [SilentChaos512/SilentGems#382]
## Versions

- **Silent's Gems**: SilentGems 1.3.14-172（minecraft 1.7.10）
- **Silent Gear**:  
- **Silent Lib**:  
- **Forge**: 10.13.4.1614
- **Modpack**: minecraft with SlientGems 1.3.14-172 + Banboo 2.6.8.5

## Expected Behavior and Actual Behavior

The day I want to update the mod I playing recently, After update, I found a crash happend...  Both the game and server can't work. Minecraft will close when it load mods, Minecraft server will report bugs when start server.
After check and try, I find Slient Gems can't work with the latest version Bamboo on MC 1.7.10， Bamboo 2.6.8.5, it is the reason of crash.
 
The mod will work with Bamboo 2.6.7.2.

I hope there's a hint of this mod conflict problem here about bamboo mod, because bamboo mod seems to be a popular mod.

I love the Slient Gems mod, it would be nice if it will compatible with Bamboo mod.

I can provide crash reports if you need, the report is too long to put here.

![chaos6](https://user-images.githubusercontent.com/26505276/61181164-e327a280-a654-11e9-9e87-82877e6c2e89.png)

I am not a native English speaker, I am sorry about some grammar & spelling error.

**Comment by SilentChaos512** [comment]
I appreciate you reporting this properly, but I no longer support versions earlier than Minecraft 1.12.2. I suggest reporting this to the bamboo mod you mentioned. Direct the mod author here if they have any questions.

I can't say anything about the cause without a crash report. But if the bamboo mod recently added any enchantments, that could be related. For future reference, you can upload your crash reports to sites like [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/).

**Comment by HowQi** [comment]
Here is the crash report, I just found the text editor can upload it, sorry. It seems the item name or class name "ruby" cause the problem(In addition, the author of bamboo mod call himself ruby in the craft guide book in game). 

[crashreport-mcserver.txt](https://github.com/SilentChaos512/SilentGems/files/3414186/crashreport-mcserver.txt)
[crashreport-mc.txt](https://github.com/SilentChaos512/SilentGems/files/3414187/crashreport-mc.txt)

About stopping support, OK ... Maybe I should try some newer version MC with this mod sometimes, because the Bamboo mod's author seems to stop support each version of the bamboo mod, at the seam time, the forum which the bamboo published stop running too, I don't know  how to contact the author.

In the end, thanks for your reply and contribution!
*By the way, the latest version of the Slient Gem Mod looks more beautiful.

**Comment by SilentChaos512** [comment]
"ruby" most likely refers to the author in this case, based on package naming conventions. I see no mention of Silent's Gems in the crash report.
