### ISSUE TITLE
Phantom Lights

### ISSUE THREAD

**Issue by RainbowScythe** [SilentChaos512/SilentGems#383]
So I've been trying to research how these lights work in your mod, how they spawn and all that and I have found no where that talks about them at all. I had no issues with them until now. And it's not persay an issue more of frantic confusion. I am trying to grow an ender lilly which I am told requires complete darkness, however there is one phantom light that seems to spawn inside the house I made for the ender lilly. I've noticed punching it will get rid of it but only for so long before it's back. Is there a way to permanently get rid of them or move them to a more not in the way spot.

**Comment by SilentChaos512** [comment]
If you have a chaos flower pot (renamed to luminous flower pot in 1.14), you may need to move it. They can place phantom lights up to about 14 blocks away.
