### ISSUE TITLE
[1.14.4] Soul urns have a complete nbt reset and turn black when 3x3 mined.

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#384]
## Versions
- **Silent's Gems**: SilentGems-1.14.4-3.3.1+56
- **Silent Gear**: SilentGear-1.14.4-1.3.2+51
- **Silent Lib**: SilentLib-1.14.4-4.3.0+38
- **Forge**: forge-1.14.4-28.0.23
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

## Actual Behavior
When you break the urn with a silentgems hammer indirectly when mining 3x3 it wipes its nbt, turns black and becomes empty.

## Links/Images
Gif showing the problem.
https://gyazo.com/cb9892a4c10316cced8d982791941e6a

Another video 
https://gyazo.com/7acb0b1fdd9a72af302838224d6d3cdc

- (Link)

## Steps to Reproduce the Problem

1. Install on a dedicated server
2. place an urn and a block next to it, 
3. mine the urn indirectly by mining the block next to it.

**Comment by SilentChaos512** [comment]
Things I noticed in testing (mostly just listing this for my own reference):

1. Shulker boxes are affected the same way
2. Using a hammer in creative mode keeps NBT _and_ duplicates the block

So, safe to assume the hammer is at fault. I'll look into this ASAP.

**Comment by SilentChaos512** [comment]
Should be fixed by Silent Gear 1.3.3
