### ISSUE TITLE
[1.14.4] Game crash in opening Recipe GUI

### ISSUE THREAD

**Issue by revdave33** [SilentChaos512/SilentGems#385]
## Versions

- **Silent's Gems**: 1.14.4-3.3.1+56
- **Silent Lib**: 1.14.4-4.3.0+38
- **Forge**: 28.0.38

## Actual Behavior
When I open the Recipe GUI either from a crafting bench or from the crafting window in my inventory, the game crashes.

It started with forge-28.0.28

[latest.log](https://github.com/SilentChaos512/SilentGems/files/3463016/latest.log)

## Steps to Reproduce the Problem

1. Open inventory or crafting bench.
2. Mouse click on Recipe GUI icon

**Comment by SilentChaos512** [comment]
Based on some of the chatter on the Forge Discord server, this might be a Forge issue. I just tried updating my development environment and something is definitely not working quite right. I'd recommend using an earlier version of Forge for now, if it's an option for you.
