### ISSUE TITLE
Missing Item Name and texture

### ISSUE THREAD

**Issue by ScrambledGamer** [SilentChaos512/SilentGems#386]
## Versions

- **Silent's Gems**: SilentGems-1.14.4-3.3.1+56
- **Silent Gear**: Not Installed
- **Silent Lib**: SilentLib-1.14.4-4.3.0+38
- **Forge**: forge-28.0.32
- **Modpack**: 1.14.4

## Expected Behavior
Expected Item Name: Planter Urn Upgrade (I think)
Expected Item Texture: (Unknown)

## Actual Behavior
actual In-game item name: item.silentgems.planter_urn_upgrade
actual in-game texture: Missing texture

**Comment by SilentChaos512** [comment]
Fixed in 3.3.3, also added recipes for most of the existing urn upgrades.
