### ISSUE TITLE
Crash when loading world.

### ISSUE THREAD

**Issue by Sunekaer** [SilentChaos512/SilentGems#389]
## Versions

- **Silent's Gems**: SilentGems-1.14.4-3.3.2+58.jar
- **Silent Gear**: SilentGear-1.14.4-1.3.5+54.jar
- **Silent Lib**: SilentLib-1.14.4-4.3.1+39.jar
- **Forge**: 28.0.45
- **Modpack**: N/A

crash: https://paste.dimdev.org/opisuligix.php

**Comment by SilentChaos512** [comment]
This is the fault of another mod, nothing I can do to fix it. The only way to track down the mod at fault is to remove mods until it stops crashing. If you added any mods recently (especially mods that _recently updated from 1.12_), you should check those first.
