### ISSUE TITLE
[1.9] Crash on startup with Inventory Tweaks

### ISSUE THREAD

**Issue by b0bst3r** [SilentChaos512/SilentGems#39]
Forge 1900/1907 (tried both)
SilentLib-1.9-1.0.7-13.jar
SilentsGems-1.9-2.0.11-29.jar

http://pastebin.com/ReAbpz3Y

I would have posted this to Inv tweaks but the same was happening with Tech Reborn and TR fixed this here https://github.com/TechReborn/TechReborn/commit/3509ff4f101c98a37e697abe63623d82bcb0092a

**Comment by SilentChaos512** [comment]
I looked at the TechReborn commit. I don't really get how that could fix the crash, but thanks for linking it. I'll see if I can do anything, but I feel like InvTweaks is at fault.

**Comment by SilentChaos512** [comment]
After looking at this more closely, it's definitely Inventory Tweaks. The version for 1.9 was likely built for an earlier version of Forge. The 1.9.4 version seems to have no issues.
