### ISSUE TITLE
Name needs localizing. block.silentgems.topaz_ore

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#390]
1.14.4

![2019-08-10_22 49 07](https://user-images.githubusercontent.com/4427684/62829907-5f17fa80-bbc1-11e9-9c9a-a8c3d79d9110.png)

**Comment by ProsperCraft** [comment]
block.silentgems.ruby_ore as well.

**Comment by GamertechAU** [comment]
As does the Imperial tool status.

**Comment by SilentChaos512** [comment]
The blocks might be better fixed on HWYLA's end, but it looks like I can write a plugin to fix the issue for my blocks. Wouldn't be surprised if there are other mods that have a similar issue. I use an atypical solution for translating block names, which cuts hundreds of lines from the translation files.
