### ISSUE TITLE
[1.14.4] Failure to connect to server from client

### ISSUE THREAD

**Issue by Mantarri** [SilentChaos512/SilentGems#393]
## Versions

- **Silent's Gems**: 1.14.4-3.3.6+63
- **Silent Gear**:  
- **Silent Lib**: 1.14.4-4.3.1+39
- **Forge**: 1.14.4 - 28.0.49
- **Modpack**: N/A

## Expected Behavior
Client connects to server successfully

## Actual Behavior
Server stops player connection attempt.
- Error `[Netty Epoll Server IO #1/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [silentgems:network] rejected their client side version number`

## Links/Images
https://gist.github.com/TheMisteryMan/5b1fb876f5cc6c1075cc1f4d2bae32b5

## Steps to Reproduce the Problem

1. Add aforementioned versions of Silent's Gems and Silent Lib to client, and server, using aforementioned forge versions.
2. Attempt to connect to server from client.

**Comment by SilentChaos512** [comment]
Double check you have the same version on both the client and server. If so, try restarting the client and server and try connecting again.

**Comment by Mantarri** [comment]
I've already done so (forgot to say so in the original post).

**Comment by Mantarri** [comment]
Forgot about this issue, i believe all I did was update to the latest forge, anyways, I'll close this issue.
