### ISSUE TITLE
[1.14.4] Chaos orbs not breaking when full

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#396]
## Versions
- **Silent's Gems**: 1.14.4-3.3.10+67
- **Silent Gear**: 1.14.4-1.3.9+58
- **Silent Lib**: 1.14.4-4.3.1+39
- **Forge**: 28.0.55
- **Modpack**: Unreleased

## Expected Behavior
The SG Curseforge page says that the chaos orbs are meant to break after absorbing a set amount of chaos.

## Actual Behavior
Testing with multiples of all 3 orbs and they're all full without breaking, so we end up with a stockpile of full orbs.

-Also, I know everything's still new and early for 1.14, but would it be possible to get a basic guide in-game explaining the current chaos system, the events and how to prevent them please? It's all currently a bit hit and miss.

Cheers Silent.

## Steps to Reproduce the Problem
1. Hold or place chaos orb on pedestal
2. Fill it up
3. Orb doesn't break

**Comment by GamertechAU** [comment]
To add to this, some orbs do crack/break as intended but it's hit and miss.

Also, it seems like when they break, they blast all their stored chaos back into the world. Is that correct Silent?

**Comment by SilentChaos512** [comment]
No, the chaos is not released, it just destroys the orb.

Last time I tested this everything seemed to be working. I wonder if some other mods is interfering with items breaking somehow.

**Comment by GamertechAU** [comment]
After an orb broke in inventory, the player chaos went from around 60k to over 2m. It wasn't tested immediately after breaking, but the player hadn't done anything to generate chaos and it's never been that high in the whole playthrough.

Working on narrowing it down, but it's hard to reproduce.
