### ISSUE TITLE
Feature Request: Config for Ender Slimes

### ISSUE THREAD

**Issue by Elsker99** [SilentChaos512/SilentGems#397]
Adding a config for the spawn rate of Ender Slimes. Also changing where they spawn. They seem to spawn in the air A LOT and under platforms and just fall into the void.

They are fun and can't wait for their slime to have function but it would be nice to turn them off or at least lower the rate because it messes with Enderman farms.

**Comment by SilentChaos512** [comment]
Spawn configs already exist, on both 1.14 and 1.12.

**Comment by Elsker99** [comment]
> Spawn configs already exist, on both 1.14 and 1.12.

Sorry i didn’t realize :/ I was trying to find them and I couldn’t. I don’t know exactly where to find these configs. Don’t mean to bother but any thanks
