### ISSUE TITLE
Ticking Player Crash with 

### ISSUE THREAD

**Issue by Mystogrigen** [SilentChaos512/SilentGems#398]
## Versions

- **Silent's Gems**: SilentGems-1.14.4-3.3.11+69.jar
- **Silent Gear**: SilentGear-1.14.4-1.3.10+59.jar 
- **Silent Lib**: SilentLib-1.14.4-4.3.1+39.jar 
- **Forge**: 28.0.92
- **Modpack**: N/A

## Expected Behavior
I can't answer this without sarcasm

## Actual Behavior
It crashes at load.

## Links/Images

https://gist.github.com/Mystogrigen/1402d48fe947c3ec49f7077cee5bac11

## Steps to Reproduce the Problem

1. Load save file.
2. (with other mixes/mashes of versions) crash randomly with a spawn event?

**Comment by SilentChaos512** [comment]
Crash report shows Forge 83. Try updating to 91 or 92.

**Comment by Mystogrigen** [comment]
Grabbed the wrong crash report. Generating a new one now.

https://gist.github.com/Mystogrigen/abd069803298dfd59a646bb0b14851ce

The world refuses to load/create when loaded/created. It hangs.

**Comment by SilentChaos512** [comment]
Ah, OK. Forge 92 did rename some things. For now, you could downgrade to 91, if that's an option for you. I'll try to fix this sometime today or tomorrow.

**Comment by Mystogrigen** [comment]
That worked. Thanks for that.

**Comment by SilentChaos512** [comment]
Leaving this issue open until I can update.
