### ISSUE TITLE
minecraft 1.14.4 is crashing and idk why please help

### ISSUE THREAD

**Issue by jcdriftekv2** [SilentChaos512/SilentGems#399]
[crash-2019-09-06_19.16.36-server.txt](https://github.com/SilentChaos512/SilentGems/files/3586174/crash-2019-09-06_19.16.36-server.txt)

**Comment by SilentChaos512** [comment]
Could have sworn I updated the required Forge version... Forge is making a lot of compatibility-breaking changes right now. You need to either update Forge to 92+ or revert to an earlier version of Gems. You will also need to update Silent Lib if you update Forge, and probably some other mods.

Also, this should have been submitted as a bug report and the issue template followed. Just for future reference.

**Comment by jcdriftekv2** [comment]
ok so update or down grade now when i tried updating every thing eairlyer it seemed to not load id get stuck at 98% or 100% when it was loading my save game or map ?

**Comment by SilentChaos512** [comment]
Then you might be better off just downgrading for now. I think some mods are just waiting for Forge changes to settle down.

**Comment by jcdriftekv2** [comment]
this is what i just got affter updating ill try down grading

[crash-2019-09-06_20.05.27-client.txt](https://github.com/SilentChaos512/SilentGems/files/3586183/crash-2019-09-06_20.05.27-client.txt)
