### ISSUE TITLE
[1.14.4] Server crash on load

### ISSUE THREAD

**Issue by ImAK9** [SilentChaos512/SilentGems#400]
## Versions

- **Silent's Gems**: 3.3.11
- **Silent Gear**: 1.3.11
- **Silent Lib**: 4.3.2
- **Forge**: 28.0.95
- **Modpack**: N/A

## Expected Behavior

- Server to actually load

## Actual Behavior

- Crashes on launch

## Links/Images
Crashlog: https://paste.ee/p/jyLzB

## Steps to Reproduce the Problem
Start server with Silent Gems, Morpheus, Bluepower and Silent Lib

**Comment by SilentChaos512** [comment]
Does the same crash occur without Blue Power?

**Comment by ImAK9** [comment]
Yeah it does

**Comment by ImAK9** [comment]
Just..

[17:18:03] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.xalcon.torchmaster.common.logic.entityblocking.LightsRegistryCapability$RegistryContainer cannot be cast to net.silentchaos512.gems.api.chaos.IChaosSource
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@4f548e3e worldTickEvent(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                2: ASM: class net.silentchaos512.gems.chaos.ChaosHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                3: ASM: class net.silentchaos512.lib.util.EntityHelper onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
                4: ASM: net.silentchaos512.gems.util.SoulEvents@1aeebfdb onTick(Lnet/minecraftforge/event/TickEvent;)V

Instead..

**Comment by ImAK9** [comment]
Could it be Torchmaster?

**Comment by SilentChaos512** [comment]
Could I get a full list of mods from you? If you are using the Twitch launcher, a profile export will work. I would really like to figure out what is causing this. As far as I know, this is the result of another mod. But it would be useful to know why this is happening.

**Comment by ImAK9** [comment]
Do you want the server or client files?

**Comment by SilentChaos512** [comment]
Server

**Comment by ImAK9** [comment]
https://paste.ee/p/RZy4V

**Comment by ImAK9** [comment]
I could make you a zip also if you wanna run and test it yourself

**Comment by SilentChaos512** [comment]
Yes, please do

**Comment by ImAK9** [comment]
https://ufile.io/03imtf7n

**Comment by ImAK9** [comment]
(Be sure to rename that forge(version).jar to forge.jar)

**Comment by SilentChaos512** [comment]
From what I can tell so far, another mod is causing the game to fail to load, but for some reason the game doesn't crash until something (like my mod) tries to access something that was never created. Fast Furnace seems to be one possibility, as removing it eliminated some error messages. I think I have removed all client-side only mods, but something is still accessing client-side classes.

**Comment by SilentChaos512** [comment]
Storage Drawers is also broken. I'm going to report that one to them.

**Comment by ImAK9** [comment]
Any guesses?

**Comment by SilentChaos512** [comment]
Storage Drawers updated. Not sure if Fast Furnace is an issue or not. Other than that, just make sure you have removed all client-side mods from your server.

**Comment by SilentChaos512** [comment]
Reported this issue to Forge: https://github.com/MinecraftForge/MinecraftForge/issues/6148

**Comment by ImAK9** [comment]
Thanks! Hope it's not too hard of a fix.
