### ISSUE TITLE
[1.13.2] Crafting Table isn't working correctly

### ISSUE THREAD

**Issue by TheNightQueenRaven** [SilentChaos512/SilentGems#401]
## Versions
SilentLib-1.13.2-4.0.10+27
SilentGems-1.13.2-3.0.12+28
1.13.2-forge-25.0.219

## Expected Behavior
The crafting table should working as it usually does.

- (Description)

## Actual Behavior
Instead, placing items (such as gold ingots in the formation to create a gold block) makes the items in the crafting table interface become invisible and act as if they are not placed in a configuration at all, and may either cause them to disappear or duplicate the item (such as the gold ingot).

- (Description)
I placed 9 gold ingots from a stack of 64 gold ingots in the standard configuration of 9 spread across all 9 slots for the crafting table interface, as per normal, and instead they disappeared entirely, not even being visible in the interface. The items themselves either got duplicated or were destroyed completely upon leaving the interface (I don't know how to make it duplicate rather than destroy the items, it seems like it might have just been chance?). I did further tests in the video linked below.

## Links/Images
Youtube video made for this bug report: 
(feel free to fast forward the video a bit if you wish)
https://www.youtube.com/watch?v=gLjzSBZo5C0&feature=youtube

## Steps to Reproduce the Problem
In the video linked above, I have shown how to reproduce the issue, but here are the basic steps:

1. Place crafting table and open the interface
2. Place items in the formation of what item you wish to craft
Problem should immediately be seen.

**Comment by SilentChaos512** [comment]
Is this unique to servers? I just tried with just Gear, Gems, Lib, and JEI. Works correctly in singleplayer. Also, what leads you to suspect Gems as the cause?

**Comment by TheNightQueenRaven** [comment]
When I remove both Silent Lib and Silent's gems, the crafting table functions properly again. Also, no, I was playing in single player only. I don't know if it is a version issue between Silent Lib and Silent's Gems, but I really want to get to the bottom of it, I really really love these mods and don't want to play without them. 1.14 is too buggy and laggy for me to play on this system, so 1.13.2 is the highest version I can play right now.

**Comment by SilentChaos512** [comment]
Not sure how familiar you are with what Forge has been doing, but they started on a complete rewrite in 1.13. A full release for 1.13 was never their goal, so that version is incomplete and has a lot of unfixed bugs. There may not be anything I can do. Best advice I can offer is to try removing other mods to see if it fixes the issue. Maybe try rebuilding your pack, adding 5 mods or so at a time to narrow it down.

**Comment by TheNightQueenRaven** [comment]
I wonder if there is a way to fix the bugs for forge?

**Comment by TheNightQueenRaven** [comment]
Is there anything I can do to possibly resolve the issue?
