### ISSUE TITLE
Corrupted slimes appear as wrong size

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#404]
## Versions

- **Silent's Gems**: 3.3.11
- **Silent Gear**: 1.3.10
- **Silent Lib**: 4.3.2
- **Forge**: 
- **Modpack**: N/A

## The Problem

The size of corrupted slimes seems to differ on client and server side (also applies to singleplayer). Slimes often appear to be small, but act like large or medium slimes.

**Comment by CyanSlinky** [comment]
hopefully you can fix this one, it's ended 2 of my hardcore runs. (I'm not mad or anything i know i have to deal with this stuff while 1.14 mods are still WIP etc.) oh and they also seem to be really fast sometimes?

**Comment by SilentChaos512** [comment]
I'm sure it's fixable, probably just missing a method call. The speed is probably just because they're bigger than they look. You can tell the size of the slimes by looking at the particles. Bigger slimes make particles in a bigger area when they land.
