### ISSUE TITLE
Server Crash on Startup 

### ISSUE THREAD

**Issue by IchigoGames** [SilentChaos512/SilentGems#405]
## Versions
- **Silent's Gems**:SilentGems-1.14.4-3.3.12+71
- **Silent Gear**:SilentGear-1.14.4-1.3.11+60
- **Silent Lib**:SilentLib-1.14.4-4.3.2+42
- **Forge**:28.0.95
- **Modpack**: N/A

## Expected Behavior
for server to start

- (Description)

## Actual Behavior
Server Crashed

Updated Silent Gems and Silent Gear also added a few mods to my test pack for my modpack works fine in singeplayer but will crash on server.

Crash Report https://pastebin.com/CqXbnUkp

## Steps to Reproduce the Problem
not sure

**Comment by IchigoGames** [comment]
may have something to do with adding StorageDrawers-1.14.4-6.0.2

**Comment by SilentChaos512** [comment]
I've seen this very same crash report dozens of times by now. As far as I know, this is the result of another, broken mod. No easy way to tell which. Log files might contain clues. Otherwise you just need to try removing or downgrading mods.

**Comment by IchigoGames** [comment]
i was able to get it to work by Removing SilentGear-1.14.4-1.3.11+60

**Comment by IchigoGames** [comment]
but of course without that silent gems does not have much use

**Comment by SilentChaos512** [comment]
That's odd. Could I get a full log file from when it crashed? The debug.log file, if possible.

**Comment by IchigoGames** [comment]
ok one min

**Comment by IchigoGames** [comment]
https://pastebin.com/iusShznN crash report      

https://www.dropbox.com/s/1a5sqwv6f7kn8sp/debug.log?dl=0 

https://www.dropbox.com/s/6nx8vk7w5seb75a/latest.log?dl=0

**Comment by SilentChaos512** [comment]
I see this line in the log file: `[11Sep2019 10:16:12.722] [modloading-worker-1/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraftforge/client/event/GuiScreenEvent for invalid dist DEDICATED_SERVER`.

Looks like you have a either a client-side mod, or one that is accidentally trying to load a client class on the server. I know Silent Gear does not use that event, so I'm not sure why removing it would fix the issue.

**Comment by IchigoGames** [comment]
not sure what i removed all the client side mods from my server files

**Comment by IchigoGames** [comment]
ops i guess searchablechests-1.14-1.5.1 is a client side mod

**Comment by SilentChaos512** [comment]
I have yet to find any easy way to determine which mod is responsible. I'm preparing to report this issue to Forge because I'm dealing with it almost daily now. Forge should be crashing the server when a mod fails to load. Instead, they just let it keep running and it crashes somewhere else instead.

Best thing you can do right now is try removing mods. I would guess the ones above line 914 in the debug.log you posted are most likely. ~~I see Searchable Chests mentioned, maybe that one?~~ Was just about to mention that.

**Comment by IchigoGames** [comment]
before i open a new support ticket any idea what this means The server is likely to require channel [[silentgear:network]] to be present, yet we don't have it                                                                       

kicks me from my server when i join

**Comment by SilentChaos512** [comment]
I don't believe I've seen that one before

**Comment by IchigoGames** [comment]
oh it might help if i re add silent gear to my client
