### ISSUE TITLE
Placing a Glow rose on ground Crashes Server.

### ISSUE THREAD

**Issue by IchigoGames** [SilentChaos512/SilentGems#406]
## Versions
- **Silent's Gems**:SilentGems-1.14.4-3.3.13+72
- **Silent Gear**:SilentGear-1.14.4-1.3.11+60 
- **Silent Lib**:SilentLib-1.14.4-4.3.2+42 
- **Forge**:28.0.104
- **Modpack**:The New Frontier Reloaded

## Expected Behavior
Placing a Glow rose on ground should have no issues 

- (Description)

## Actual Behavior
Placing a Glow rose on ground Crashes Server

- (Description)
Player was Placing a Glow rose on ground and it Crashed Server

## Links/Images
https://pastebin.com/ScSYm9iC
https://www.dropbox.com/s/6nx8vk7w5seb75a/latest.log?dl=0
https://www.dropbox.com/s/1a5sqwv6f7kn8sp/debug.log?dl=0

## Steps to Reproduce the Problem
place a glow rose on the ground on a server

**Comment by SilentChaos512** [comment]
Naturally Charged Creepers needs to fix this.

**Comment by SilentChaos512** [comment]
Wait, maybe not. I may need to fix this.

**Comment by IchigoGames** [comment]
Going to be updating silent gems soon ?

**Comment by SilentChaos512** [comment]
Yeah, I'll upload a new build in a minute.
