### ISSUE TITLE
Corrupted slime spawn crashing the game

### ISSUE THREAD

**Issue by Cobaaalt** [SilentChaos512/SilentGems#408]
## Versions

- **Silent's Gems**:  3.3.10+67
- **Silent Gear**: 1.3.11+64
- **Silent Lib**:  4.4.0+44
- **Forge**: 28.1.0
- **Modpack**: N/A

## Expected Behavior

- Not much, aside this issue being fixed?

## Actual Behavior

- Game just freezes and then crashes.

## Links/Images

- http://www.mediafire.com/file/ubdqp18mreo4jot/2019-09-14-6.log/file

## Steps to Reproduce the Problem

1. Walk around till corrupted slime is queued to spawn. (presumably at night)

**Comment by SilentChaos512** [comment]
That version of Silent's Gems is not compatible with the latest Forge. You need to update.
