### ISSUE TITLE
[1.14.4] Loot tables stack traces in single player logs-

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#409]
## Versions

- **Silent's Gems**:SilentGems-1.14.4-3.4.1+74
- **Silent Gear**:SilentGear-1.14.4-1.3.11+64
- **Silent Lib**:SilentLib-1.14.4-4.4.0+44
- **Forge**: 1.0.6
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

## Links/Images

Log-
- https://gist.github.com/ProsperCraft/678443cb5c22c306623085e0fdeaf3e2

Log excerpt-
https://gist.github.com/ProsperCraft/60c71467c276bb1e6aa39cdd69687fa2

**Comment by SilentChaos512** [comment]
Seems to be caused by Explorercraft. I'm guessing it's trying to add loot to some loot tables, but without putting a name on the loot pools.

**Comment by SilentChaos512** [comment]
Reported to Explorercraft: https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion?comment=123
