### ISSUE TITLE
My game is crashing when i enter in my world

### ISSUE THREAD

**Issue by LucyusSama** [SilentChaos512/SilentGems#410]
## Versions

- **Silent's Gems**: 1.3.11
- **Silent Gear**: 3.4.1
- **Silent Lib**: 4.4.0
- **Forge**: 28.1.5
- **Modpack**: N/A

## Expected Behavior

- (Description)
I Just want to play ;-;
## Actual Behavior

- (Description)
When my world load, the game crashes
## Links/Images

[crash-2019-09-17_18.19.24-server.txt](https://github.com/SilentChaos512/SilentGems/files/3623573/crash-2019-09-17_18.19.24-server.txt)

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
Crash is caused by another mod. If this is a server, make sure you have removed client-only mods from the server. If you can provide a log file (debug.log if possible), I may be able to help find the cause.

Related issue on Forge: https://github.com/MinecraftForge/MinecraftForge/issues/6148

**Comment by LucyusSama** [comment]
How i find out wich mods are "client-only"?
Sorry if that question is kinda "noob" it's because i'm new on that "MODS WORLD"
I can show my mods folder, i have just 8 mods (taking out your mods)

**Comment by LucyusSama** [comment]
PS: i'm not using servers, im just playing the solo game

**Comment by SilentChaos512** [comment]
Your mod list is in the crash report, I don't see anything that would seem to be the issue. Placebo is one version behind. Maybe try updating Forge.

The logs folder will be in the same place as the config and mods folders. The debug.log has the most information, but latest.log might work if you don't have that.
