### ISSUE TITLE
Add Silver Ore config

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/SilentGems#411]
## What Should Be Added or Changed?
Add Silver Ore config in silentgems-common.toml; more specifically the world gen able to be disabled

## Why Should This Be Done?
More config options are always good, but mostly because Silent's Mechanisms adds Silver Ore too.
(Other misc ores would be nice as well, but Silver Ore is the only redundant one)

**Comment by SilentChaos512** [comment]
Added a config to set veins per chunk. Defaults to 0 if Silent's Mechanisms is installed.
