### ISSUE TITLE
[1.14.4] Empty loot chests.

### ISSUE THREAD

**Issue by kaggya** [SilentChaos512/SilentGems#414]
## Versions

- **Silent's Gems**: 3.4.2 + 75
- **Silent Gear**: 1.4.1 + 66
- **Silent Lib**:  4.4.0 + 44
- **Forge**: 1.14.4 - 28.1.18
- **Modpack**: N/A

## Expected Behavior

Loot chests that are not completely empty when opened.

## Actual Behavior

Certain loot chests, namely those found in nether_bridge, simple_dungeon, abandoned_mineshaft, buried_treasure, and desert_pyramid would spawn without any items present whatsoever. All other loot chests appear to function normally, with items from mods including Silent's Gems turning up as usual. 

Loot tables were tested via The One Chest item from the Enigmatic Legacy mod, which spawns loot in a chest of the user's choice according to the table that is currently selected. In this case, all of the tables were tested, with the only problematic ones being the ones listed above.

## Links/Images

Excerpt from latest.log. Full log included.
https://gist.github.com/kaggya/d4d4eb3b6d58c715a78ab1df4a1e47c7

## Steps to Reproduce the Problem

Unknown.

**Comment by SilentChaos512** [comment]
Looks identical to #409. Seems to be caused by another mod modifying a loot table without putting names on their pools. Explorercraft is one mod that is/was doing that.

**Comment by ChilledDayZ07** [comment]
I don’t have explorercraft installed and I’m having the same issue in my nether fortress all the chests are empty.

**Comment by SilentChaos512** [comment]
Any mod could potentially do this. There is currently no easy way to tell which, other than disabling mods.

(edit) Someone really needs to report this to Forge. This could be fixed with 2 lines of code. Guess I should do that whenever I can get around to writing the report...

**Comment by ChilledDayZ07** [comment]
I found what my problem was and it was me, I had treasure bags installed and I guess I messed up the loot tables.

**Comment by WildDragon1980** [comment]
I tested with a small amount of mods installed and it looks like the cause is Silent Gear and not silent's gems. With both installed I was getting empty loot chests. After removing Silent Gear my loot chests were populated again.
