### ISSUE TITLE
1.14.4 - Ender Slimes spawn over the void and die

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/SilentGems#415]
## Versions

- **Silent's Gems**: 3.4.3+76
- **Silent Gear**: 1.4.1+66
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.8 (I know it's old, but this is the latest version Twitch App has available right now)
- **Modpack**: N/A

## Expected Behavior
Ender Slimes spawn on the End Stone, but not over the void. I would expect them to fall of the islands, but not _spawn_ off of them.

- (Description)

## Actual Behavior
Ender Slimes spawn on both the ground and over the void. You can see the death particles constantly.

- (Description)

## Links/Images
Side of an island:
![image](https://user-images.githubusercontent.com/19861808/65821698-c7b54800-e1fe-11e9-853c-f116424b1b99.png)

Underside of an island:
![image](https://user-images.githubusercontent.com/19861808/65821756-9db05580-e1ff-11e9-8e04-607d3656810a.png)

## Steps to Reproduce the Problem

1. Have mods installed
2. Go to outer end islands (/setblock ~ ~ ~ minecraft:end_portal, /tp ~ ~ ~-10000)
3. Fly over void and watch smiles spawn without ground

**Comment by SilentChaos512** [comment]
Twitch launcher actually does have newer versions, but they don't sort the list properly. You have to scroll down a bit. But I don't think any recent Forge updates have changed anything to do with entity spawns. Will investigate.

**Comment by ProsperCraft** [comment]
I can confirm that the slimes are spawning in the void and falling to their death over and over, came to report it but got beat by 3 hours :)

and yes, the new versions of forge are in the launcher.

**Comment by vizify** [comment]
Is there a way to spawnproof this? because I wanted to build an enderman farm but the slimes messed with the spawning of enderman

**Comment by SilentChaos512** [comment]
@vizify I'm not too familiar with how enderman farms are constructed (been years since I made one). I can set ender slimes to not spawn above Y 65, does that help?

**Comment by vizify** [comment]
Ok that helped a lot thanks

**Comment by vizify** [comment]
I thought ender slimes won't spawn above Y 65, but it still spawns on Y 245. Is that a bug?

**Comment by SilentChaos512** [comment]
@vizify I'm not seeing any issues. Made a 100x100 platform and no spawns. Verified the height check is occurring with a debugger.

**Comment by vizify** [comment]
Is the debugger the debug stick thing? Sorry I don't really know about commands and debug stuffs

**Comment by SilentChaos512** [comment]
No, it's a development tool used to step through code and find issues. It's not something related to Minecraft specifically, just software development in general.
