### ISSUE TITLE
Recipe Book Bug

### ISSUE THREAD

**Issue by itsgelo** [SilentChaos512/SilentGems#416]
## Versions

- **Silent's Gems**: 3.4.4
- **Silent Gear**: 1.4.3
- **Silent Lib**: 4.4.0
- **Forge**: 28.1.31
- **Modpack**: N/A

## Expected Behavior

- Resolve the issue of the mod items showing up in the recipe book

## Actual Behavior

- The item mods from both Silent Gems and Silent Gear show up on my recipe book as a craftable item, but it shows no recipe for it at all, it also shows spawn eggs that cannot be crafted in the recipe book.

## Links/Images

-  https://gyazo.com/8c85c1b9e0d739c4ee070342c470cd54

**Comment by SilentChaos512** [comment]
Unrelated, but I'm curious about the enchantment tokens missing their first layer. Do you have Optifine installed?

**Comment by itsgelo** [comment]
Yes I do, If that causes the bug then I will gladly delete Optifine

**Comment by SilentChaos512** [comment]
I wouldn't be surprised, Optifine has other issues with multi-layer item models.

**Comment by itsgelo** [comment]
The tokens seem to appear fine on JEI, just not on the recipe book
