### ISSUE TITLE
1.12.2 Picking up Material Grader deletes gems inside

### ISSUE THREAD

**Issue by Shirukenu** [SilentChaos512/SilentGems#417]
## Versions

- **Silent's Gems**: SilentGems-1.14.4-3.4.4
- **Forge**: 14.23.5.2844

## Expected Behavior
Material grader, stack of gems to be graded and graded gems become objects to pick up when material grader is broken with appropriate tool (pickaxe in this case)

## Actual Behavior

Material grader becomes an object that can be picked up, but all gems inside are deleted. Placing the material grader doesn't make them come back as if it was a container that retains inventory.

## Steps to Reproduce the Problem

1. Place down material grader.
2. Put gems inside material grader.
3. Use pickaxe to break material grader.
4. Cry.

**Comment by SilentChaos512** [comment]
Why did you list this as 1.14.4 when you are clearing playing 1.12.2?

**Comment by Shirukenu** [comment]
That's a good question. Fixed.
