### ISSUE TITLE
Gem stats aren't showing up in SMP

### ISSUE THREAD

**Issue by Stefanowhb** [SilentChaos512/SilentGems#418]
![](https://i.imgur.com/laqlzQt.png)
```[Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize biomesoplenty.common.command.BiomeArgument@2066e281 (class biomesoplenty.common.command.BiomeArgument) - will not be sent to client!
[Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@5b6325af (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@160dcf53 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.silentchaos512.gear.api.parts.MaterialGrade$Argument@1efa2b7b (class net.silentchaos512.gear.api.parts.MaterialGrade$Argument) - will not be sent to client!```

**Comment by SilentChaos512** [comment]
Need a full client and server log file.

**Comment by Stefanowhb** [comment]
[server latest.log](https://github.com/SilentChaos512/SilentGems/files/3694865/latest.log)
[client latest.log](https://github.com/SilentChaos512/SilentGems/files/3694867/latest.log)
these right?

**Comment by SilentChaos512** [comment]
It looks like everything is working based on the log file... I see parts being received by the client.

There is one error that stands out on line 1017 of the server log. Looks like some mod is adding stuff to a loot pool incorrectly. I'm not sure if that's causing this issue, but it might be related. No idea which mod is causing it.

**Comment by Stefanowhb** [comment]
Really weird bug, i restarted the server and it seemed to have fixed itself... Odd. Might be some problem with another mod though, like you said

**Comment by ProsperCraft** [comment]
Same problem here on The Adventures of Halk server-
![2019-10-21_22 39 29](https://user-images.githubusercontent.com/4427684/67259580-da184f80-f453-11e9-9484-2e31635ecabf.png)

Server logs-
[latest.log](https://github.com/SilentChaos512/SilentGems/files/3753845/latest.log)
[debug.log](https://github.com/SilentChaos512/SilentGems/files/3753846/debug.log)

Client logs-
[latest.log](https://github.com/SilentChaos512/SilentGems/files/3753848/latest.log)

SilentGems-1.14.4-3.4.6+79
SilentMechanisms-1.14.4-0.6.6+39
SilentLib-1.14.4-4.4.0+44
SilentGear-1.14.4-1.4.3+68

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
Version 1.1.11

**Comment by ProsperCraft** [comment]
Server reboot did not fix it.

**Comment by SilentChaos512** [comment]
@ProsperCraft Something has definitely gone very wrong here. I tried opening the parts GUI in the crafting station and I get this.

![2019-10-22_12 25 49](https://user-images.githubusercontent.com/5721949/67313163-21402800-f4c8-11e9-93e5-6ff9366d6325.png)

I tried relogging without restarting the game and that fixed it. Not sure why this is happening.
