### ISSUE TITLE
1.12.2 Config to disable Fluffy Seeds

### ISSUE THREAD

**Issue by TheCowMonarch** [SilentChaos512/SilentGems#419]
Trying to setup my modpack to have most seeds only available through something like the Farming for Blockheads market. 

From what I can tell there is no way to stop seeds from dropping when grass is broken.

**Comment by SilentChaos512** [comment]
I assumed you're on 1.12.2 since you mentioned the seeds dropping from grass. But I'm going to add a similar config for 1.14.4 as well.
