### ISSUE TITLE
Config to disable Mending Enchantment Token

### ISSUE THREAD

**Issue by tommyTT** [SilentChaos512/SilentGems#42]
I'm okay with the other enchantment tokens being craftable since you take out the randomness of the enchantment table, but I have a problem with the one for Mending. The recipe is way too cheap, nether stars are nothing expensive in modded at a certain point in time. Also it doesn't fit, because you can not get a mending enchantment from a table, only by trading with a librarian villager. And since the whole enchantment is way too overpowered anyway, I would suggest to make it at least configurable if this token can be crafted or not.

**Comment by SilentChaos512** [comment]
Sounds good, I had some doubts about adding them in the first place. I think most people said "Yes" on the Twitter poll (for what little that's worth). I'll add a config for both treasure enchantments, but they'll be enabled by default.
