### ISSUE TITLE
Enchanted book

### ISSUE THREAD

**Issue by crunchynut609** [SilentChaos512/SilentGems#421]
not so much a problem, but a question.

how do you use a supercharge 1 enchanted book?

I was going through my villager trades and noticed it there and thought "oh" and when I tried an anvil it didn't work.

why would there be a book if you cant use it?

looks like 2 questions, oops

**Comment by SilentChaos512** [comment]
What Minecraft version? I thought this was fixed already. The books are not usable, so they shouldn't be obtainable.

Please follow the template next time. It exists for a reason.

**Comment by crunchynut609** [comment]
im using the mods in 1.14.4 of their latest versions

I am able to obtain the books from a zombie villager after I cured it and started cycling through their trades
