### ISSUE TITLE
Console spewing loads of loot table errors, empty loot chests in world.

### ISSUE THREAD

**Issue by diydavindra** [SilentChaos512/SilentGems#424]
## Versions
- **Silent's Gems**: 1.14.4-3.4.6+79 
- **Silent Gear**: 1.14.4-1.4.3+68
- **Silent Lib**: 1.14.4-4.4.4.0+44
- **Forge**: 1.14.4-28.1.70
- **Modpack**: FTB Unstable (hand made server)

## Expected Behavior
Loot chests spawning with items.

## Actual Behavior
Some chests will spawn items while others will be empty, posted link to error log from console below. (this is only a snipped bit its a wall of text of these loot table errors.)
server log https://pastebin.com/J8AV7bxf

## Steps to Reproduce the Problem
Copied mods from pack removed singplayer mods and threw them in server.

**Comment by SilentChaos512** [comment]
This is caused when another mod adds loot to loot tables without setting pool names. I'm not aware of any easy way to tell _which_ mod is responsible.

**Comment by diydavindra** [comment]
Damn, that sucks the only real reason why i assumed it was silentgems was cause it seems to error out afterwards. But yea that does make sense.
