### ISSUE TITLE
Black Dye and White Dye Makes Light Blue Dye?

### ISSUE THREAD

**Issue by jelaw21** [SilentChaos512/SilentGems#426]
## Versions

- **Silent's Gems**: 2.8.22+327
- **Silent Gear**: N/A
- **Silent Lib**: 3.0.13+167 
- **Forge**: 14.23.5.2847
- **Modpack**: Skyblock Billionaire

## Expected Behavior
Crafted Black Dye with Bone Meal to get Gray Dye

## Actual Behavior
Crafted Black Dye with Bone Meal and got Light Blue Dye

- (Description)

## Links/Images
![image (2)](https://user-images.githubusercontent.com/21100827/67985766-f3618e80-fbff-11e9-85b3-f5dcced4c7dc.png)

- (Link)

## Steps to Reproduce the Problem
1. Place Black Dye and White Dye on crafting grid

I notice that both the black and blue dyes have an item id of <silentgems:dye> but  neither of them have any metadata.

![image (3)](https://user-images.githubusercontent.com/21100827/67986018-800c4c80-fc00-11e9-85e9-48752c4014df.png)

![unnamed](https://user-images.githubusercontent.com/21100827/67986023-839fd380-fc00-11e9-9a7e-853687c3a43c.png)

**Comment by SilentChaos512** [comment]
No idea when that broke. Confirmed it's not caused by another mod. I'll look into fixing this whenever 1.12.2 needs another update. Just use vanilla dyes for the time being.
