### ISSUE TITLE
1.14 - Luminous Flower Pot is buggy

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/SilentGems#429]
## Versions

- **Silent's Gems**: 1.14.4-3.4.6+79
- **Silent Gear**: Not needed
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 28.1.92
- **Modpack**: N/A

## Expected Behavior

Luminous flower pot works like it did in 1.12

## Actual Behavior

Luminous Flower Pot:
- doesn't show the glowrose in it
- has a full block bounding box
- the lights it generates have an x-ray effect
- edit: does not have a loot table, and I don't think it drops its contained glowrose

## Links/Images

![image](https://user-images.githubusercontent.com/19861808/69483869-4e973300-0df2-11ea-85d8-da794cfd3411.png)

![image](https://user-images.githubusercontent.com/19861808/69483876-640c5d00-0df2-11ea-9670-5a1b7a194a8e.png)

- (Link)

## Steps to Reproduce the Problem

1. Place luminous flower plot
2. Place glowrose in it
3. Observe bugs

**Comment by mg-carlos** [comment]
This issue is present in SilentGems-1.15.2-3.5.0+83.

**Comment by Partonetrain** [comment]
^ Only the glowrose not showing and not dropping from the pot
