### ISSUE TITLE
Default frequency of End Essence Ore too high

### ISSUE THREAD

**Issue by tommyTT** [SilentChaos512/SilentGems#43]
The frequency at which the ores spawn in the end is way too high in my opinion. Since it doesn't have too many uses at the moment (that I know of), I would suggest to turn down the default values by a lot, especially considering all the new islands in the end now in 1.9.

**Comment by SilentChaos512** [comment]
I'll keep that in mind. I'd like to reach the End in survival once on my own to get a feel for it. Then I'll tweak the defaults.
