### ISSUE TITLE
No Enchantments in Rune Slates after Crafting

### ISSUE THREAD

**Issue by PessimisticBastard** [SilentChaos512/SilentGems#430]
## Versions

- **Silent's Gems**: 1.14.4-3.4.6+79
- **Silent Gear**: 1.14.4-1.4.5+71 
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 1.14.4-forge-28.1.102
- **Modpack**: N/A

## Expected Behavior
Rune slates have enchantments on them.

- (Description)

## Actual Behavior
Rune slates are left completely blank when crafted, leaving an empty rune. I believe it may have something to do with having updated forge.

- (Description)

## Links/Images

<a href="https://imgur.com/T4JCYUi"><img src="https://i.imgur.com/T4JCYUi.png" title="source: imgur.com" /></a>

- (Link)

## Steps to Reproduce the Problem
Uncertain, problem appeared as soon as the map loaded & I tried to use my chaos gem with levitation on it, only to discover it wasn't working, and no longer has levitation on it.

**Comment by SilentChaos512** [comment]
Probably a broken mod that's preventing some data files from loading correctly. Your log file may have clues about what's going on, if you would share it. This kind of issue can be tricky to track down though. Sometimes you just have to try disabling mods until you find the one.

**Comment by PessimisticBastard** [comment]
Well, I finally had the time today to go through and figure out what was causing the issue.
It was Useless mod that was causing the issue. I have no idea what changed from its previous version to the latest, but that seems to be the problem child.
