### ISSUE TITLE
1.12 - Pixelmon and Silent Gems

### ISSUE THREAD

**Issue by onyxagata** [SilentChaos512/SilentGems#432]
When running Silent Gems with Pixelmon, I think something with the gui's happen were they both try to load at the same time or something. This makes the battle screen in pixelmon grey and blurs the text

Id like to see if youre willing to put a toggle for the guis in the config

**Comment by SilentChaos512** [comment]
Not sure what would cause something like that. Could I get a screenshot, please?

**Comment by P3rf3ctXZer0** [comment]
yeah I can confirm this bug. Something with the lighting :(

**Comment by P3rf3ctXZer0** [comment]
![xuM8FMC](https://user-images.githubusercontent.com/10351221/71956304-66632480-31b0-11ea-9dfa-4ed03dcd02a4.png)
https://i.imgur.com/xuM8FMC.png

**Comment by P3rf3ctXZer0** [comment]
Hey I found out this may be cause by the way pixelmon is handling the world thread https://gist.github.com/P3rf3ctXZer0/469307461f47dc122cf13339f9ba6a0a

Does silent gems also modify world state?

**Comment by SilentChaos512** [comment]
@P3rf3ctXZer0 Your log excerpt points to Phosphor being the cause. Hard to say if this is even the same issue, since OP hasn't provided any information.
@onyxagata Can you provide more information on your issue? Like a screenshot and/or log file?

**Comment by P3rf3ctXZer0** [comment]
I talked to pixelmon devs - they said its caused by the way spawning handles lighting.

**Comment by P3rf3ctXZer0** [comment]
![nEuWEJ2](https://user-images.githubusercontent.com/10351221/71991422-6425b800-31fa-11ea-81b8-9984a2b5f448.png)

**Comment by P3rf3ctXZer0** [comment]
Phosphor just noticed the hole in the code. Thats all.
