### ISSUE TITLE
More detail about broken mod

### ISSUE THREAD

**Issue by McKitten** [SilentChaos512/SilentGems#433]
Server side/Pack admins need more detail about the apparent broken mod causing Chaos Buff error to narrow it down. 

99 mods (3 are silentx)  so could it be anything. 

latest.log output https://pastebin.com/p1nR22ez

Whilst 3rd party problems are not yours, enabling us to find a work around is in the mods best interest; and personally appreciated.

**Comment by SilentChaos512** [comment]
I see a "Failed to reload data packs" warning on line 2249 of your log (mod are data packs, btw). The stacktrace right below that mentions a mod with the mod ID "mca". I'm guessing that's it.

I would have provided a more useful warning message, but my mods have no way of telling what's causing data loading to fail. One mod breaks and everything else just fails to load. Best I can do is let you know when my objects are missing.

Please update me when you discover the cause of the issue. Hopefully it's an easy fix.

**Comment by Ommina** [comment]
I'm reasonably certain that is [MCAdditions](https://www.curseforge.com/minecraft/mc-mods/mcadditions) -- it might be worthwhile dropping that particular mod temporarily to see if that resolves the problem.

Closed source, and no issue page that I've found.

On the other hand, why a mod that appears to deal in adding decorative blocks would have an EntityHuman in the first place is beyond me.  It may be the mca, also, is being implicated unfairly.

**Comment by McKitten** [comment]
You guys were spot on.
I'll give retrograding MCA version a shot first first but the effort alone has me as a fan-g.. er kitty.

**Comment by McKitten** [comment]
MCA-1.1.0 being active still breaks it - will have to disable til more research can be done.
I noticed issues with SilentGems 79 but never had a warning of it. It was working prior to this tho so something else is involved but as I inferred in my first post, time is an issue no amount of awesome help can fix.
Thank you tho.

**Comment by Ommina** [comment]
So long as @SilentChaos512  isn't opposed to the discussion continuing a bit, I'll mention that Vampirism is listed earlier in the stack trace.  That's another candidate to disable temporarily.

Line 2263 of your log:

 `at de.teamlapen.lib.lib.config.BloodValueLoader.loadBloodValuesFromDataPack(BloodValueLoader.java:70) ~[?:1.6.0-alpha+20191210-0113]`

does mention data pack loading, as well, which certainly gives one pause.

**Comment by McKitten** [comment]
That may actually be the real cause then but mca is the easier one of the two to disable due to the world gen of vampyrism. Maxiner was late to the 1.14 party but will hopefully fix his stuff soon enough because of the rapid progress he is making. Very few mods for 1.14 seem actually complete but you take what you can get as a pack creator, even if you have 5 tech mods and only 1 of then has cables.
