### ISSUE TITLE
1.14 Slimes timing entry in toml

### ISSUE THREAD

**Issue by McKitten** [SilentChaos512/SilentGems#434]
## What Should Be Added or Changed?
Configuration to change the time between slime spawns

## Why Should This Be Done?
The current setting is OK for experienced players but may cause rage quitting for newbies. Admins need the ability to modify this timing on server side; perhaps even a separate timing for the ones with advanced abilities - especially since they have a penchant for destroying farmland and/or fences in their way.
A cooling off period on start game could also be useful, ensuring a player has a home bed set before initiation.

**Comment by Partonetrain** [comment]
I agree they are quite annoying. You can turn off the spawning event entirely in silentgems-common.toml 
`"silentgems:corrupted_slimes" = false`

**Comment by SilentChaos512** [comment]
Definitely some good ideas here, thanks. I really like the idea of limiting some/all events to after a player has a bed.
