### ISSUE TITLE
1.12 Crash with Roots

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [SilentChaos512/SilentGems#439]
## Versions

- **Silent's Gems**: 2.8.22 +327
- **Silent Lib**: 3.0.13 +167
- **Forge**: 14.23.5.2836
- **Modpack**: Enigmatica 2 with a bunch of mods added

## Expected Behavior
Smooth sailing

## Actual Behavior
A crash right after the world goes ' light' (when all blocks dissapear and all you see are entities in the minecraft fog) 

## Links/Images
https://paste.dimdev.org/ajetoyalir.mccrash

I will also be reporting this to the Roots dev.
Love this mod btw, have added it to every pack Ive ever played

**Comment by noobanidus** [comment]
This is on my side, feel free to close.
