### ISSUE TITLE
[1.9.4] 2.0.13-37 - Crash on startup server side

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/SilentGems#44]
Description: Dedicated server crashes on startup with newest SilentGems/Lib, fixed when I revert.
Version: 2.0.13-37
Lib: 1.0.9-15
Forge: 12.17.0.1940
[Crash Report](https://gist.github.com/dirtyfargo/e3b7cba36906b8afd3b5bd008791024a)

**Comment by SilentChaos512** [comment]
That's a big issue. I'm not sure how to fix that properly at the moment, but I'll upload an altered version of Silent Lib that won't crash.

**Comment by dirtyfargo** [comment]
Ah no worries, thank you :)

**Comment by SilentChaos512** [comment]
I'll close this issue since the crash has been fixed, and create a new one to address the underlying issue. Thanks for always reporting these crashes so quickly :)
