### ISSUE TITLE
Chaos Events Crashing Server

### ISSUE THREAD

**Issue by dreckz** [SilentChaos512/SilentGems#440]
## Versions

- **Silent's Gems**: 3.4.7
- **Silent Gear**: 1.4.6 
- **Silent Lib**: 4.4.0
- **Forge**: 28.1.107
- **Modpack**: Treasures of Altera 1.3.8
- **MC Version**: 1.14.4

## Expected Behavior

- When loading into the world on an SMP server, it should load the character, and if the chaos event is imminent, it should do the chaos event

## Actual Behavior

- When loading into the world on SMP, a chaos event attempts to occur and crashes the server

## Links/Images

- [crash-2020-01-26_08.54.15-server.txt](https://github.com/SilentChaos512/SilentGems/files/4113546/crash-2020-01-26_08.54.15-server.txt)

## Steps to Reproduce the Problem

1. Load into server on a chunk that is attempting to incur the chaos event.
2. Occurs semi-randomly randomly.

**Comment by McKitten** [comment]
Same issue here, 3 consec crashes from the same https://pastebin.com/CsLzn0qx
I suspect because this is a natural slime chunk that myself and another player are in that something is amplifying the problem but he has not started with Gems and was reporting high slime counts before entering my slimey mine.

**Comment by SilentChaos512** [comment]
This _might_ be fixed by 97ede0f5be29f502dfc0ca55c040d1f20f733178 (related issues #445 and #450). Applying this potential fix to 1.15.2.

**Comment by McKitten** [comment]
Any luck with a 14.4 fix? I actually had looted purifying powder burning when this mess happened https://pastebin.com/nzHfAJY3

**Comment by SilentChaos512** [comment]
Yeah, I'll backport the changes when I get the time. Wish someone would confirm if this has been fixed in 1.15.2.

**Comment by McKitten** [comment]
I've been in SP for 1.15.2 for at least 1 month of in game time now and have noticed a trend of the chaos slimes actively avoiding slime chunks unlike the MP home in my pack. This may or may not be the difference, but then it could be the fact that it is SP not MP.
I would guestimate you have about 50k copies downloaded of the 1.15.2, and no complaints yet so.. call it?
