### ISSUE TITLE
Something went wrong with chaos buff loading! This may be caused by another broken mod, even those not related to Silent's Gems.

### ISSUE THREAD

**Issue by Gamerbolts** [SilentChaos512/SilentGems#441]
## Versions

- **Silent's Gems**: 3.4.7+80
- **Silent Gear**: 1.4.6+72
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.111
- **Modpack**: [PXC Network Modpack](https://www.curseforge.com/minecraft/modpacks/pxc-network-modpack)

## Expected Behavior

- Chaos Buffs to work

## Actual Behavior

- Get the above error saying it's caused by another broken mod

## Links/Images

- [latest.log](https://github.com/SilentChaos512/SilentGems/files/4129905/latest.log)

## Steps to Reproduce the Problem

1. Install my modpack
2. Run on server
3. It doesn't seem to happen at first, it happens when I am on the server then close down the modpack and the server and reload both. When I connect I get this message at start.

Any help is appreciated. Doesn't crash the server but doesn't allow me to enjoy the fullness of your mods. Thank you

**Comment by SilentChaos512** [comment]
Search the log for "Failed to reload data packs". The error after that
should be the cause. At work right now, can't seem to open it from my phone.

Also, note to self: fix the issue template version formatting.

**Comment by Gamerbolts** [comment]
Ah BluePower, would never have been able to guess that one. Looks like their Alloy Furnace Recipe.

Thanks so much
