### ISSUE TITLE
Massive lagspikes from Chaoshandler

### ISSUE THREAD

**Issue by Darkere** [SilentChaos512/SilentGems#445]
## Versions

- **Silent's Gems**: SilentLib-1.15.2-4.6.0+48.jar
- **Silent Lib**: SilentLib-1.15.2-4.6.0+48.jar
- **Forge**: forge-30.0.43
- **Modpack**: [Randomly Added Mods v1.9](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods/files/2875478)

We've updated our server and added silent gems in the update. We are getting some massive lag spikes. 

I've run some profiling that excludes ticks that are finished before 1 second passes and this is the result: https://sparkprofiler.github.io/#jkKxYA5iVq

**Comment by SilentChaos512** [comment]
Possibly the same issue as #440. I have no idea how this is happening, I've
never encountered anything like it.

**Comment by Partonetrain** [comment]
I was able to fix this by disabling Chaos Slime spawning in 1.14, hope that helps and narrows down the issue

**Comment by SilentChaos512** [comment]
It does seem to be tied to the slime and wisp events. I think the function
that hangs is one for getting a chunk from the world. Not sure why it only
happens in some cases. Might be worth comparing mod lists in affected
instances.

**Comment by Exarchai** [comment]
Getting same issue. Friend couldn't even connect to my server (kept getting timed out/disconnected errors), until I disabled the chaos slime spawns. It seemed that they kept trying to spawn every time he tried logging in.

I'm not 100% sure, but it might be infernal mobs conflicting. I remember seeing a lot of log spam relating to infernal mobs before he crashed

**Comment by Bricktricker** [comment]
I think I found out what causes the lagspikes.
Here: https://github.com/SilentChaos512/SilentGems/blob/eb445e0e30b5e7f10c95cfaaba84a823b49f913a/src/main/java/net/silentchaos512/gems/world/spawner/CorruptedSlimeSpawner.java#L57
you are calling `world#getChunk` with a BlockPos, but getChunk expects a ChunkPos. This causes the server to load a chunk far away, wich causes the lagspikes.
A solution would be to use `world.getChunkAt(new BlockPos(posX, 0, posZ))` to get the right chunk.
