### ISSUE TITLE
1.15.2 - Return Home Charm crashing upon use

### ISSUE THREAD

**Issue by BarylRolls** [SilentChaos512/SilentGems#447]
Attempted to use the return home charm on a bound teleport anchor while still within sight of it to test it out and the server crashes. 
[crash-2020-02-07_23.47.52-server.txt](https://github.com/SilentChaos512/SilentGems/files/4173793/crash-2020-02-07_23.47.52-server.txt)

**Comment by SilentChaos512** [comment]
Apparently `BlockState#causesSuffocation` is marked client-only now, weird. Will look for a replacement tomorrow.

Also should have used the bug report template, FYI.

**Comment by BarylRolls** [comment]
Sorry, my first time using github ^^; I'll look for it next time. Great mod though
