### ISSUE TITLE
1.14+ - Config to disable Gem generation entirely per-dimension

### ISSUE THREAD

**Issue by Partonetrain** [SilentChaos512/SilentGems#448]
## What Should Be Added or Changed?
As of right now there is no way to disable gem generation entirely, nor any option to disable Geodes. Setting regionSize on of the three dimensions to 0 does nothing and resets the config to its default.

`[world.generation.nether.gems]
				#The region size for gems in the Nether.
				#Each 'size x size' chunk area is a 'region', which contains a couple types of gems.
				#Larger regions will make finding many types of gems more difficult.
				regionSize = 0
`
This is invalid and gets reset

## Why Should This Be Done?
Modpack customization.

**Comment by SilentChaos512** [comment]
Added the configs in 1.15.2, will backport them later.
