### ISSUE TITLE
Flight Chaos Gem Not Working

### ISSUE THREAD

**Issue by preflora** [SilentChaos512/SilentGems#449]
Apologies if this is the incorrect place to ask about this, my friends and I made a custom modpack based on crackpack 3 and added silent gems. I made a Chaos Gem with flight, recharge, and capacity and charged it on the altar. After turning it "on" I tried flying and it doesn't work, nothing happens. I also tried it in a singleplayer world with the same modpack and it didn't work there either. Is there some kind of setting or config we are missing?

**Comment by SilentChaos512** [comment]
You should include more information in the future, but I assume you are on
1.12.2 if flight runes exist. This is probably a mod conflict. Try removing
mods until you find the problem.
