### ISSUE TITLE
fake players crash my game how to get rid of???

### ISSUE THREAD

**Issue by semytruck** [SilentChaos512/SilentGems#452]
when i was adventuring the fake players gave me xp and thats alright but there was so many fake player that it crashed and blocks i placed started disappearing

**Comment by SilentChaos512** [comment]
You need to include version information, as well as a crash report. A
better description would also help. Not sure what fake players you mean, I
don't recall this mod using any.

**Comment by semytruck** [comment]
Sorry for not including them but I'm in the 1.12.2 version and I can't include the crash report cuz I'm away from my pc but as for the fake players it's the glowing flying thing that repairs your tools that have soul powers if you can't fix it I completely understand its just really annoying having a laggy game whilst trying to explore some places thanks in advance

**Comment by semytruck** [comment]
![2020-04-08_13 31 18](https://user-images.githubusercontent.com/62752230/78784471-4d2f6700-799d-11ea-87f3-e6ca2410fe67.png) and sorry about the crash thing its more of if i try to place a block it disperses into blocky air and hopefully this could be removed like maybe in the files or something cuz i want to play minecraft but i cant travel without it lagging like a mac trying to run fifa 2020 -semytruck as you can tell
