### ISSUE TITLE
Yellow Diamond Armor Bug

### ISSUE THREAD

**Issue by Ikermp11** [SilentChaos512/SilentGems#454]
## Versions

- **Silent Gear**: 1.15.2
- **Silent's Gems**: 1.15.2 
- **Silent Lib**: 1.15.2
- **Forge**: 1.15.2
- **Optifine Installed**: No

It should appear the armor as you would see a normal armor when equipped. But it appears red and black large blocks. The textures of the armor can't be seen.

**Comment by SilentChaos512** [comment]
Looks like there are some bigger problems with armor rendering in general. In addition to some of the textures in Gems not having been renamed, it seems the usual coloring is applied on top of that. So the textures look "flatter" than they should.

**Comment by Ikermp11** [comment]
When would this be fixed? Just to know.

**Comment by SilentChaos512** [comment]
Trying to fix it today.

**Comment by Ikermp11** [comment]
Thanks!

**Comment by SilentChaos512** [comment]
Curse is taking a while to approve files, so not sure when they will be up. But make sure the update both Silent's Gems and Silent Gear.
