### ISSUE TITLE
Internal Server Shutdown

### ISSUE THREAD

**Issue by DeropManz** [SilentChaos512/SilentGems#455]
## Versions

- **Silent's Gems**: SilentsGems-1.12.2-2.8.22+327
- **Silent Gear**: x.x.x 
- **Silent Lib**: SilentLib-1.12.2-3.0.13+167
- **Forge**: 1.12.2 - 14.23.5.2847
- **Modpack**: Custom
- **Optifine Installed**: Yes 

## Expected Behavior
 For the game not to crash and run normally.

## Actual Behavior

The game randomly says "Internal Server Shutting Down" after at least 10 minutes of gameplay and after many times of this happening it crashes. Vanilla Fix believes its Silent Gems.

## Links/Images

- (Link)
- (Another link, if needed)
   
Mods Used (https://user-images.githubusercontent.com/56196394/79696027-23512c80-8248-11ea-9ae1-9fa92a9366c3.png)

Crash Report [crash-2020-04-19_13.31.43-server.txt](https://github.com/SilentChaos512/SilentGems/files/4499904/crash-2020-04-19_13.31.43-server.txt)

## Steps to Reproduce the Problem

 It happens at random

**Comment by SilentChaos512** [comment]
Crash report doesn't contain much info. Could I get a full log file please?

**Comment by DeropManz** [comment]
Do you mean this?
[latest.log](https://github.com/SilentChaos512/SilentGems/files/4500092/latest.log

**Comment by SilentChaos512** [comment]
Seems like you are using 2.8.18, even though the name of the file says 2.8.22. Try redownloading the mod to make sure you have the latest version.

**Comment by DeropManz** [comment]
It said only Silentlib was outdated if it crashes again I'll give you an update if not I'll close the issue but either way thanks for your help.
