### ISSUE TITLE
Random Chaos Events create excessive world generation

### ISSUE THREAD

**Issue by CharZinta** [SilentChaos512/SilentGems#456]
## Versions

- SilentGems-1.15.2-3.5.1+84
- **Silent Gear N/A
- *SilentLib-1.15.2-4.6.0+48
-  forge-1.15.2-31.1.19 
- SeaTech
- Minecraft & Forge only with above 2 listed mods tested as well
- **Optifine Installed**:  No

## Expected Behavior

(Description here)

## Actual Behavior
When the pack is running in server mode, or as stated above we tested on a base minecraft and forge install with just two mods, and a player is logged you get random world generation.  We have see region files as far out as 30,000+ distance each time a chaos event happens.

(Description here)

## Links/Images

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1.  Setup vanilla server with Forge
2.  Add silentLib and Silent Gems
3. let a player logon, walk around and then wait. Increase is random but happens frequently enough you should get 10 or more new regions in less than 24hrs.

**Comment by SilentChaos512** [comment]
This may have been fixed by version 3.5.3 (commit 97ede0f5be29f502dfc0ca55c040d1f20f733178). Try updating and try again. Include a log file if the problem continues.

**Comment by CharZinta** [comment]
Thank you. Consider this closed, if you wish, until I work with the Pack author to make the change or take over the pack myself and do so.
