### ISSUE TITLE
[1.9.4] Crash on server startup

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/SilentGems#46]
Description:  Dedicated server crash on startup, fixes when I revert to older versions of Silent Gems.
[Crash Report](https://gist.github.com/dirtyfargo/d7ae590d439dc5bee187ca544c01a746)
Version: 2.0.16-41
Lib: 1.0.10-17
Forge: 12.17.0.1963

**Comment by SilentChaos512** [comment]
As a temporary workaround, try using: Silent's Gems 2.0.16-41 and Silent Lib 1.0.9-16.

**Comment by dirtyfargo** [comment]
Yup that seems to work for now thx :)

**Comment by SilentChaos512** [comment]
OK, I'm going to upload a new version of Silent Lib that will fix this issue. It should be functionally identical to 1.0.9-16, so you don't NEED to update right now. Whatever works for you.
Switching to client-side localization has been surprisingly painful, but it shouldn't cause any more trouble for now.
