### ISSUE TITLE
Problem with SpongeForge mod

### ISSUE THREAD

**Issue by xdPrzemo** [SilentChaos512/SilentGems#460]
## Versions

- **Silent's Gems**: 1.12.2-2.8.22+327
- **Silent Gear**: N/A
- **Silent Lib**: 1.12.2-3.0.14+168
- **Forge**: 1.12.2-14.23.5.2847
- **Modpack**: N/A 
- **Optifine Installed**: Yes but this is server problem not client

## Expected Behavior
Fix bug.

## Actual Behavior
After installing SpongeForge mod on my server armor from silent gems are not breaking self.

## Links/Images
https://drive.google.com/file/d/1ez69IsGv-u-Lu7eaJ1Elbj_VMzku3-Lp/view?usp=sharing
https://www.spongepowered.org/

## Steps to Reproduce the Problem

1. 
2. 
3.

**Comment by SilentChaos512** [comment]
Says I don't have permission to access the file. I recommend uploading to gist.github.com, pastebin, or any similar site.

**Comment by xdPrzemo** [comment]
> Says I don't have permission to access the file. I recommend uploading to gist.github.com, pastebin, or any similar site.



> Says I don't have permission to access the file. I recommend uploading to gist.github.com, pastebin, or any similar site.

Hi you try again.
I opened this film to all.

**Comment by xdPrzemo** [comment]
Hi Silent working now?

**Comment by SilentChaos512** [comment]
I was hoping for a log file, but probably nothing I can do about this anyway. Looks like an issue that Sponge would need to fix.
