### ISSUE TITLE
Digital Miner from Mekanism mines Nether- and Endores in the Overworld

### ISSUE THREAD

**Issue by cyberpunkbln** [SilentChaos512/SilentGems#461]
## Versions

- **Silent's Gems**: SilentGems-1.15.2-3.5.3+86
- **Silent Gear**: SilentGear-1.15.2-1.6.4+90
- **Silent Lib**: SilentLib-1.15.2-4.6.1+49
- **Forge**: forge-1.15.2-31.2.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
That the Digital Miner only mines Overworld-Ores from SilentGems.

## Actual Behavior
When i put my Digital Miner around the World on some spots the Digital Miner mines GemOre from the Nether and End, Hardened Endstone as an example. In the last tests only SilentGem-Ores and Hardened Endstone from the End.

I choose the Filter -> Mod-Selection -> silentgems

## Question:
Can it be that some Nether and End-Blocks spawn in the Overworld? Or is this a bug?

thx

**Comment by SilentChaos512** [comment]
The dark and light gems do spawn in the overworld in small quantities, in gem "geodes" surrounded by hardened netherrack/end stone.

**Comment by cyberpunkbln** [comment]
Ah thank you, good to read,
thx
