### ISSUE TITLE
Silent's Gems 3 (silentgems) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by JakeMoe** [SilentChaos512/SilentGems#463]
## Versions

- **Silent's Gems**: 1.15.2-3.5.3+86
- **Silent Gear**: 1.15.2-1.7.2+96
- **Silent Lib**: 1.15.2-4.6.1+49
- **Forge**: 31.2.8
- **Modpack**: I'm still developing it, not on CurseForge yet
- **Optifine Installed**: No

## Expected Behavior
Game to load to main menu

## Actual Behavior
During mod loading and startup, I get the message in the title underneath red text "Error loading mods - 1 error has occurred during loading".  Only buttons available are "Open Mods Folder" and "Open latest.log"

Error seems to start at line 186 in the latest.log linked below.

## Links/Images
https://gist.github.com/JakeMoe/52f92b8a3e693dd16cf29a04f1c71f74

## Steps to Reproduce the Problem

1. Start modpack (currently 57 mods, including Silent Lib, Gems, Gear, and Mechanisms)
2. Wait for loading to complete and error to appear

**Comment by SilentChaos512** [comment]
You must update Gems to 3.5.4 if you are using Silent Gear 1.7+.
