### ISSUE TITLE
Gear Soul Items gain no experience

### ISSUE THREAD

**Issue by dacsinu** [SilentChaos512/SilentGems#469]
I've been fighting with a machete I added a gear soul to and I get no experience on the weapon. i tried the same with my bow and the same thing occurs. I kill mobs, and no experience gets added. Is there something I am missing about the mechanic?

**Comment by trollsdottir** [comment]
In silentgems-common.toml (1.15.2 version at least) the first config option is:

[gearSoul]
	#If true, gear souls can gain XP when being used by fake players (certain machines)
	fakePlayersGetXp = false

have you tried changing that?
