### ISSUE TITLE
Pile of Corrupted don't drop from the block

### ISSUE THREAD

**Issue by ExoFrece** [SilentChaos512/SilentGems#477]
SilentGems-1.15.2-3.5.8+91
SilentGear-1.15.2-1.9.6+130
SilentLib-1.15.2-4.6.6+59
Forge 31.2.5

## Expected Behavior
Pile of Corrupted Stone/Dirt from Corrupted Stone/Dirt right? 

## Actual Behavior
it don't drop his pile

**Comment by SilentChaos512** [comment]
Yes, seems I made a mistake when moving to data generators. Should be dropping 4 piles instead of itself.
