### ISSUE TITLE
1.16 Crash on launch

### ISSUE THREAD

**Issue by Tyrius1** [SilentChaos512/SilentGems#480]
## Versions
Minecraft 1.16

SilentGems-1.16.1-3.6.0+94
SilentGear-1.16.1-1.10.0+133
SilentLib-1.16.1-4.7.0+58
forge-32.0.71

Game crashing on launch

https://pastebin.com/a5PUV7MU

**Comment by SilentChaos512** [comment]
Check your log file. Color handler crashes usually indicated some other crash earlier in the loading process, probably another mod.
