### ISSUE TITLE
[1.16.1] Crash on startup when Silent Gear is not installed

### ISSUE THREAD

**Issue by TheLMiffy1111** [SilentChaos512/SilentGems#481]
## Versions
- **Silent's Gems**: 3.6.0+94
- **Silent Gear**: N/A
- **Silent Lib**: 4.7.0+58
- **Forge**: 32.0.70
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Added Silent's Gems to test JAOPCA in dev environment, should startup properly

## Actual Behavior
Crashes on startup when Silent Gear is not installed, as the mod adds default block items to the Silent Gear item group.

## Links/Images
- latest.log: https://pastebin.com/26uDmmia

**Comment by SilentChaos512** [comment]
I knew I would make a typo like that eventually...
