### ISSUE TITLE
[1.16.3] Disabling World Generation for Gems in the Overworld doesn't actually Disable them. (disabling anything doesn't work?)

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#484]
## Versions
- **Silent's Gems**: 3.6.1+96
- **Silent Gear**: 1.10.2+138
- **Silent Lib**: 4.7.0+58
- **Forge**: 32.0.75
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3
- **Optifine Installed**: No

## Expected Behavior
Overworld Gems being disabled like I disabled them in the config.

## Actual Behavior
Overworld Gems are disabled but they are still available in the Overworld.

## Steps to Reproduce the Problem
1. Install SilentGems + Lib.
2. Start game & Generate configs and disable Overworld Ore generation.
3. Restart Game.
4. Relaunch game & then Join / Create a World.
5. Check world, ores are still available. Even though config has them disabled.
6. Profit.

**Comment by bessiq** [comment]
Can confirm. Have max and min both set to zero. Using Forge 32.0.88 and same sgems version. Checked both modded and vanilla overworld biomes and gems are present.
`maxTypePerBiome = 0`
`minTypePerBiome = 0`

**Comment by SilentChaos512** [comment]
OK, seems the regional gems config for other dimensions is also applying to the overworld. As a temp workaround, try setting `world.generation.other.gems.regionSize` to 0 as well.

**Comment by bessiq** [comment]
Thanks for responding. I'll give that a shot. If it doesn't work out, I'm fine just having them in the overworld. I was thinking about locking them to a mining dimension, but the setting you mention would likely remove them there, too. Although, it allows adding pretty much any ore or block in its own config, sooo....time to test!

Anyway, thanks!

**Comment by Gbergz** [comment]
> OK, seems the regional gems config for other dimensions is also applying to the overworld. As a temp workaround, try setting `world.generation.other.gems.regionSize` to 0 as well.

Yes that seem to have worked, but for me this won't fix for what I'm trying to do unfortunately. I'll wait for a "real" fix. Thanks though! :)

**Comment by bessiq** [comment]
Another fun fact I learned from this, and it makes sense now that I realize it: setting overworld gems' min/max to zero also disables glowrose generation, as they seem to be indicators for the gem type(s) in that region. E.g. I found some Tanzanite Glowroses and found Tanzanite ore close by. TIL lol

**Comment by Gbergz** [comment]
Still an issue on **1.16.3**, using this version: [SilentGems-1.16.3-3.7.0+103](https://www.curseforge.com/minecraft/mc-mods/silents-gems/files/3072113)
**Forge:** 34.1.19

Any updates on if this can get fixed?
**-** Gbergz

**Edit:** Also while I'm here, any silentgems ore can be broken with hand and the gem will drop. No pickaxe required. Harvest Levels seem broken. 
GIF showing it: https://gyazo.com/4a4641fb73b79b0eccedba8a9dca65c9

**Comment by Gbergz** [comment]
Any updates on this? Ores are still present in overworld even though they're disabled.
![image](https://user-images.githubusercontent.com/26634554/96178292-77a34380-0f2f-11eb-8300-d3b64f71bec3.png)

**SilentGems**: [SilentGems-1.16.3-3.7.1+104.jar](https://www.curseforge.com/minecraft/mc-mods/silents-gems/files/3077986)
**Forge:** 34.1.19

**Comment by SilentChaos512** [comment]
Just to clarify, you want no gems in the overworld, but you do want them in other dimensions (like mining worlds), right?

**Comment by Gbergz** [comment]
> Just to clarify, you want no gems in the overworld, but you do want them in other dimensions (like mining worlds), right?

Yes, exactly. The plan was to disable the overworld silentgems-ores and only have them enabled in a Mining Dimension.
Which was possible in 1.15.

**Comment by SilentChaos512** [comment]
OK, I'll take another look today. I also need to work out some other worldgen issues thanks to changes in 1.16.3. The config options might end up completely changed, FYI.

**Comment by Gbergz** [comment]
Gotcha, thanks for the answers!

**Comment by SilentChaos512** [comment]
Mostly done with rewriting all the world gen. Just need some time to clean up the configs and make sure they actually work as intended.

**Comment by Gbergz** [comment]
Sweet! Thanks for the update on things

**Comment by SilentChaos512** [comment]
Should be fixed in 3.7.2

**Comment by Gbergz** [comment]
Seems fixed! Thank you so much. 👍
