### ISSUE TITLE
Potential lag issues.

### ISSUE THREAD

**Issue by Raycoms** [SilentChaos512/SilentGems#487]
## Versions

![image](https://user-images.githubusercontent.com/6438347/88489675-9e378b00-cf8d-11ea-9038-04dda82eef4c.png)

- **Forge**: 31.2.30
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack
- **Optifine Installed**: Yes

## Expected Behavior
No lag

## Actual Behavior
Lag

I've been profiling our server for a while and I believe there is a bunch of lag related to player movement and messaging coming from silent gems.

Those were the ones that were really sticking out. But a tool mod should definitely not take up to five percent of the total tick time. An entity mod I'd except up to five percent.

I believe comparisons for these things are done every tick which puts a significant strain on the server.

https://cdn.discordapp.com/attachments/495698685334650903/737054493388308480/unknown.png
https://cdn.discordapp.com/attachments/495698685334650903/737054596517593169/unknown.png
https://cdn.discordapp.com/attachments/495698685334650903/737054725178130543/unknown.png

https://spark.lucko.me/#qORJSepivs

**Comment by Raycoms** [comment]
I guess this should be moved to SilentGear

**Comment by SilentChaos512** [comment]
Looks like gear souls are the main issue there. Should be safe to cut their update ticks to once a second or less.
