### ISSUE TITLE
[Compatability] Lucky Cases

### ISSUE THREAD

**Issue by APolarBaer** [SilentChaos512/SilentGems#49]
i havent tried with the new version yet because im waiting on another mod for the same issue as this but i crashed from opening a case and it points to Silent's Gems but it didnt before you added the armor so maybe its that? anyways heres the log 

http://pastebin.com/qR18TzgD

Kloonder told me 
"Tell the author from silets gems, is is crashiing because of an issue where a item can't be rendered if it has no initial NBT tag, so he should add a case to his rendering system, where an item can be rendered without an NBT tag"

link to the lucky cases issue i posted:
http://minecraft.curseforge.com/projects/lucky-cases/issues/5

if this is something thats a non issue that fine, i love the work you've done on this mod keep it up :D

**Comment by SilentChaos512** [comment]
I should definitely fix that crash. Tools are robust enough to not crash when they have no data (they're unusable however).

I think I'll make a suggestion to the author of Lucky Cases while I'm at it. They should be able to make the cases give basic gem tools and armor with a small change, if they want to.

**Comment by SilentChaos512** [comment]
Issue created on Lucky Cases issue tracker, suggesting a change for better mod compatibility: http://minecraft.curseforge.com/projects/lucky-cases/issues/6.

**Comment by APolarBaer** [comment]
crashed after re adding lucky cases, points to silent gems still :/ 

http://pastebin.com/tAteKrXZ

**Comment by SilentChaos512** [comment]
I haven't uploaded the fix yet, it should be up in a few minutes.

**Comment by APolarBaer** [comment]
oh, my apologies xD

**Comment by SilentChaos512** [comment]
No problem, just keep an eye out for version 2.0.21-50 :)
