### ISSUE TITLE
[1.15.2] Soul Urns randomly disappearing when broken

### ISSUE THREAD

**Issue by L-Aleixo** [SilentChaos512/SilentGems#492]
## Versions

- **Silent's Gems**: 3.5.5+88
- **Silent Gear**: 1.8.2+109 
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.24
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior

When you break a Soul Urn it should be dropped in the ground so you can pick it up in order to use it again.

## Actual Behavior

It has happened two times already in the server I play at, once with a friend of mine and once with me:
The soul urn is working fine until it eventually does not drop when we break it with our pickaxes, so we simply lose the urn with everything inside of it... As simple as that.
It may be latency-related, I don't know. But it's quite annoying.

## Links/Images

N/A

## Steps to Reproduce the Problem

This issue seems to be random. Both me and my friend didn't do anything unusual with the urns for it to happen. In both times we were in the overworld, there was free space in our inventories and there was nothing nearby that could have "catched" them before us. But it happened to my friend about an hour after he started using the urns, while for me it took over a real life day to happen... So:

1. Play on a server (since it may be latancy-related);
2. Use the urns until the issue happens.

**Comment by SilentChaos512** [comment]
Will need a log file for this, one where the issue has occurred.
