### ISSUE TITLE
Server crashes due to "chaos ore"

### ISSUE THREAD

**Issue by SaltyShorts** [SilentChaos512/SilentGems#493]
## Versions

- **Silent's Gems**: 3.6.2
- **Silent Gear**: 2.0.9 
- **Silent Lib**: 4.7.0
- **Forge**: 1.0.8
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Server runs smoothly

## Actual Behavior

Server crashes randomly

## Links/Images

https://pastebin.com/ypuqi1uH

## Steps to Reproduce the Problem

Currently not known

**Comment by SilentChaos512** [comment]
You need to provide a crash report.

**Comment by SaltyShorts** [comment]
My bad added it now

**Comment by SilentChaos512** [comment]
Looks like an Optifine crash

**Comment by RemagOfficial** [comment]
if the server is crashing because of OF thats weird because OF is client-side only

**Comment by SilentChaos512** [comment]
Yeah, that is weird. But the crash report provided shows Optifine in the mods list, and it looks like a typical Optfine screw-up.

**Comment by RemagOfficial** [comment]
@SaltyShorts then if you have OF in the **server** mod folder remove it and get back to us with the result

**Comment by SaltyShorts** [comment]
removed OF from the server mod folder and the same issue is happening again

**Comment by SaltyShorts** [comment]
Seems like the problem happens when you add a mod and remove it again. Seems like a forge error as the same thing is happening with another mod which i removed from the server
