### ISSUE TITLE
Gear Souls cannot be equipped to armor

### ISSUE THREAD

**Issue by AlmightyBacon** [SilentChaos512/SilentGems#496]
## Versions

- **Silent's Gems**: 3.6.3+100
- **Silent Gear**: 2.1.1+162
- **Silent Lib**: 4.7.1+59
- **Forge**: 32.0.108
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

Expected Gear Soul to attach to Armor piece (leggings and chest tested). 

## Actual Behavior

Recipe Does not function. Also, JEI doesn't show any recipes involving Gear Souls. Tools and weapons work as intended though.

## Steps to Reproduce the Problem

1.  Craft a piece of Silent Armor
2.  Craft a Silent Gear Soul
3.  Attempt to craft gear soul to armor

**Comment by SilentChaos512** [comment]
Fixed by Silent Gear 2.3.2
