### ISSUE TITLE
1.16.3 cannot load world with How Fortunate and Silent Gems installed

### ISSUE THREAD

**Issue by Blntswrd** [SilentChaos512/SilentGems#498]
## Versions

- **Silent's Gems**: 1.16.3-3.7.0+103
- **Silent Gear**: 1.16.3-2.2.0+164 
- **Silent Lib**: 1.16.3-4.8.1+61
- **Forge**: 34.1.5
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

The world to load

## Actual Behavior

When trying to load into the world it would stop and tell me there is an error in data packs and ask me to load in safe mode or go back to main menu.

This also happens in other versions of Minecraft.

## Links/Images

Debug: https://pastebin.com/gqZePX52
Latest: https://pastebin.com/0tVbRDAU

## Steps to Reproduce the Problem

1. Install both mods
2. Launch world

**Comment by SilentChaos512** [comment]
Need a log file. Will close the issue if not provided.

**Comment by Blntswrd** [comment]
Debug: https://pastebin.com/gqZePX52
Latest: https://pastebin.com/0tVbRDAU

**Comment by SilentChaos512** [comment]
Looks like Fortunate is at fault here. Is there something that leads you to believe this is a Silent's Gems issue?

**Comment by Blntswrd** [comment]
I wasn't sure which one it was, it happens with Silent Gems and Silent Mechanism but I haven't seen it happen with any other mod so I posted it both here and on How Fortunate just to be safe.
