### ISSUE TITLE
Crash when try to craft a tool with a bone and a stick toolrod.

### ISSUE THREAD

**Issue by MiagoMeowsome** [SilentChaos512/SilentGems#50]
Everything is in the title !
When trying to craft a tool with a stick and a bone the game crash because it fails to render the item.

[Crash log](http://puu.sh/pL0Mr/71b8497397.txt)

**Comment by SilentChaos512** [comment]
Huh. I thought I tested that case... By the way, you're not able to mix rods types. They're supposed to match.

**Comment by MiagoMeowsome** [comment]
Yeah i supposed it was the case, i just wanted to try.
Thank you for taking care of it so fast ! :)
