### ISSUE TITLE
[1.16.3] Silent Gems (and other silent mods) are not registering their ConfiguredFeatures

### ISSUE THREAD

**Issue by TelepathicGrunt** [SilentChaos512/SilentGems#500]
Hello! Me and others had found with various mods that sometimes, mod's stuff will not spawn at all when pairs with certain mods. Upon investigating, it turns out to be due to how biome's codecs are parsed and when they have both registered and unregistered ConfiguredFeatures in the same generation stage. It's pretty complicated to explain the full effects of this but simply, ConfiguredFeatures should be registered to maximize mod compatibility and not break other mods.

![unknown1](https://user-images.githubusercontent.com/40846040/95244251-b6beef80-07df-11eb-972b-a7e468aaa0a7.png)

So this ties to silent mods because I made a mod called Blame that will detect these unregistered ConfiguredFeatures and print their JSON out so I can see which mods are not registering their stuff. I tried Blame on TownCraft and found that most of the unregistered stuff came from the silent mods. The log is too big to host on pastebin so I included it below
[latest.log](https://github.com/SilentChaos512/SilentGems/files/5335864/latest.log)

silentgems, silentgear, and silents_mechanisms are all present in the log showing their configuredfeatures are not registered. If you need an example of how to register them, basically do the feature.configure().placement()... and store the configuredfeature somewhere like a static variable. Then you can grab the configuredfeature registry from vanilla (there's no forge registry for this) and register the configuredfeature to there and add your configuredfeature to biomes! You can do the registering at anytime before as world is selected so even FMLCommonSetupEvent should be fine (I register mine in the Feature registry event after I register the base Feature)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/10241e85e317d24f1b9c47cd3134b1f84f01f293/src/main/java/com/telepathicgrunt/repurposedstructures/RSConfiguredFeatures.java#L191-L192

I hope this helps!

**Comment by SilentChaos512** [comment]
Should be fixed in all 3 mods now

**Comment by TelepathicGrunt** [comment]
I just tried Blame with a bunch of mods on and it found that silentgems:wild_fluffy_puff_plant configuredfeature is not registered. I can make a new issue report if you want me to. let me know if you need any help with registering stuff and I'll help out when I got time!

**Comment by SilentChaos512** [comment]
Yeah, seems I did miss that. With so many of them I'm not surprised. I'll just reopen this one.
