### ISSUE TITLE
[1.16.3] Ores spawn in solid columns

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#502]
## Versions

Silent's Gems: SilentGems-1.16.3-3.7.0+103
Silent Gear: SilentGear-1.16.3-2.3.0+165
Silent Lib: SilentLib-1.16.3-4.8.1+61
Forge: forge-1.16.3-34.1.17
Modpack:https://www.curseforge.com/minecraft/modpacks/towncraft/
Optifine Installed: No

## Expected Behavior

Ores be spread out.

## Actual Behavior

Note, I have not tested with only siltengems, this is on our dedicated server testing of TownCraft TWO, so it very well could be a mod interaction.

## Links/Images

![2020-10-11_19 50 21](https://user-images.githubusercontent.com/4427684/95697219-32170b80-0bfb-11eb-8e2d-43ce165a7b28.png)
![2020-10-11_19 44 53](https://user-images.githubusercontent.com/4427684/95697226-36dbbf80-0bfb-11eb-8793-73c22e36700f.png)
![2020-10-11_19 45 06](https://user-images.githubusercontent.com/4427684/95697228-37745600-0bfb-11eb-9ecb-a9cbd3070ae1.png)

**Comment by SilentChaos512** [comment]
Fixed in all 3 mods
