### ISSUE TITLE
[1.16.1] Return Home Charm & Teleporters Crash Server 

### ISSUE THREAD

**Issue by lulabyte** [SilentChaos512/SilentGems#506]
## Versions

- **Silent's Gems**: 1.16.1
- **Silent Gear**: 1.16.1
- **Silent Lib**: 1.16.1
- **Forge**: 1.16.1
- **Optifine Installed**: Yes

## Expected Behavior

When I use the amulet on the teleporter, they should link so I can teleport home with the amulet.

## Actual Behavior
When applying the amulet to the teleporter, the server crashes and restarts.

## Links/Images
link to crash report: http://www.lulabyte.com/lindsey/crash-2020-10-19_05.50.22-server.txt

## Steps to Reproduce the Problem

1. Have a teleporter placed and the corresponding (or not?) return home charm.
2. Click the charm to the teleporter.
3. Crash and cry.

**Comment by CoruscareGames** [comment]
I would like to add to this; right clicking a teleporter in 1.16.1 crashes the server.

[crash-2020-10-21_13.36.28-server.txt](https://github.com/SilentChaos512/SilentGems/files/5413696/crash-2020-10-21_13.36.28-server.txt)
