### ISSUE TITLE
[1.16.3] The Fluffy Puff Invasion -- working as intended?

### ISSUE THREAD

**Issue by elowanut** [SilentChaos512/SilentGems#507]
- **Silent's Gems**: SilentGems-1.16.3-3.7.1+104
- **Silent Gear**: SilentGear-1.16.3-2.3.1+166
- **Silent Lib**: SilentLib-1.16.3-4.8.1+61
- **Forge**: 34.1.25
- **Optifine Installed**: No

I just wanted to check on the intended spawn rate of wild fluffy puffs in the Overworld. In previous versions, e.g. 1.16.1 and before, I felt like wild puffs were moderately rare, in the range of 1/10 chunks had one or two.

I recently finished updating everything to 1.16.3, and have discovered that puffs are literally everywhere! My last game spawned me in a Taiga biome that had dozens upon dozens of fluffy puffs, just everywhere. This seems to be the case in all the forest-type biomes -- I ran across one regular oak forest that had 4-8 puffs in nearly every chunk!

I thought at first maybe it was a strange interaction with one of the many other mods I use, like Biomes O' Plenty, or something else that heavily influences world gen, but the Plethora o' Puffs happens even with JUST Silent Gems/Gear/Mechanism loaded.

My question is whether this is working as intended, or if something has happened to the puff spawn rate?

**Comment by SilentChaos512** [comment]
Definitely could use some tweaking. My priority at the time was to just get something usable with the new world generation in 1.16.3.

**Comment by elowanut** [comment]
Makes sense, I know the new world generation threw a lot of stuff into disarray.

Before, finding a puff seemed like one of those (very minor) little Minecraft quests, like finding a pumpkin. Sometimes you have one right at spawn, sometimes you have to go searching. At the moment, they're more like "lemme clear out some of these puffs so I have space to build."

**Comment by SilentChaos512** [comment]
Just realized I haven't even uploaded the newest version (3.7.2), which has a world gen rewrite. It's possible I already fixed the placement rates, but I can't remember. I had to rewrite everything to fix some other issues.

**Comment by elowanut** [comment]
On 3.7.2, the generation rate is definitely toned down from 3.7.1. It is still significantly higher than it used to be, but is definitely back in the range of "design choice" rather than "bug!"

Personally, I preferred when it was rarer than it is  now, but it's at least reasonable. The vanilla "Forest" biome still has a larger-than-normal number of them, though.

On a world-gen related note, it's wonderful that the ore isn't spawning in corner columns anymore. Anecdotally, it feels like the gem ores are slightly rarer now. Hard for me to say, since I can't definitively state what the previous spawn rates were like. Any chance of a more granular config option for world gen of the gem ores? It would be nice to have some control over vein size / frequency, like we have with the metal ores.
