### ISSUE TITLE
[1.16.3] You can indefinitely upgrade tools with netherrite.

### ISSUE THREAD

**Issue by Ketrai** [SilentChaos512/SilentGems#508]
## Versions

- **Silent Gear**: SilentGear-1.16.3-2.3.0+165
- **Optifine Installed**: Yes

## Expected Behavior
To only be able to add one ingot.
Instead there is no limit on the amount of ingots you can apply

## Actual Behavior
you can add as many ingots as you like for more upgrades

## Steps to Reproduce the Problem

1. grab any type of silent tool/armor
2. grab a bunch of netherrite ingots.
3. grab a smithing table (vanilla) and add a netherrite ingot to the tool/armor
4. add more netherrite ingots this way, infinite upgrades!

On an unrelated note, you can't apply netherrite coatings to armor, only the smithing table works.

**Comment by SilentChaos512** [comment]
Already fixed in the latest version. Check the betas on Curse.
