### ISSUE TITLE
[1.16.4] Nether and End ores in Overworld

### ISSUE THREAD

**Issue by TwilightPSN** [SilentChaos512/SilentGems#510]
## Versions
- **Silent's Gems**: 3.7.3+106
- **Silent Gear**: 2.3.7+176
- **Silent Lib**: 4.9.0+63
- **Forge**: 35.0.16
- **Optifine Installed**: No 

## Expected Behavior

These should be generating in the end and nether not in the overworld

## Actual Behavior

nether and end stuff generating in overworld

## Links/Images
![2020-11-18_23 12 04](https://user-images.githubusercontent.com/37508557/99620653-ef173780-29f3-11eb-94f0-360b2f9319c8.png)
![2020-11-18_23 10 27](https://user-images.githubusercontent.com/37508557/99620655-efafce00-29f3-11eb-8d0f-5c6e3b11e0bb.png)

**Comment by SilentChaos512** [comment]
Those are geodes, not a bug. You can disable them in the config if you wish.
