### ISSUE TITLE
[1.16.4] Shovel with not durability causes crash

### ISSUE THREAD

**Issue by frakier** [SilentChaos512/SilentGems#518]
[crash-2020-12-27_17.04.04-client.txt](https://github.com/SilentChaos512/SilentGems/files/5745333/crash-2020-12-27_17.04.04-client.txt)
## Versions

- **Silent's Gems**: SilentGems-1.16.3-3.7.3+106.jar
- **Silent Gear**: SilentGear-1.16.3-2.4.8+195.jar
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63.jar
- **Forge**: forge-1.16.4-35.1.13
- **Modpack**: N/A 
- **Optifine Installed**: No 

- many other mods as well turned them all off and it worked. Will report back after turning the other mods on in batches.

## Expected Behavior

Shovel should not crash the game when durability is zero and you hit grass [the plant not a grass block].

## Actual Behavior

Shovel with zero durability crashes the client when you click grass [the plant not a grass block].

## Links/Images

If you want the crash report I can put it here or not at all. I don't use any of the above.
Standard crash log of about 47kb size.

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1. Get a wooden shovel
2. Use until it will not longer break grass, dirt, etc.
3. Click on some grass [the plant not a grass block].

**Comment by SilentChaos512** [comment]
Need a crash report or a log file. I don't care what site it's on as long as I can click a link and access it.

**Comment by frakier** [comment]
added one of the crash reports above, still going through disabling and re-enabling. to see if I can narrow down what is going on. Looking like mod interactions, still working on it. Will update and change title if necessary.

**Comment by SilentChaos512** [comment]
Looks like a COFH crash. None of my code is even in the stacktrace.

**Comment by frakier** [comment]
Just your shovel that is involved at the moment but I think I'm getting close to what is causing the issue.
I think another mod is breaking something, not sure why cofhcore is involved yet.

**Comment by frakier** [comment]
Ok out mod pack does not have regular shovels, added them in to try, same crash so taking your mod out now to. Just delete this. Sorry for the trouble. Should have though to check basic tools as well but with them being ripped out it never occurred to me.
If anyone else asks point them toward a cofhcore - pickletweaks issue. I'm going to file a report with one or both as I figure this out.
