### ISSUE TITLE
[1.15.2] mod references tags that don't exist

### ISSUE THREAD

**Issue by tlsctf2** [SilentChaos512/SilentGems#519]
## Versions

- **Silent's Gems**: 3.6.2+98
- **Silent Gear**: 1.11.4+187
- **Silent Lib**: 4.6.6+59
- **Forge**: 1.15.2-31.2.47
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Unsure on specifics.

## Actual Behavior
According to a team member on the Forge forums (diesieben07), the 1.15.2 build of this mod has invalid recipes that reference tags that don't exist and I was wondering if you could take a look into that. I've included the thread where I got this information from after I asked about world-generated chests being empty.

## Links/Images
https://forums.minecraftforge.net/topic/95696-1152-every-world-generated-chest-is-empty/

## Steps to Reproduce the Problem
Unsure of specifics.

**Comment by SilentChaos512** [comment]
I see one recipe from my mod in your log file. A single failed recipe is nothing that would completely break the data loading process like that. You're looking for another mod.
