### ISSUE TITLE
[1.16.4] Crash Upon Taking Damage

### ISSUE THREAD

**Issue by NatalaH** [SilentChaos512/SilentGems#520]
## Versions

- **Silent's Gems**: SilentGems-1.16.3-3.7.6+109
- **Silent Gear**: N/A
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: 1.16.4-forge-35.1.28
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

I expected there to be slight damage and the sound to accompany it when I jump off of something.

## Actual Behavior

Taking damage from falling (I did not test other sources) crashes the game. I hear the sound of the damage being taken, but not the affect. Upon re-logging in, the health bar starts to go down the appropriate amount. 

## Links/Images

https://pastebin.com/MvTLLXDL

## Steps to Reproduce the Problem

1. Make a world with SilentGems and SilentLib but not SilentGear,
2. Put on iron armor. (Possibly not necessary but as the log file referred to silent gear I did so to reproduce and make sure it happened with vanilla gear. It does.)
3. Jump off of something high enough to take damage.

I have long loved Silent Gems for its enchantment token system and soul urns, and the gems themselves. I prefer not to have SilentGear, but after seeing the crashlog I did note it seems to be looking for it and tested it with it as well. It does not crash with SilentGear installed. If this is an intended change I apologize for wasting time.

**Comment by SilentChaos512** [comment]
Definitely a bug. While Gems interacts a lot with Gear, it is meant to be able to run by itself.
