### ISSUE TITLE
Server Mod Load Failure

### ISSUE THREAD

**Issue by judicius** [SilentChaos512/SilentGems#525]
## Versions

- **Silent's Gems**: 3.7.8 +111
- **Silent Gear**: 2.5.1 +206
- **Silent Lib**: 4.9.0 +63
- **Forge**: 35.1.36
- **Modpack**: beta build not public yet (Builders Delight 2)
- **Optifine Installed**: No 

## Expected Behavior
Server start with updated Mod

## Actual Behavior
Server Crash, mod load failure

## Links/Images
https://gist.github.com/judicius/cbe61a85447fd04535030ff6ec938542

**Comment by SilentChaos512** [comment]
Log still shows version 3.7.7. Make sure the right file is on the server, or try redownloading it.

**Comment by judicius** [comment]
Deleted and reinstalled and you were right it worked.
