### ISSUE TITLE
Armor from supercharged items does not have supercharged stats

### ISSUE THREAD

**Issue by FluffyDiscord** [SilentChaos512/SilentGems#526]
## Versions
SilentGems-1.16.3-3.7.9+112
SilentGear-1.16.3-2.5.2+207
SilentLib-1.16.3-4.9.1+64

- **Forge**: 1.16.5, 36.0.1
- **Modpack**: Valhelsia 3 + few other mods
- **Optifine Installed**: Yes

## Expected Behavior
Crafted armor piece uses the supercharged stats which are shown on the "blueprint/template" thingy, before actually crafting the piece.

## Actual Behavior
Armor piece seems to revert back to the non supercharged state

## Links/Images
https://cdn.discordapp.com/attachments/474004116579024897/802656204651888640/2021-01-23_22.47.39.png
https://cdn.discordapp.com/attachments/474004116579024897/802656200960245780/2021-01-23_22.47.45.png

## Steps to Reproduce the Problem

1. super charge lvl 3 kyanite gem and azure ingots
2. craft boots plate from 2 and 2
3. now try crafting boots from the plate

**Comment by SilentChaos512** [comment]
Not sure what did it, but this seems to be fixed in newer versions of Silent Gear.
