### ISSUE TITLE
Impossible to disable glowroses

### ISSUE THREAD

**Issue by Chuunkyz** [SilentChaos512/SilentGems#536]
## Versions

- **Silent's Gems**: 3.7.14
- **Silent Lib**: 4.9.6
- **Forge**: 1.16.5, 36.1.4
- **Optifine Installed**: Yes 

I tried to disable the glowroses with the config but it seems like the config for the glowroses does nothing.

**Comment by SilentChaos512** [comment]
Added a new config option and removed the two existing ones. Neither of their default values made sense for the way world generation is currently handled.
