### ISSUE TITLE
Hand is displayed transparent

### ISSUE THREAD

**Issue by XxMiltenXx** [SilentChaos512/SilentGems#54]
Hello.
Whenever I use SilentGems, my hand is displayed transparent, as seen in the attachment.
Versions:
Minecraft: 1.10.2
Forge: 12.18.0.2008; 12.18.1.2011; 12.18.2015
SilentGems: SilentsGems-1.10.2-2.0.23-52
SilentLib: SilentLib-1.9.4-1.0.12-19, SilentLib-1.9.4-1.0.12-20
Java: 8u91 64-Bit
NVidia Driver: 368.69

As you can see, I already tried multiple versions. I am not using any other mods, a fresh MC installation. The error persists with or without Optifine (however, if you enable the "internal Shaders" in Optifine, the error is gone).
I also tried various ingame settings (VBOs on/off, Graphics on Fancy/Fast), but it's always transparent.

Either no one bothered to report the issue, or I am the only one having it.

![transhandsilentgems](https://cloud.githubusercontent.com/assets/13734214/17004060/6847f1b8-4ed3-11e6-9479-2f0246f4d019.png)

**Comment by SilentChaos512** [comment]
I've seen this myself, sporadically. Seems to occur less often with other mods installed, strangely enough. I've seen a similar bug with Psi before, maybe I can find some clues there.
