### ISSUE TITLE
silents-gems-1.17.1-4.1.0 Minecraft crashes during startup after world render phase

### ISSUE THREAD

**Issue by randallboggs** [SilentChaos512/SilentGems#545]
## Versions

- **Silent's Gems**: 4.1.0
- **Silent Gear**: 2.7.0 
- **Silent Lib**: 5.0.0
- **Forge**: 37.0.30
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior

(Description here)

## Actual Behavior

Game starts and allows world choice.  Choose existing or create new world.   World render starts and runs to 100%, then game crashes out with java exception.

Excerpt from log: "Caused by: java.lang.NoSuchFieldException: backgroundColor" 
I'm somewhere between noob and expert, but it looks like it might be as simple as adding a default field value named backgroundColor?  ...or maybe the field is there but the name is different?

## Links/Images

Crash log here: https://boggshouse.com/latest.log
- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1. Using CurseForge modloader
2. Create a custom modpack version 1.17.1 and include SilentGems
3. Try to load the game and enter a world

**Comment by SilentChaos512** [comment]
It has to do with how soul gems take their colors from spawn eggs. Not sure why it doesn't crash in dev, but I have an idea of how to fix it at least.

**Comment by randallboggs** [comment]
Cool.  Thanks for creating these mods.  My family and I really enjoy the content they bring to the game.

**Comment by SilentChaos512** [comment]
Fixed in version 4.1.2. Be sure to update Forge to 37.0.31 or higher too.
