### ISSUE TITLE
Items can't be removed from gem bag and flower basket

### ISSUE THREAD

**Issue by imagelesskink** [SilentChaos512/SilentGems#547]
## Versions

- **Silent's Gems**: 4.1.2
- **Silent Gear**: 2.7.2
- **Silent Lib**: 5.0.0
- **Forge**: 37.0.44
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
Ability to remove items from the gem bag & flower basket and to put glowroses in the flower basket

(Description here)

## Actual Behavior
None of the above

(Description here)

## Links/Images

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1. Get a gem bag/flower basket
2. Put something in
3. Now you can't get it out. Too bad!

**Comment by Syndaryl** [comment]
I can replicate this issue, I am also seeing some really... wacky GUI issues.

![image](https://user-images.githubusercontent.com/8820565/134188591-72dd725e-87f9-40c1-b804-963a515a954d.png)
