### ISSUE TITLE
Crafting will use any token not just blank

### ISSUE THREAD

**Issue by dabigmoose** [SilentChaos512/SilentGems#55]
Have been able to produce this many times. I was making 16 prot tokens for armor set. I shift clicked recipe and I had enough mats for 8 of them.  grabbed rest of mats and shift clicked again but instead of it using the 8 blank tokens it used the 8 prot tokens.  I tried this with a couple of other token recipes and it will work with them all.

**Comment by SilentChaos512** [comment]
So you are saying the recipes are accepting enchanted tokens where they should just be taking blanks? Hmm... Makes sense, the only thing that distinguishes them now is NBT. That's definitely not desirable behavior though. I'll see what I can do to fix this.

**Comment by dabigmoose** [comment]
Nope not desirable behavior at all. Thank you for taking a look at it.
