### ISSUE TITLE
Crash - not loading

### ISSUE THREAD

**Issue by AGkizlis** [SilentChaos512/SilentGems#559]
## Versions

- **Silent's Gems**: silents-gems-1.18.1-4.2.1.jar
- **Silent Gear**: silent-gear-1.18.2-2.10.1.jar
- **Silent Lib**: silent-lib-1.18.2-6.2.0.jar
- **Forge**: 40.1.0
- **Modpack**: N/A 
- **Optifine Installed**: No 

## Expected Behavior
I expect the client to start.

## Actual Behavior
The client crashes.

## Links/Images
- latest.log: [https://pastebin.com/g1NgNCci](https://pastebin.com/g1NgNCci)

## Steps to Reproduce the Problem
1. Use SKlauncher to install version 1.18.2
2. Install forge
3. Add only the three mods listed above (silent's lib, gear, gems)
4. Try to start the client. It crashes.

**Comment by SilentChaos512** [comment]
Most 1.18.1 mods fail to load on 1.18.2, unfortunately. I am working on an update as time allows.

**Comment by AGkizlis** [comment]
Thank you for your reply. Later on I figured the reason myself and thought of closing this issue, but hey, It's nice to see people interested enough to post issues, right? Thanks again.
