### ISSUE TITLE
[1.10.2] Something wrong with loot weights?

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#56]
Reported by Zygus42 via CurseForge:

> I was just testing (MC 1.10.2) and in chests in minecarts in an abandoned mine, every single cart had 6 or 7 of the new gem types in it (Indicolite, Moonstones, etc) - is this intentional ?  seems a very high rate and no setings in the config to cover it .

Check net.silentchaos512.loot.LootHandler for issues.

**Comment by Zygus42** [comment]
Have done more testing since, and this hasn't happened again - not sure why.  Bad RNG maybe ?
