### ISSUE TITLE
Crash with WTHIT.

### ISSUE THREAD

**Issue by int-72h** [SilentChaos512/SilentGems#565]
## Versions
- **Silent's Gems**: 3.7.16
- **Silent Gear**: 2.6.36
- **Silent Lib**: 4.10.0
- **Forge**: 36.2.34
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior
Tooltip appears.

(Description here)

## Actual Behavior
The game crashes.

## Links/Images
- (https://gist.github.com/int-72h/8a352c902fb93aad38afd3f09570bc79)
## Steps to Reproduce the Problem
I'm not exactly too sure how this happened, but it appears to be an issue with either WTHIT or silent gems.
1.  Look at a gem ore with WTHIT installed.
2.  Game crashes.

**Comment by SilentChaos512** [comment]
Your link is giving me a 404

**Comment by int-72h** [comment]
OK turns out it's an issue with WTHIT and it's due to me using an old version. Oops.
