### ISSUE TITLE
Wrong Invisibility effect

### ISSUE THREAD

**Issue by uhloin** [SilentChaos512/SilentGems#567]
Minecraft 1.19 Forge
silent-lib-1.19.2-7.0.3.jar
silent-gear-1.19.2-3.0.6.jar
silents-gems-1.19.2-4.4.0.jar

I created ring with Alexandrite with adorement "Cloacking". If I wear it then got "Invisibility" effect and also "Hunger II" effect alghough there is nothing about hunger in description. Moreover Hunger is working but Invisibility is not, mobs can see me and attack from usual distance.

**Comment by SilentChaos512** [comment]
The hunger effect is intended, so I'll add it to the description.
