### ISSUE TITLE
(Feature Request) Shields

### ISSUE THREAD

**Issue by Vaygrim** [SilentChaos512/SilentGems#57]
I'm developing a 1.10.2 pack, and right now it's got Tinkers' Construct as well as Silent Gems & Extra Parts. One of the ONLY reasons we have Tinkers' Construct in the test versions of the pack at present... is the BattleSigns. Vanilla's single 'iron shield' is lackluster at best, and marks an item category that desperately could be filled by wonderful mods like "Silent Gems".

Thoughts? Impressions? Bogart Impersonations?

**Comment by SilentChaos512** [comment]
I definitely want to add shields, it's something I've been thinking about since 1.9 came out. I'll take a look at the Battle Signs and see if that gives me any ideas for _how_ and _what_ to do.

**Comment by Vaygrim** [comment]
Epic! I realize these types of things take time, but even if you added just ONE shield to start with, I think it could be good. If you haven't actually experimented with (and USED) a Battle Sign as a shield in-game yet, I highly encourage that you do so. You can actually aim the projectiles coming at you, and bounce them BACK on your enemies!  (I think that's a vanilla shield thing)

**Comment by SilentChaos512** [comment]
I have something functional, just no rendering yet. Take a look when you have some time: https://minecraft.curseforge.com/projects/silents-gems/files/2323753.

**Comment by SilentChaos512** [comment]
Thoughts on what should determine a shield's blocking power? Currently using the 'protection' stat that armor uses, but I'm wondering if it should be a new stat instead.

**Comment by Vaygrim** [comment]
Okay! I have been tackling 'mystery bugs' in my modpack regarding performance / CPU issues, sorry i haven't had a chance to get back to you on this. (Congrats, your mod is in the clear by the way.)
I'm actually not quite sure how to balance this, as I don't know if the Vanilla / TiCon shield items even add protection when used.

I would say that the simple way to implement them from the start.. is to just use the protection system. Use what is already there, keep things simple. That's me tho.

**Comment by SilentChaos512** [comment]
I'll go ahead and close this issue for now. Shields are functioning, and I haven't had any bug reports. I do have a couple of enhancements I'm considering, but I'll work on those as I find the time.
