### ISSUE TITLE
1.12 (2.8.21) error when attempting to mine obsidian with a default or tipped pickaxe..?

### ISSUE THREAD

**Issue by sunlightspectre** [SilentChaos512/SilentGems#570]
Version: See above, 2.8.21 for Minecraft 1.12!

- **Silent's Gems**: 2.8.21
- **Silent Gear**: N/A
- **Silent Lib**: 3.0.13
- **Forge**: 14.23.5.2847
- **Modpack**: N/A 
- **Optifine Installed**: Yes

## Expected Behavior
In the past, when swinging a pickaxe at the purply ore that I am told is obsidian, I expect to get said obsidian. **This is using an obsidian-or-higher graded pick; and I have used both 'default' silent's picks and tip-upgraded picks.** I admittedly only play minecraft occasionally, but that is not what's happening at the moment!.. Instead...

## Actual Behavior
The **expected behaviour of using an obsidian-or-higher-graded pickaxe produces no obsidian on swing.** I will be able to mine it at a decent speed, though still too slow for my liking, but no obsidian pops out. I am sure since this issue is for a 'legacy' variant, there's no real time or interest in searching for it *but*, if you have an idea on what could cause that behaviour, I think I can probably slap a solution together myself. c: I'd appreciate any help, of course, but just a step in the right direction'd be great..!

## Steps to Reproduce the Problem

1. Put together a pickaxe. I am currently using a supercharged heliodor pick with a diamond tip; it was emerald earlier, but I assumed that the emerald upgrades were the problem and tried replacing it.
2. Swing at obsidian.
3. Get no obsidian.
4. Try again with a supercharged helidor pick (no tip); process repeats.

**Comment by SilentChaos512** [comment]
I no longer support 1.12, sorry. I'm too busy working on modern versions.

**Comment by sunlightspectre** [comment]
Modernity backstabs me once again. Don't worry, I'm quite used to it! I did find out that *created* obsidian works as designed... So that's somewhat sorted?

Regardless, I'll be closing this, then. Best!

**Comment by sunlightspectre** [comment]
Also, thanks kindly for the holiday candy! What a cute touch.

**Comment by sunlightspectre** [comment]
Ah, woops, I forgot git sets to re-open. Closing.
