### ISSUE TITLE
[Minor][Cosmetic] Misspelling

### ISSUE THREAD

**Issue by nullspeaker** [SilentChaos512/SilentGems#576]
![image](https://user-images.githubusercontent.com/2228057/229404409-7de52195-6a1b-4415-aea4-bb8ccc07c9d9.png)
[`Volatile`](https://www.merriam-webster.com/dictionary/volatile) is misspelled as [`volitile`](https://www.merriam-webster.com/dictionary/volitile).

**Comment by SilentChaos512** [comment]
I don't believe that trait is from Silent Gear or Silent's Gems. You should report it to whichever mod adds the material for Source Gem.

**Comment by nullspeaker** [comment]
> I don't believe that trait is from Silent Gear or Silent's Gems. You should report it to whichever mod adds the material for Source Gem.

!
That is correct, I must've clicked the wrong tab when reporting the issue >.< Sorry!

[SilentGear Compat issue](https://github.com/dragoni7/Silent-Compat/issues/11)
