### ISSUE TITLE
my minecraft is not generating the gem ores

### ISSUE THREAD

**Issue by Jerossvaldo** [SilentChaos512/SilentGems#577]
## Versions
1.19.4

- **Silent's Gems**: 1.19.4-4.4.2
- **Silent Gear**: 1.19.4-3.4.0 
- **Silent Lib**: 1.19.4-7.2.0
- **Forge**: 1.19.4
- **Modpack**: N/A No
- **Optifine Installed**: Yes

## Expected Behavior

The ores spawn naturally into the world

## Actual Behavior

The ores simply don't generate in the world, but they appear in JEI
Only the bort ore generates

## Links/Images

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1. 
2. 
3.

**Comment by CORRUPTEDUSER404** [comment]
I'm having the same problems, it's like there is no generation criteria or something. I remember you could mod the generation with the config files in a video but it didn't go into detail.

**Comment by CORRUPTEDUSER404** [comment]
Looking at the config file, it seems that this version doesn't have the ability to generate them. Even after transplanting a part of another config file into them that *Should*  tell them to generate. They don't. I think the world gen for the gems is borked.

**Comment by SilentChaos512** [comment]
I fixed this issue in 1.20.1 when I ported the mod. I'll try to backport the fix later.

**Comment by lekonai** [comment]
> I fixed this issue in 1.20.1 when I ported the mod. I'll try to backport the fix later.

hey mate im just wondering when youre gonna do that?

**Comment by SilentChaos512** [comment]
@lekonai I'm in the middle of moving right now, so it will probably take me a few more days at least...

**Comment by lekonai** [comment]
@SilentChaos512 I'll be waiting!! Congrats on the new house/flat though :D

**Comment by SilentChaos512** [comment]
Sorry this took so long to get to. Moving was a much bigger mess than we expected lol.

This has been fixed by 5f6ae13bb5656bc5395e1e8e918262a3bfd532fd and f6acbba0c1cd477a38fcaffa0017079650b00619. Basically, I just copied the fixed code straight from the 1.20.x branch.
