### ISSUE TITLE
Silent Gems - Alexandrite fails to load 1.20.1 - missing harvest tier - Server Fails To Load Datapacks

### ISSUE THREAD

**Issue by Cataraxts** [SilentChaos512/SilentGems#582]
## Versions
SilentGems 4.6.0 - 1.20.1

- **Silent's Gems**: 4.2.0
- **Silent Gear**: 3.6.1
- **Silent Lib**: 8.0.0
- **Forge**: 47.2.4
- **Modpack**: personal modpack
- **Optifine Installed**: No

## Expected Behavior
Server loads the mod like normal and starts successfully.

## Actual Behavior
Server fails to load datapacks and insists on loading without them or not loading at all. Only datapack I added to this server has nothing to do with silentgear/gems/lib, its an origins datapack.

## Links/Images
[latest.log](https://github.com/SilentChaos512/SilentGems/files/14629117/latest.log)

## Steps to Reproduce the Problem

1. Install my base personal modpack
2. Install silent gems + lib + gear
3. Start server environment

**Comment by SilentChaos512** [comment]
Oops, I need to update Gems for the new Silent Gear version... I'll do my best to tackle that tomorrow.

**Comment by SilentChaos512** [comment]
Fixed by 05d75eb821e1af735bd0bdd4f6b968e1a66cff01. Thanks for reporting.
