### ISSUE TITLE
Missing getPlantType override in BlockFluffyPuffPlant

### ISSUE THREAD

**Issue by lumien231** [SilentChaos512/SilentGems#59]
Connected to lumien231/Random-Things#114

The Plant Type of your item and your block are different.
You extend ItemSeeds with ItemFluffyPuffSeeds so the type of the item is EnumPlantType.Crop
You don't override IPlantable.getPlantType in BlockFluffyPuffPlant so it defaults to EnumPlantType.Plains

That's why your seeds can be planted on random things fertilized dirt but get destroyed next "update" because the block (Which has a different plant type) can't stay there.

**Comment by SilentChaos512** [comment]
Thanks for looking into this!
