### ISSUE TITLE
Bug for tool upgrades

### ISSUE THREAD

**Issue by SwordKorn20** [SilentChaos512/SilentGems#6]
I am currently using your latest version of Gems for 1.7.10 and I have finally found an emerald.

I promptly used it to make a tool upgrade (solely for durability as I had diamond upgrade by this point) and applied it to my trusty pick.

The Emerald upgrade lowered the mining level of my pick from 3 (diamond) back to 2. My understanding from the tooltip was it would only apply the mining level 2 if it wasn't already 2 or above. I believe your logic somewhere only checks if it is 2 or below and thus doesn't take into account higher mining levels hence the bug.

EDIT:

After some testing, I have also found that Emerald upgrades are classed as the highest possible tool upgrade. I decided to apply an emerald upgrade first, promptly followed by a diamond one and that refused to work.

**Comment by SilentChaos512** [comment]
Applying a different tip upgrade replaces the existing one, so it is possible to lower the mining level. It is considering the mining level of the base tool, not the upgraded one. Not being able to downgrade is a bit of an oversight, and has been fixed for the next version.
