### ISSUE TITLE
Crash on launch (Guide-API 2.0.2)

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#61]
MC Version: 1.10.2
Forge Version: 2069
Core Mod Version: SilentLib-1.9.4-1.0.12-20
Mod Version: SilentsGems-1.10.2-2.0.27-61

[Crash Log](http://pastebin.com/wQQD65eY)

**Comment by SilentChaos512** [comment]
Guide-API being a pain in the butt again... Love that mod, but everything explodes every other update.
