### ISSUE TITLE
The crystal lamps cannot be switched on or off

### ISSUE THREAD

**Issue by dhalek** [SilentChaos512/SilentGems#64]
I made some malachite lamps but they do not respond to redstone signals. Neither a directly attached lever nor redstone dust can turn them on.
On the other hand the inverted lamps cannot be turned  off by a redstone signal.
Or do I miss something here? I'm using SilentsGems-1.10.2-2.0.28-66 if that matters.

**Comment by SilentChaos512** [comment]
Confirmed, they aren't responding to redstone. I wonder when that broke? Shouldn't be hard to fix though.
