### ISSUE TITLE
[Bug]Server-side crash

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#65]
MC Version: 1.10.2
Forge Version: 2086
Mod Version: 2.0.28-66

Steps to Reproduce: Somewhat random, but when it does happen it's always when you teleport with the return home charm. 
Additional Info: Not sure if relevant. The person also had a refined chaos orb in inventory.

[Crash Log](http://pastebin.com/M2QViEy2)

**Comment by SilentChaos512** [comment]
Not sure if this is Gems or not. It looks like some entity is causing this crash, probably in the area the player is teleporting to. Crash report is vague (not your fault, of course), so it's hard to tell exactly what's going wrong.

Let me know if you find out anything else.

**Comment by SilentChaos512** [comment]
Any news on this one? I was never able to reproduce this.
