### ISSUE TITLE
Shields need to be re-equipped to function properly after eating food(possibly inter-mod or dedicated server issue)

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#66]
I'm using other mods, playing on a private server, and when I tested it with just SilentLib and Silent's Gems in single player, it didn't happen(not with golden apples at least). This leads me to believe it is either an inter-mod issue, or an issue with dedicated servers somehow. In the chance that it is the latter, I figured it would be worth posting this here.

I was testing with a flint shield, as I'm still pretty early-game in my world where I first noticed it. After eating a food item with a shield equipped, the shield doesn't let me block with it - it moves when I right click, like I'm using a different right click function on my main hand item, but it doesn't let me actually raise it to block attacks until I remove it from my offhand and put it back(or swap it with another item then swap it back), at which point it will work again until I eat more food.

I've tried various food items, all from vanilla - cooked potatoes, bread, steak... I don't know what exactly is causing this issue and I'm not sure if it would help, but this is the log:

https://paste.ee/p/GkbYc

SilentsGems-1.10.2-2.0.28-66 is the version I'm using.

Forge version is forge 1.10.2-12.18.1.2092.

Mods in the set:

[1.9.4]Mo' Villages-1.5.2.jar
AppleSkin-mc1.10.2-1.0.4.jar
AutoRegLib-1.0-2.jar
BabyMobs-1.10.2-1.5.jar
BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar
Chameleon-1.10-2.1.7.jar
Charset-0.3.0-pre15.jar
Chisel-MC1.9.4-0.0.6.42.jar
chiselsandbits-12.1-2.jar
CosmeticArmorReworked-1.10.2-v1a-2.jar
CraftTweaker-1.10.2-3.0.10.jar
creeperconfetti-1.2.1-2.jar
disenchanter-[1.9.4]1.4.jar
FastLeafDecay-v11.jar
FlourPower-1.9.4-0.0.2-1.jar
flowergirls-1.10.2-1.1.0.jar
goetia-1.10.2-0.002.0.jar
IvToolkit-1.2.8.5.jar
jei_1.10.2-3.9.5.255.jar
journeymap-1.10.2-5.2.4-unlimited.jar
LevelUp!-0.12-1.10.2.jar
malisiscore-1.9.4-4.1.1-3.jar
malisisdoors-1.9.4-5.0.4-2.jar
MCA-1.10.2-5.2.3-universal.jar
MCMultiPart-1.2.1-universal.jar
modnametooltip_1.10.2-1.6.0.jar
multistorage-1.10.0-1.2.2.jar
Neat 1.3-10.jar
Quark-r1.0-55-3.jar
RadixCore-1.10.2-2.1.3-universal.jar
RecurrentComplex-1.0.3.jar
Reliquary-1.10.2-1.3.3.543.jar
roots-1.10.2-0.202.0.jar
shetiphiancore-1.10.0-3.3.0.jar
SilentLib-1.9.4-1.0.12-20.jar
SilentsGems-1.10.2-2.0.28-66.jar
StorageDrawers-1.10.2-3.2.7.jar
terraqueous-1.10.0-1.2.5.jar
underphangables-1.10.2-1.0.2.jar
Waystones_1.10.2-2.0.5.jar

**Comment by SilentChaos512** [comment]
I've noticed this as well. But it seems only the animation is broken. Blocking damage still works, even without the shield appearing to be raised. I think it happens with vanilla shields as well. I'll look in to this more.

**Comment by Febilian** [comment]
Hmm, alright. I wasn't sure if it was working or not, or whether it did this with vanilla shields. Thanks for taking the time to look at it!
