### ISSUE TITLE
Material Grader block is getting a negative chaos charge value

### ISSUE THREAD

**Issue by Febilian** [SilentChaos512/SilentGems#67]
https://gyazo.com/9ded27152a3ef03bf2e063b9c42e257d

Is this normal? Am I misunderstanding something? It doesn't seem to run out of charge when I put something in it to grade, instead it just makes the negative value go up.

**Comment by SilentChaos512** [comment]
Client-server desync, it's not displaying the correct values. I need to remove that debug text.

**Comment by Febilian** [comment]
Ah, I see. So it's just a display issue.
