### ISSUE TITLE
REQUEST: Can siletGems be updated to work on 1.8.9?

### ISSUE THREAD

**Issue by kwpugh** [SilentChaos512/SilentGems#7]
I love this mod on 1.7.10 and would love to put it into my new 1.8.9 modpack.

**Comment by SilentChaos512** [comment]
I'm currently testing the 1.8.9 version. It will be available later today or tomorrow if I don't find any major issues.

**Comment by kwpugh** [comment]
Awesome, thank you.

**Comment by kwpugh** [comment]
Thanks, I'm testing it on my server right now.
