### ISSUE TITLE
[Feature Request] Sky block support

### ISSUE THREAD

**Issue by scottosx** [SilentChaos512/SilentGems#73]
Originally posted at https://github.com/SilentChaos512/SilentGems/issues/15

scottosx:
> I do see now that SkyResources is supporting your mod for gem production. https://mods.curse.com/mc-mods/minecraft/243482-sky-resources You can even get Chaos essence but it is really a grind, no automation.

> I have also been playing with the Void Ore Miner from Environmental Tech. https://mods.curse.com/mc-mods/minecraft/245453-environmental-tech

> It pulls your ores from the Void but not the Chaos Ore for some reason. I have had it running for several MC days and have pulled over 1000 ores. Again, your gems are coming up but you can't get very far without Chaos Essence.

SilentChaos512:

> I just checked out SkyResources. It does seem to have built-in support for Gems (always nice to see, I thought my work was kind of niche). I can see how getting the Chaos Essence could be a pain.

> An idea I've had before (or maybe suggested to me) was a block that can create Chaos Essence. Ideally something that takes a lot of Chaos energy to produce each piece, but that would be perfect for sky block packs. I'll look into that when I get some time, or maybe I'll ask M4thG33k to add it to Gemulation if he wants.

**Comment by scottosx** [comment]
It turns out that the Void Resource Miner from Environmental Tech uses a config file and not the ore dictionary. I assume the reason is that he is assigning laser colors to each entry.

The mod author had a few gemstones in their but not your complete set. I have added all your ores with the related color and will submit to the ET author.

This is a text version of the minable.json config file for the Void Ore Miner.

[minable.txt](https://github.com/SilentChaos512/SilentGems/files/573840/minable.txt)

I would say that it will be included as it gives more reasons to craft the laser filters.

**Comment by scottosx** [comment]
A Chaos battery type block would be a good idea. I would suggest that it has a relatively small capacity and is for early game just to get some starting essence. At least enough to craft a core. It is like the Diluted Pool in Botania.

From there you could probably use the Chaos altar and if needed the Gem Transmutation Device from Gemulation.

BTW, Chaos nodes do appear in Void worlds. I don't know the frequency. This is pretty much mid to late game though as you need flight or a jet pack to get to them. I found one about 100 blocks away from spawn and moved it.

**Comment by scottosx** [comment]
Submission to Environmental Tech project:

https://github.com/ValkyrieofNight/EnvironmentalTech/issues/8

**Comment by SilentChaos512** [comment]
I'm thinking I might partially repurpose the Chaos Altar for making Chaos Essence. It was made much less useful in the rewrite, since nodes/pylons can directly recharge items the player is holding. The altar will still be able to recharge items. As well as the altar handling essence production, I'll add a new block for early game production, as you suggested.

I did notice nodes appearing in the void world. I feel like that's not a bad thing though. Mod pack creators and users can change the frequency (or disable them) in the config file. I imagine you could get to them using the water bucket trick as well. Pour down water and swim down the stream placing blocks below the platform, then build out. That would likely require a lot of blocks, but it's an option.

**Comment by SilentChaos512** [comment]
Still playing around with this, likely needs some balancing. The altar is now cheaper to craft (4x less chaos essence) and has a transmutation recipe system (no JEI support yet). Added a third slot to the altar for a catalyst (currently unused).

This will be in version 2.1.2-81. Let me know what you think after you have some time to play with it.

**Comment by scottosx** [comment]
I wanted to let you know that I have been testing this extensively now on a new map. I am playing the Myriad Caves CTM (Conquer the Monument) map with a set of custom mods and configs. 

By design that map is UHC and resource starved. I am treating it as essentially a SkyBlock with a whole mess of meanies trying to kill me.

Your new inclusions make play on this type with Silent Gem's a joy. I customized the Ex Nihilo Omnia sieve recipe for gravel to include Chaos shards. Along with the improved mechanics of Sky Resources all aspects of your mod are within reach and well balanced.

The Chaos altar transmutations and glow rose fertilizer are very well done. Kudos to you my friend.

If you have ever thought that Minecraft was too easy in combat but also enjoy building tech trees from nothing and overpowered weapons with plenty of targets, try out Myriad Caves in this fashion.

Sorry for the late reply but I am exploring the synergy between many mods and play styles.
Silent Gems though is always near the top of my list of favorites. Again great work.
