### ISSUE TITLE
[1.10.2] Huge amounts of serverside log spam in new version

### ISSUE THREAD

**Issue by b0bst3r** [SilentChaos512/SilentGems#76]
Getting this spamming in the server console pretty rapidly 

http://i.imgur.com/izc0acr.png

SilentsGems-1.10.2-2.1.2-81
SilentLib-1.9.4-1.0.12-20
forge:1.10.2-12.18.2.2123

**Comment by SilentChaos512** [comment]
I tried running a server and I'm not seeing anything unusual. Do you have a node or pylon right next to a Chaos-accepting block or something like that?

**Comment by b0bst3r** [comment]
Apart from the chaos altar?  I thought that was the idea for a chaos altar and pylons to be next to each other?

**Comment by SilentChaos512** [comment]
I was wondering if it could be caused by senders (pylons/nodes) directly touching the receiver (altar, etc). I just tested that and it doesn't seem to cause any problems for me.

**Comment by b0bst3r** [comment]
I'm beginning to wonder if this is chukloader related, there's been no one on the server today and I just checked I have absolutely massive logs, this  http://pastebin.ubuntu.com/23468604/ is the current log since server auto restarted.

**Comment by SilentChaos512** [comment]
Probably is related to chunk loading. Chaos packets lose their targets when chunks unload. They're **supposed** to save that, but it seems they don't. I'll see what I can do.

**Comment by b0bst3r** [comment]
It's completely outside the chunkloaded area, but since I came to the location all the log spam has ceased.  I also updated the post above with screenshots

**Comment by SilentChaos512** [comment]
I think I solved it. It was a dumb programming mistake with loading the target position. This will also fix packets disappearing on world load.
