### ISSUE TITLE
[1.10.2] Gems showing unlocalised name in the Nether

### ISSUE THREAD

**Issue by b0bst3r** [SilentChaos512/SilentGems#78]
Not sure if another mod is doing this but in this screenshot http://i.imgur.com/qQuPQEd.png you can see WAWLA in the top left corner and TheOneProbe in the bottom right corner showing this name for all Nether gem ores (OW is fine).  Makes it kinda hard to figure out what is what.

SilentsGems-1.10.2-2.1.2-81
SilentLib-1.9.4-1.0.12-20
forge:1.10.2-12.18.2.2122

**Comment by SilentChaos512** [comment]
For me, TheOneProbe is displaying the unlocalized name (because the unlocalized name it's trying to use is wrong) and Waila/Wawla and WIT are fine. And it does seem to be just dark gem ores for some reason...

**Comment by b0bst3r** [comment]
pretty sure that's WAWLA in the top left corner of the screen showing it incorrectly, we don't use WAILA so maybe that's correcting it, or that's what you're seeing.

**Comment by SilentChaos512** [comment]
Oh, I thought Wawla required Waila.

I was able to get the name fixed, but TheOneProbe still shows a missing texture. I'll see if I can get that fixed as well.
