### ISSUE TITLE
Crash with Silents Gems

### ISSUE THREAD

**Issue by DatrixTHLK** [SilentChaos512/SilentGems#79]
Hello,

Had a crash with this mod as the errored file. If you know of this already, then you may close this and I shall wait.
https://gist.github.com/DatrixTHLK/38caf31398513f161f1eb527bf08c1ef

Minecraft: 1.10.2
Forge: 12.18.2.2125
SilentLib: 1.1.0-23
SilentsGems: 2.1.3-82

**Comment by SilentChaos512** [comment]
You need to update Silent's Gems. The latest Silent Lib changed some things and all mods that use it must be updated.

I'll leave this issue open for a day or two in case anyone else encounters the same problem.

**Comment by DatrixTHLK** [comment]
Is Silent Gems 2.1.3-82 not up to date?

**Comment by SilentChaos512** [comment]
Latest is 2.1.4-83 (https://minecraft.curseforge.com/projects/silents-gems/files/2345206), released at the same time as Silent Lib 1.1.0-23.

**Comment by DatrixTHLK** [comment]
Yeah I just noticed when I went there. Thanks.
