### ISSUE TITLE
Nodes spamming the logs

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#82]
MC: 1.10.2
Forge: 2121
Mod: SilentsGems-1.10.2-2.1.4-83

While reading through logs trying to pinpoint things that had potential to cause issues or extra resource usage, this seemed to merit a look.  I'd prefer to let you know things and have it turn out to be nothing, than not say something and have it go unnoticed.

This is spammed very very often on the server.
[Relevant spam example](http://pastebin.com/xXtqb2A3)

As always, thank you for your time and hard work.

**Comment by SilentChaos512** [comment]
I was afraid this issue wasn't completely fixed. I know _what_ is happening, but I'm having trouble understanding _how_ it happens. Couple questions:
- Singleplayer or server?
- Any chunkloaders involved?

**Comment by MysticAura** [comment]
Server and the chunk loaders used would be extra utils ward.. Problem being that there are 15 playing on the server (TLove's sub-server) and no concrete way of seeing which node is firing. <insert grumble about 1.10.2 not having opis>

**Comment by SilentChaos512** [comment]
Is the issue fixed in 2.1.5?

**Comment by MysticAura** [comment]
Possibly. I haven't noticed it spamming yet..however I'm creating a new issue for a crash the server had today.

**Comment by SilentChaos512** [comment]
I'll consider this closed. Let me know if you spot anything, but it shouldn't pop up anymore.
