### ISSUE TITLE
java.lang.NullPointerException with Silent Gems or Silent Lib being the culprit

### ISSUE THREAD

**Issue by DatrixTHLK** [SilentChaos512/SilentGems#83]
Hello,

Not sure why, isn't this mod updated to the latest along with your Library mod? I know for a fact this mod was working yesterday night but now it doesn't want to work. All mods including the Library mod are updated to the latest version.

Crash Log: https://gist.github.com/DatrixTHLK/c3a410136795a291319ef28998d5f863

Minecraft 1.10.2
Forge: 2151
SilentLib: 1.1.0-23
Silent Gems 2.1.4-83

**EDIT:** Deleting config files didn't work...hmmm...I took out a mod I recently added in to see if it is causing incompatibility with yours. It is Ex Nihilo Adscencio. I will reference the issue with the mod author.

**Comment by SilentChaos512** [comment]
Something to do with an enchantment by the looks of it, although I don't have time to look at my code at the moment. There's probably an additional sanity check or two that I could do as well.

**Comment by DatrixTHLK** [comment]
Take your time. I can wait. 👍

**Comment by SilentChaos512** [comment]
I don't think there's anything I can do on this one. We'll just have to wait for Ex Nihilo Adscensio.
