### ISSUE TITLE
Crash during game loading

### ISSUE THREAD

**Issue by Plurp13** [SilentChaos512/SilentGems#85]
I had a crash related to this mod but realized there was an update, so I updated and it crashed during loading...

http://pastebin.com/JMJEu7RD There's the crash from this time.

http://pastebin.com/t02wjPZ3 And there's the first crash.

**Comment by SilentChaos512** [comment]
You were on the right track... but you need to update Silent Lib as well.

**Comment by Plurp13** [comment]
Oooooh ok, right, usually when a dependency is missing/outdated it tells me instead of out right crashing so I didn't think of it haha. Thanks ^.^

**Comment by SilentChaos512** [comment]
Yeah, that's my fault. It will be fixed in the next version.

**Comment by Plurp13** [comment]
Yay~
