### ISSUE TITLE
[Crash][Bug] Crash when trying to craft supercharged armor

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#87]
MC: 1.10.2
Forge: 2151, 2166
Mod Versions: SilentsGems-1.10.2-2.1.5-84, SilentsGems-1.10.2-2.1.6-86

Issue: Crash to desktop

Steps to Reproduce: Put the recipe for supercharged armor into a crafting table > crashes when you try and pull out the result.

[Crash Log](http://pastebin.com/PAhajWFP)

I'm starting to feel like a thorn in your side *hides*

**Comment by SilentChaos512** [comment]
Already fixed (issue #86). I'll upload a patched version in a minute.
