### ISSUE TITLE
[1.11] Issue when placing blocks with tools

### ISSUE THREAD

**Issue by Katallask** [SilentChaos512/SilentGems#88]
Love the mod! it's the best minecraft mod out there IMO.. my son and I love it so much we were actually bummed when 1.11 came out and we had go to back to vanilla.. :)    Just one issue i've found.. when I use a flint tool to place a gravel block, the tool vanishes.. I'm guessing this isn't by design, since I was getting ready to grind gravel to get more flint using the double mouse button trick?    (that's the best mechanic anyone ever introduced btw.. having to switch tools sux!! )  anyway, keep up the rockin good work, and if you happen to get a chance to check out the issue, i'd be much appreciative!

**Comment by Katallask** [comment]
if it helps, the tools that vanished were iron tipped flint shovel and pick

**Comment by Katallask** [comment]
went back and tested, and plain flint tools also vanish, so not the tips.

**Comment by SilentChaos512** [comment]
I had a feeling right-click to place might be broken in 1.11, just hadn't gotten around to testing it. I would guess all tools would be affected. Interesting that they disappear though.

Thanks for reporting this, and I'm glad you like the mod! I'll look into fixing this as soon as possible.

**Comment by SilentChaos512** [comment]
Suggested workaround for now is to place the block you want to place in your off-hand. Holding down left- and right-click at the same time will work like that. At this point, I'm not even sure if this is fixable because of some changes in 1.11, but I might come up with something.

**Comment by Katallask** [comment]
Thank you for the workaround!   Yeh, not really surprised to hear that it might not be fixable, but we'll keep our fingers crossed!   Thanks for replying too!  (it's nice to have people who actually look at things people report!)  I've been trying the mod through different scenarios with the tools and so far the right click issue is the only bug i've run across! (I've been testing by playing in survival, so it takes longer.. ;) )  good work!

**Comment by Katallask** [comment]
btw, this works on the current version (which rocks!) lots of hard work on that I can tell!  keep up the good work.
