### ISSUE TITLE
Issue with NoGlint upgrade

### ISSUE THREAD

**Issue by BlazingGamer** [SilentChaos512/SilentGems#9]
I think a screenshot is enough to describe this...
![2016-01-28_19 30 05](https://cloud.githubusercontent.com/assets/13196222/12650937/d3f86daa-c5f5-11e5-98b8-a8aeac0871ef.png)

**Comment by BlazingGamer** [comment]
I'm using SilentGems 1.3.9 build 164 for MC 1.7.10.

**Comment by SilentChaos512** [comment]
Looks like only the tooltip is broken. Should be an easy fix.
