### ISSUE TITLE
Problem with Ruby Ore 1.11.0

### ISSUE THREAD

**Issue by MoonCutter2B** [SilentChaos512/SilentGems#91]
Problem: when I mine the ruby ore with a iron pickaxe I don't get any rubies.

I also have Tech Reborn and Ore dictionayConverter installed.
I't might be that they are not playing nice with eachother.
I have tried mining both rubies from SilentGems and from Tech Reborn with the same result :(
Other gems work so far, its only the Rubies that fail.

Forge for 1.11.0 - 2189

**Comment by SilentChaos512** [comment]
I was able to reproduce this issue. Seems to be a Tech Reborn issue. Their ruby ore is broken, even without Silent's Gems installed. Also occurs without OreDictionaryConverter. Please report this to Tech Reborn, if no one else has done so already.
