### ISSUE TITLE
Chaos Node Crash on Server

### ISSUE THREAD

**Issue by lilmoefow** [SilentChaos512/SilentGems#92]
Lately our server has been getting terrible TPS even when no players are logged on, and we are experiencing lots of these crashes today.

http://pastebin.com/h4aZHkX7

If i can provide any other info let me know.   I am just the server admin, i do not actually play on the pack/map.

**Comment by SilentChaos512** [comment]
How long has this been an issue and how old is the world? Any mods you have added recently?

**Comment by lilmoefow** [comment]
Issue just started this morning i believe,  Map is only a few weeks old.  Don't think any new mods were added no. 

I think Lame might have updated the server this morning, going to ask him one he is awake.  Sorry for the lack of decent info.  Will update once we have done some roll backs and testing tomorrow.

**Comment by SilentChaos512** [comment]
Alright. Also had some others look at the crash report, there's a chance it could be hardmodetweaks. I'd recommend updating a couple mods at a time after rolling back and see where that goes.

**Comment by b0bst3r** [comment]
It looks like this may have been caused by ftb utils chunkloading - certainly the low TPS which somehow completely messes up the chaos nodes in the world and they end up giving thousands of "calls" all over the place.  This in turn caused 100% CPU usage and low TPS issues.

**Comment by SilentChaos512** [comment]
@b0bst3r I think I get what you're saying. I started playing on a server recently, and I've noticed something similar with my pylons. They seem to be outputting the chaos transfer packets when I'm away, and the packets are not updating, just collecting in one spot. Then they start moving when I teleport back. Is that what you mean?

**Comment by b0bst3r** [comment]
Yes that happens but I'm not sure if that was the cause or not, this is basically what happened 

http://imgur.com/ay9jrb5
http://imgur.com/Znn849R

**Comment by SilentChaos512** [comment]
@b0bst3r What generates that?

**Comment by b0bst3r** [comment]
Nallars tickprofiler but we've tried several tools and they all point to the same thing, the chaos nodes.

**Comment by SilentChaos512** [comment]
Any way to know where the problem nodes are, or what's around them? From the screenshots I can tell one or more nodes are attacking hostile mobs (attack and levitation packets). More mobs mean more activity, of course. I guess I could start by capping the number of mobs that can be attacked. I'm also grabbing a list of nearby hostiles every tick, which should definitely be changed.

Still, it's hard to imagine the nodes being such a big problem, unless the server is weak or players have done something truly crazy... like putting dozens of nodes on a massive mob grinder. Don't get me wrong, I'd like to fix this. I'm just trying to understand what's going wrong so I can do something about it.

**Comment by b0bst3r** [comment]
Yeah there were co ords on the top 5 culprits, I visited them and they were just nodes in the wild with nothing nearby, which led me to believe it was flagging up all the nodes which were on the map.  Once I creatively removed those nodes it just moved onto another set of 5 randomly generated, which again pointed to it being all nodes.  I just think something (probably another mod) caused this and it's unlikely that the actual cause can ever be found.  The map itself has gone through a lot of mod updates and has likely weakened the map as a result, we've since started a new map and it behaves as you would expect.  I do have the map if you're interested in downloading it and the pack is available on the atlauncher.

**Comment by SilentChaos512** [comment]
I wouldn't mind taking a look at the world, if uploading it isn't inconvenient for you.

**Comment by b0bst3r** [comment]
Have you used ATLauncher before @SilentChaos512 if not I will put a step by step in for you?

**Comment by SilentChaos512** [comment]
It's been a while, but I've used ATL before.

**Comment by b0bst3r** [comment]
http://www.mediafire.com/file/b9br8p6bhutdht4/world.zip

On Atlauncher you're looking for a pack called Bevo's Superstitions either version 2.0 or 2.1 (have not tried it with the latest 2.2.

To find some co-ordinates of people bases simple OP yourself and do /mc colonies list 

Although you shouldn't need to find people's bases as the map goes into silly mode with no one on.  Lastly I haven't tried this in Single play only SMP.
