### ISSUE TITLE
Suggestion: Change damage type of projectiles to magic

### ISSUE THREAD

**Issue by darklordwonton** [SilentChaos512/SilentGems#94]
I looked at the code for magic projectiles and noticed they do 'thrown' damage, I think it would make more sense for them to do 'magic' damage given they're magic projectiles (also would make their damage boosted by effects/items from other mods that boost magic damage and blocked by magic blocking effects/items from other mods.

**Comment by SilentChaos512** [comment]
Good point. No idea why I chose thrown damage in the first place.
