### ISSUE TITLE
Server Crash on Startup 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#95]
https://gist.github.com/P3rf3ctXZer0/d163e4967a00f6e5df59eebcc08ad022

**Comment by SilentChaos512** [comment]
I swear it seems like every new feature I add breaks servers at least once. Easy fix though, sorry for the trouble.

**Comment by P3rf3ctXZer0** [comment]
@SilentChaos512 is the fix coming out in a bit? I am waiting to update some things if it is.

**Comment by SilentChaos512** [comment]
I'll be doing a build in a minute, had a couple other issues I was just wrapping up.

**Comment by SilentChaos512** [comment]
Should be up: https://minecraft.curseforge.com/projects/silents-gems/files/2361862
