### ISSUE TITLE
Crash with tinker's construct

### ISSUE THREAD

**Issue by darklordwonton** [SilentChaos512/SilentGems#96]
I got this crash when loading the game: http://pastebin.com/pCKPJaw5

I have tinkerstools disabled in the tinker's construct config.

**Comment by SilentChaos512** [comment]
I get a completely different crash when I try disabling tinkers tools. How are you doing it, setting TinkerTools in TinkerModules.cfg to false?

**Comment by darklordwonton** [comment]
Okay so I figured out the problem, I was using an outdated version of ticon :P. That explains why it couldn't find the bow class.
