### ISSUE TITLE
Issue on worldgen on new version (1.10.2)

### ISSUE THREAD

**Issue by GordonHollow** [SilentChaos512/SilentGems#97]
I update SilentGems to last version and have issue when generate new chunks
World server just stopped (don't drop anything and can't enter in any GUI)

Console says this: 
[Client thread/DEBUG] [Silent's Gems/]: null
[Client thread/INFO] [STDOUT/]: [net.silentchaos512.lib.util.LogHelper:debug:19]: null
this 2 lines repeat many times

**Comment by GordonHollow** [comment]
Sorry, it Quark new features in worldgen issue, not SilentGems fault

**Comment by SilentChaos512** [comment]
I'll be sure to remove that debug line at least, it's not needed.
