### ISSUE TITLE
Area Miner and Lumberjack need to indicate lack of Chaos

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#98]
Need to verify which versions of Minecraft this affects.

**Comment by SilentChaos512** [comment]
Probably a misunderstanding, I believe it's just a lack of Chaos on the player. Everything seems to be working. There's needs to be some feedback on that, instead of the ability just not working.

**Comment by SilentChaos512** [comment]
Fixed by aea95b939f68a24626a64e43ec42afb11dbf2f06.

**Comment by cyberpunkbln** [comment]
Hello,
sorry i don't understand this. I use the latest Beta SilentsGems-1.11.x-2.3.7-161 and Supercharged Axes don't have Lumberjack-Effect like Lumberjacks-Mods. Can you shortly explain how i can use the Lumberjack on Supercharged Axes? Thx.

**Comment by SilentChaos512** [comment]
Use the "Toggle Special" keybinding (defaults to Shift+C) to turn Lumberjack on/off. Your crosshairs should change when Lumberjack is on.

**Comment by cyberpunkbln** [comment]
thx
